### ISSUE TITLE
grunt.utils.spawn does not call success callback

### ISSUE THREAD

**Issue by iros** [gruntjs/grunt#100]
``` javascript
grunt.utils.spawn({
  cmd: "zip",
  args: ["-r", conf.dest, conf.src],
  opts : {
    cwd : conf.cwd
  }
}, function(err, result, code) {
  grunt.log.writeln("Done"); // this never gets called
  if (err) {
    grunt.log.error(err);
    done();
    return;
  }
});
```

**Comment by br4nnigan** [comment]
> Is there a simple solution?

	var done = this.async();
	grunt.utils.spawn({
		cmd: "zip",
		args: ["-r", conf.dest, conf.src],
		opts : {
			cwd : conf.cwd
		}
	}, function(err, result, code) {
		done();
		grunt.log.writeln("Done"); 
		if (err) {
			grunt.log.error(err);
		}
	});
