### ISSUE TITLE
Any chances for streams support for tasks?

### ISSUE THREAD

**Issue by chicoxyzzy** [gruntjs/grunt#1000]
Take a look at [Gulp](https://github.com/wearefractal/gulp). Any chances next versions of Grunt will support streams for tasks?

**Comment by joseph-jja** [comment]
Question: is there any reason that a task cannot use streams with grunt today? So if I were to write a task and had a list of files, is there any reason that this.files.forEach couldn't use streams to manipulate the files?

**Comment by monolithed** [comment]
+1
