### ISSUE TITLE
Grunt return 0 even if a protractorjs test fail

### ISSUE THREAD

**Issue by manuelmazzuola** [gruntjs/grunt#1114]
Grunt returns 0 even if a protractorjs test fail and consequently jenkins return a false positive.
Instead when a karmajs test fail grunt returns with a fail status code as I expect.
Is this a grunt or a protractor issue ?

```
Running "protractor:run" (protractor) task

------------------------------------
PID: 12690 (capability: phantomjs #1)
------------------------------------

Starting selenium standalone server...
Selenium standalone server started at http://10.11.12.3:51446/wd/hub
F

Failures:

  1) E2E Scenario should redirect to login page
   Message:
     Expected false to be truthy.
   Stacktrace:
     Error: Failed expectation
    at null.
...
...
...
==== async task ====
asynchronous test function

Finished in 1.695 seconds
1 test, 2 assertions, 2 failures

Shutting down selenium standalone server.
[launcher] Runner Process Exited With Error Code: 1
>> 
>> Test failed but keep the grunt process alive.

Done, without errors.
```

**Comment by chitwant82** [comment]
@adjohnson916 : I use keepAlive in protractor conf and in the case of test failures grunt exits with code 0, however on the CI server (Jenkins in my case) I use text finder plugin to search in console output for specific pattern like # spec, 0 failures. If this is not seen mark build fail. You can also write a shell script as a post build action to get console output via curl and parse for specific string and mark the build pass/fail accordingly

**Comment by rohitsakala** [comment]
@chitwant82 any other simple solution ? rather than checking for patterns ?

**Comment by ArmorDarks** [comment]
You can try to use [`process.on('exit')`](https://nodejs.org/api/process.html#process_event_exit) in Gruntfile, check for code and do a cleanup before exit.
