### ISSUE TITLE
EPERM error while using 'grunt-contrib-clean' Issue with grunt compilation

### ISSUE THREAD

**Issue by pvsm** [gruntjs/grunt#1133]
I am working with Windows 7 Enterprise SP1, node: v0.10.28 and grunt v0.4.4. I am using grunt to generate CSS files from my SASS project and have been using ''grunt-contrib-clean" plugin to delete the CSS files before generating a new ones. Recently I have not been able to generate the CSS files as I am getting the following error messages and the running of the task stops:

"Warning: Unable to delete filename (EPERM, operation not permitted ) filename. Use --force to continue". 
Aborted due to warnings.

I have tried looking for this issue but I haven't had any luck. Seems like no one knows the exact answer on the forums too. Any thoughts on this? I have been looking at this issue for the past few days and haven't been able to find any solution. Thank you.

**Comment by reggaeguitar** [comment]
Instead of npm cache clean I ran npm cache verify at npm's recommendation, removed node_modules and ran npm install again and this fixed the issue for me
