### ISSUE TITLE
Set a property of an array element with grunt.config.set

### ISSUE THREAD

**Issue by fredw** [gruntjs/grunt#1136]
I'm trying to set the property of an element of an array in the settings of grunt, so using the API method `grunt.config.set`, but doesn't works:

Here is a example:

<pre>
module.exports = function(grunt) {

    grunt.initConfig({
        persons: {
            list: [
                {name: 'First name'},
                {name: 'Second name'},
            ]
        }
    });
    
    grunt.registerTask('default', function() {
    
        // Change name of first person
        grunt.config.set('persons.list[0].name', 'Changed name');
    
        var persons = grunt.config('persons');
        
        persons.list.forEach(function(person, i) {
            grunt.log.writeln('Name: ' + person.name);
        });
    });
};
</pre>

The name of person don't changes.
What I'm doing wrong?

**Comment by nikkwong** [comment]
Isn't this incorrect as far as javascript goes? Why do you access the array index with dot notation?
