### ISSUE TITLE
Preserve CLI args when spawning child grunt process

### ISSUE THREAD

**Issue by dylancwood** [gruntjs/grunt#1172]
When spawning a child process using `grunt.util.spawn`, with the option `grunt: true`, it might make sense to automatically pass any of the current process' CLI arguments to the child. For example, if the parent grunt process is running in `--debug` and/or `--no-write` mode, it would make sense that any child processes should as well. Failing to pass `--no-write` to the child process could result in writing to disk when that behavior is not desired.

While it is true that a developer can easily pass the arguments that they deem important to the child process, it appears that many of the plugins that I have found do not. 

I look forward to hearing what you all think.

_Update_: I looked into implementing this, and found that the spawn method is located in the grunt-legacy-util package. Since it seems that development has stopped on that repo, what path forward do your recommend? Would it be a good idea to start a separate grunt-spawn project?

Thanks

**Comment by sumeetattree** [comment]
Any update on this? It just tripped me up. I had to manually write in logic to trap `--no-write` in custom multitasks.
