### ISSUE TITLE
update to newer version of iconv-lite for dependencies

### ISSUE THREAD

**Issue by hyunchulkwak** [gruntjs/grunt#1183]
iconv-lite(https://github.com/ashtuchkin/iconv-lite) is now at version of 0.4.4, which supports more encoding options, including euc-kr(Korean), euc-jp(Japanese), and etc. I've been in need of using euc-kr for grunt.file.defaultEncoding and used workaround to support it. It might be great if i don't need to clone their newest repo for me setting up grunt.

**Comment by shama** [comment]
Done on af387a0233bc73e6ce5b7f186341dda2cc14f1dc
