### ISSUE TITLE
Upcoming changes to npm / node-semver

### ISSUE THREAD

**Issue by jmeas** [gruntjs/grunt#1186]
There are two changes coming to npm that may require some changes in the way we specify grunt dependencies.

The first is [the removal of `peerDependencies`](https://github.com/npm/npm/issues/5080). As you might already know, Grunt plugins typically specify their relationship to Grunt itself as a peerDep, so we'll need to figure out their new relationship.

The second change is [an update to the behavior of the caret operator](https://github.com/npm/node-semver/commit/3f676f510b311f63bc1dac2f92174f589bc5a14b). Depending on our decision above we might also want to change this.

=====

Regarding peerDependencies, we have at least three options:

1. Remove grunt from the dependencies altogether.
2. Add it to dependencies.
3. Add it to devDepedencies.

I'm not entirely confident with my understanding of the consequences of each of these choices, so I'm can't offer my opinion on which of these I think would be best.

Regarding the caret change:

The new behavior locks `^0.4.0` into `0.4.0` only, whereas it used to be equal to `0.4.x`. So, if we'd like to continue having that same functionality as before, then I'd suggest we use `0.4.x`. A similar alternative is `~0.4.0`, which differs in that it also pulls in prereleases.

**Comment by shama** [comment]
Noting that the change in behavior of the caret operator was reverted: https://github.com/npm/node-semver/commit/107ed7b7175aa1d2c7e789fc55e6fb564ae0a67e

**Comment by shama** [comment]
With that this can now be closed as we have an issue opened already for handling peer dependencies: https://github.com/gruntjs/grunt/issues/1116
