### ISSUE TITLE
Error whith grunt-init when copying a template with fontawesome

### ISSUE THREAD

**Issue by ashraffayad** [gruntjs/grunt#1193]
This error disappears when I remove the file fontawesome-webfont.woff.

Writing app/css/fonts/fontawesome-webfont.woff...>> A special character was detected in this template. Inside Template Tags, the

> > \n and \r special characters must be escaped as \n and \r. (grunt 0.4.0+)
> > Warning: An error occurred while processing a template (Unexpected token ILLEGAL). Use --force to continue.

**Comment by coolholic** [comment]
Had the same error and problem with woff font! Solved and working fine by adding 
{noProcess: 'fonts/**'} to the init.copyAndProcess ....
init.copyAndProcess(files, props, {noProcess: 'fonts/**'});
