### ISSUE TITLE
Use nopter

### ISSUE THREAD

**Issue by stevenvachon** [gruntjs/grunt#1197]
It would lighten the Grunt source code and still offer the same features.

When I wrote [nopter](https://www.npmjs.org/package/nopter), I was heavily inspired by the Gruntfile syntax as well as how Grunt currently uses [nopt](https://www.npmjs.org/package/nopt).

Let me know what you think and if it's missing anything that you need.

**Comment by vladikoff** [comment]
We shall stay with nopt for now, it is maintained by the npm community

**Comment by stevenvachon** [comment]
nopter uses nopt.
