### ISSUE TITLE
NODE_PATH support / separate task load path (grunt.file.setBase)

### ISSUE THREAD

**Issue by mechanicalduck** [gruntjs/grunt#1214]
Grunt doesn't use the NODE_PATH environment variable 
which is used to install node modules to a different directory.
This is necessary when using shares which don't support symlinks or 
because of the recursive dependencies path length limit problem on Windows fs/share.

It is possible to specify another grunt root path using the grunt.file.setBase method.

However, while this solves the problem of changing the grunt.js search (by grunt-cli) and task load path, 
the cwd is also changed which means that workspace files aren't reachable by relative paths anymore.
It is practicably not possible explicitly setting the cwd for all those grunt tasks.

**Comment by ktosiek** [comment]
I have a similar problem - I want to put the local node_modules in python's virtualenv (I'm working on a mixed project with scripts for managing virtualenvs already in place)
