### ISSUE TITLE
Prevent expanding templates

### ISSUE THREAD

**Issue by justinbmeyer** [gruntjs/grunt#1231]
I am working on a grunt plugin where I want users to be able to pass a template string to my plugin which will make use of that template.  For example:

``` js
initConfig({
   documentjs: {
    title: "Grunt - <%= pageName %>"
  }
})
```

The problem is that [grunt.template](http://gruntjs.com/api/grunt.template) automatically expands this, so my plugin sees: `"Grunt - "`.

Currently, lodash only supports the following workaround:

``` js
initConfig({
   documentjs: {
    title: "Grunt - <%= '\\<%= pageName %\\>' %>"
  }
})
```

I've created a [lodash issue](https://github.com/lodash/lodash/issues/740), to allow:

``` js
initConfig({
   documentjs: {
    title: "Grunt - <%%= pageName %>"
  }
})
```

But, that may or may-not happen.  Would you consider some type of flag to prevent escaping a path in the config.  For example:

``` js
grunt.template.preventExpanding("documentjs")
```

I'm happy to add this if you think it's a good idea.

**Comment by Izzmo** [comment]
This needs to be in the documentation. Such an annoying little thing and have it no where to find out but some obscure issue on Github.

**Comment by shama** [comment]
@Izzmo Patches welcome! https://github.com/gruntjs/grunt-docs
