### ISSUE TITLE
Add method to shutodwn current grunt instance and all child process

### ISSUE THREAD

**Issue by johannesjo** [gruntjs/grunt#1244]
I know there is grunt.fatal and grunt.error, but both are not able to shutdown grunt if a task is run as a child proccess using concurrent or watch. It would be very nice to have a global shutdown method, to kill all currently running tasks. An usage example would be, to prevent multiple instances of grunt from messing up each other.
Something like this:
```
  grunt.registerTask('kill', function() {
    grunt.shutdown();
  });
```

**Comment by shama** [comment]
Grunt doesn't necessarily manage processes. You can kill the process Grunt or any node script is running under with `process.exit()` though.
