### ISSUE TITLE
grunt.aliasTask - any interest?

### ISSUE THREAD

**Issue by mattkime** [gruntjs/grunt#1246]
Idea - there should be functionality for aliasing task names. 

---

this is something i've built myself that i thought others may find useful as well. 

```
     var aliasTask = function( orgTask ){
         return function(){
             var task = orgTask,
                 i, j;

             for (i = 0, j = arguments.length; i < j; i++){
                 task += ":" + arguments[i];
             }

             grunt.task.run( task );
         };
     };
```

usage
```
grunt.registerTask( 'style', aliasTask('css') );
```

proposal (that would do the same thing)
```
grunt.aliasTask('orginalTask','aliasName')
```

I work on a large team of developers, we have a complex build - a little flexibility can be very helpful.

thoughts?

**Comment by phietrt** [comment]
Only seem to add complexity with few use cases.

**Comment by gwicksted** [comment]
(for the admins) This issue is safe to close as grunt already supports the requested functionality.
