### ISSUE TITLE
Use JSCS to enforce codebase styleguide

### ISSUE THREAD

**Issue by mrjoelkemp** [gruntjs/grunt#1247]
Any interest in bringing JSCS to the grunt codebase?

I'd gladly submit a PR integrating JSCS into travis and fixing existing violations of the [styleguide](http://gruntjs.com/contributing#syntax).

**Comment by arthurvr** [comment]
Wasn't this fixed in https://github.com/gruntjs/grunt/pull/1287?

**Comment by mrjoelkemp** [comment]
Yes, sorry for missing the reference. There were weeks between the issue and the PR.
