### ISSUE TITLE
Error loading Gruntfile.coffee: Error: Use CoffeeScript.register() or require the coffee-script/register module to require .coffee.md files.

### ISSUE THREAD

**Issue by nloding** [gruntjs/grunt#1254]
This started happening randomly - I'm not aware of any changes made to my environment. I was able to resolve it by changing line 16 of grunt.js from:

`require('coffee-script');`

to:

`require('coffee-script/register');`

I am not sure if this is the best option so I haven't submitted any pull requests or anything.

**Comment by criloz** [comment]
+1

**Comment by markwainwright** [comment]
Please merge #1331.

Right now I use Grunt to run my specs, via `grunt-mocha-test`. This means that my specs can only use CoffeeScript language features that were available in the insanely old version that Grunt uses. This is pretty crazy.

**Comment by shama** [comment]
Fixed on ea07ee5cacd9eba1e0a1d0e5bd90b1e4ff96552e
