### ISSUE TITLE
grunt.task.run() Fails silently

### ISSUE THREAD

**Issue by jd-carroll** [gruntjs/grunt#1265]
When calling a grunt task from node directly, calls to subtasks fail silently.

I am trying to link my Grunt tasks into my Cordova build, through the build hooks Cordova provides.  I call Grunt from a script that looks like:
```
#!/usr/bin/env node
var grunt = require('grunt');
grunt.tasks(['build']);
process.exit(0);
```
From the build task, I call several other subtasks similar to:
```
grunt.task.run('wiredep');
````
The subtasks never run and no error / warning is displayed.

Thanks,

JD

**Comment by shama** [comment]
Currently Grunt requires a Gruntfile to run and running tasks in the way you're trying isn't supported. If you would like to sponsor a RFC to implement it, feel free to submit here: https://github.com/gruntjs/rfcs Thanks!
