### ISSUE TITLE
Update old CoffeeScript package

### ISSUE THREAD

**Issue by cryptoquick** [gruntjs/grunt#1266]
I'm using a CoffeeScript module that's loaded by Grunt, in a Gruntfile. It's using a very old version of CoffeeScript, version 1.3.3, which has an issue with the following syntax:

```
data =
      site: _.where feed.index, {id}
```

Namely, the comma interferes with destructuring somehow. I don't know in what version of CoffeeScript this was fixed, but CoffeeLint agrees with my code.

It'd be nice if CoffeeScript could be updated at some point.

**Comment by vladikoff** [comment]
https://github.com/gruntjs/grunt/issues/911
