### ISSUE TITLE
unwanted type casting by grunt.option setter

### ISSUE THREAD

**Issue by tobimx** [gruntjs/grunt#1272]
Hi,

~~~bash
grunt release-prepare --release-version=2.0
~~~

I was confused about the exception `Fatal error: Object 2 has no method 'indexOf'`. I've fixed this by casting the option to a string in the grunt task, but it is `"2"` then.

How to prevent unwanted type casting?

**Comment by silkentrance** [comment]
@tobimx

This most likely comes from nopt which includes cleaning of, including validation and type casting, for option values, with the default type mapping being `typeDefault = [false, true, null, String, Array]`.

Have you tried enclosing the release version in single or double quotes, e.g. "2.0"?

Which plugin are you using? I have looked for release-prepare but found no plugin matching your command line.

**Comment by tobimx** [comment]
release-prepare is the name of my task. Sorry for not mentioning it. 
Yes, I've already tried within quotes and came to the same result

**Comment by silkentrance** [comment]
I guess you task was declaring something like so

```
module.exports = function(grunt) {

    grunt.registerTask('release-prepare', '', function(version) {
        grunt.log.writeln(version);
        grunt.log.writeln(typeof version);
    });

};
```

Now, calling this using `grunt release-prepare:2.0` will pass in the 2.0 parameter as the version and the output should be like so

```
> grunt release-prepare:2.0
[...]
Running "release-prepare:2.0" (release-prepare) task
2.0
string
```

**Comment by silkentrance** [comment]
@tobimx see previous comment on the issue

**Comment by shama** [comment]
Please try with `grunt@1.0.0-rc1` as we have updated `nopt` and I believe fixed this issue.
