### ISSUE TITLE
grunt tasks error

### ISSUE THREAD

**Issue by rk08** [gruntjs/grunt#1278]
When I run my grunt taks i am getting this error
can you tell me how to fix it.
attaching the error image

![grunt](https://cloud.githubusercontent.com/assets/1699943/5875923/20abeb3c-a2d8-11e4-8ff1-32e2bb24955b.png)

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/gruntjs
Paste in the link to the question here so others can follow ;)

**Comment by rk08** [comment]
thanks for your reply can you at-least say why it fails.
