### ISSUE TITLE
Support node_modules outside sourcetree

### ISSUE THREAD

**Issue by avdd** [gruntjs/grunt#1279]
How do I configure grunt to use `node_modules` outside my source tree?

I can easily do `npm install --global --prefix /my/prefix` and `export NODE_PATH=/my/prefix/lib/node_modules` but grunt doesn't like it ("unable to find local grunt").

**Comment by sindresorhus** [comment]
Don't. Use `npm link`.

**Comment by avdd** [comment]
How?

I tried `npm link` and it still placed `node_modules` in my project directory.
