### ISSUE TITLE
option.flags() returns mixed values

### ISSUE THREAD

**Issue by askmatey** [gruntjs/grunt#1282]
Let's assume I run a task with options like this:

```sh
grunt hero:batman --weapon=hook,pistol --location=cave --can-jump --another-blabla
```

However, calling `grunt.option.flags()` within the task, creates a useless array:

```sh
console.log(grunt.option.flags);

[
 '--weapon=hook,pistol',
  '--location=cave',
  '--can-jump=--another-blabla'   // <-- ???
]
```

**Expected result:**

```sh
[
 '--weapon=hook,pistol',
  '--location=cave',
  '--can-jump',          // ✓
  '--another-blabla'     // ✓
]
```
Is this a bug or should I always use a value for options?

**Comment by askmatey** [comment]
Can I provide a fix for this ?

**Comment by Coridyn** [comment]
This is a known issue: https://github.com/gruntjs/grunt/issues/908

**Comment by Coridyn** [comment]
@askmatey I've made a module that will fix the Grunt options parsing.

Try it out: https://github.com/widgetworks/nopt-grunt-fix
