### ISSUE TITLE
Allow a function as a src: value

### ISSUE THREAD

**Issue by johnmcase** [gruntjs/grunt#1289]
I want to be able to do something like this:

    task: {
      src: function() {
        // some code that takes a long time to run
        return result;
      },
      options: {...}
    }

The use case is that I need to perform a complicated search for the `src` which takes a long time.  If I do `src: doSearch(...),` then I incur the cost of the search every time any grunt task is executed.  I only want to actually perform the search if I'm running the task.  Essentially I'm looking to lazy-load that `src` value.

I've poked through the grunt code some, and I think this would require a change to `grunt.file.expand` but maybe there is an easier way?

**Comment by mstrutt** [comment]
Hey, I've done something similar when I wanted to dynamically build the src for a task. You could achieve this by registering your own task (`mytask` in this case) which, when run, will get the config for `task`, modify source to the result of `doSearch`, set this back to the config of `task` (just for this run) and then run `task`:

```js
grunt.registerTask('mytask', 'description', function() {
	var task = grunt.config('task');

	task.src = doSearch(...);

	grunt.config('task', task);

	grunt.task.run(['task']);
});
```

**Comment by shama** [comment]
The solution @mstrutt is currently the best option atm. Thanks!
