### ISSUE TITLE
Add the `process` function

### ISSUE THREAD

**Issue by monolithed** [gruntjs/grunt#1290]
Currently there is no standard `process` option like [grunt-contrib-concat#options.process](https://github.com/gruntjs/grunt-contrib-concat).
I propose to add the one!

For example it may be very useful for async tasks without any output info:

![1420849930456](https://cloud.githubusercontent.com/assets/803674/5689596/4d77c5a0-9879-11e4-98f0-7d55826f87e5.png)

```
module.exports = function (grunt) {
	var done = this.async();

	grunt.initConfig({
		6to5: {
			build: {
				files: [{
					expand: true,
					cwd   : 'trunk/',
					dest  : 'cache/trunk/',
					src   : [ '**/*.js' ]
				}]
			},

			process: function (src, path_to_file) {
				grunt.log.write(path_to_file);
				done();

				return src;
			}
		}
	});
};
```

Also it will be convenient for debugging or custom wrappers.

**Comment by shama** [comment]
Closing as I think this would add too much logic into the config when it should belong in a task instead. I'm guessing `process` was added to grunt-contrib-concat for a good reason but this doesn't seem like a good idea for all tasks. It seems like it is effectively rewriting the core of a task... in which case it should just be it's own task. Thanks!
