### ISSUE TITLE
Feature request: grunt event for starting/ending tasks

### ISSUE THREAD

**Issue by Risto-Stevcev** [gruntjs/grunt#1297]
I think it would be useful to create grunt events (e.g. on 'start' and on 'stop') that would listen to when a tasks is started and when a task is stopped. The event could return the error if it fails or the result if it succeeds, as well as the task and it's associated data. 

This feature would be useful for creating tasks that generally work on other grunt tasks on a meta level.

**Comment by shama** [comment]
The best solution atm is to create a task that runs before and after other tasks.

```js
grunt.registerTask('ops', function (which) {
  if (which === 'start') doSomething()
  else if (which === 'stop') somethingElse()
})
grunt.registerTask('default', ['ops:start', 'concat', 'minify', 'ops:stop'])
```
