### ISSUE TITLE
--gruntfile option works only if --verbose option is used

### ISSUE THREAD

**Issue by chachou29** [gruntjs/grunt#1300]
Hello,
```grunt --verbose --gruntfile /home/xx/Gruntfile.js```
Works OK.
But,

```grunt --verbose --gruntfile /home/xx/Gruntfile.js```
Throw error.
```
grunt-cli: The grunt command line interface. (v0.1.13)

Fatal error: Unable to find local grunt.
...
```
node v0.10.32
grunt-cli 0.1.13
grunt 0.4.5
Ubuntu

Thank you,
Philippe

**Comment by chachou29** [comment]
Seems to be a known issue
https://github.com/gruntjs/grunt-cli/issues/45 and https://github.com/gruntjs/grunt/issues/908 
...
annoying !
When 0.5 will be release ?
Thank you 
Philippe

**Comment by shama** [comment]
Closing as a duplicate. Sorry I don't know the expected release date with the fix.
