### ISSUE TITLE
Grunt needs a maintainer!

### ISSUE THREAD

**Issue by phietrt** [gruntjs/grunt#1302]
Issues seem to be stacking up and we've been waiting for releases quite long. It's just a suggestion but isn't it time to clean up guys? Gulp has ~10 open issues! :-1: 

@cowboy

**Comment by cowboy** [comment]
You could have just posted the issue as @XhmikosR, you know.

**Comment by phietrt** [comment]
> You could have just posted the issue as @XhmikosR, you know.

@cowboy @XhmikosR thank you for the quick response, but was this comment indented for another issue or what? Apologies if I'm missing a thing. I'm not sure I'm understanding you right.

**Comment by XhmikosR** [comment]
I don't follow, how is this related to me?

**Comment by phietrt2** [comment]
I still don't really follow, @cowboy? @XhmikosR
