### ISSUE TITLE
Don't run task if Gruntfile was run with errors

### ISSUE THREAD

**Issue by segrey** [gruntjs/grunt#1303]
If requiring Gruntfile throws an error, don't run tasks loaded from additional directory paths (`--tasks`).
If it isn't a good idea, could you please advise how a task could use grunt API to figure out whether Gruntfile was required successfully?

Based on https://youtrack.jetbrains.com/issue/WEB-11338:
Even if Gruntfile is incorrect, WebStorm Grunt integration prints:
```
...
Running "_intellij_grunt_tasks_fetcher" task
{"aliasTasks":[],"coreTasks":[]}

Done, without errors. 
```

**Comment by shama** [comment]
Closing as this doesn't seem like an issue with Grunt but a configuration issue with WebStorm. Please let us know if it is in fact an issue with Grunt. Thanks!

**Comment by segrey** [comment]
Yes, you're correct, this issue is not about Grunt itself. I'd say it's about smooth interoperability between Grunt and tools (e.g. IDE). Usually, tools need to list available task, like `grunt --help` does in its `Available tasks` section. AFAIK, currently `grunt` doesn't support producing machine readable output containing all found tasks. So, WebStorm applies the following workaround: it registers and runs its own task that uses grunt private API to dump all tasks in json format:
```
grunt --gruntfile /path/to/users/Gruntfile.js --tasks /path/to/ide/tasks _intellij_grunt_tasks_fetcher
```
Source code of `_intellij_grunt_tasks_fetcher` is bundled with WebStorm. Also, I've created a gist [grunt-tasks-fetcher.js](https://gist.github.com/segrey/6f94e188dab4605c5c10) for easier access.

Ideally, grunt could support out-of-the-box dumping tasks description in json format (via some cli option, e.g. gulp v4 has `--tasks-json`). That would allow tools to drop maintaining grunt private API usages.

As a small step forward better interop, what do you think about this issue?
I can be wrong, but skipping running grunt task if Gruntfile has errors seems like a reasonable thing to me. Does it break grunt design or some workflow?
Otherwise, unfortunately, I don't see a good way to fix https://youtrack.jetbrains.com/issue/WEB-11338: the console error output will always end with confusing "Done, without errors." message. Thanks!

**Comment by shama** [comment]
So the feature request here is to provide an API to output the tasks in a JSON format?

**Comment by segrey** [comment]
Providing an API is a possible way to improve interop. Other ways are:
* skipping running grunt task if Gruntfile has errors (this issue)
* introducing a new cli flag that will dump the tasks in a JSON format

IMO, the proper way is introducing a new cli flag. In this case tools don't have to maintain similar small wrapper that dumps JSON. I understand it might be taken as overkill, so I'd be happy if grunt tasks just aren't run in case of errors. :) Thanks.

**Comment by shama** [comment]
> skipping running grunt task if Gruntfile has errors (this issue)

I'm not sure what this means. Are you talking javascript syntax errors? Each task handles it's own errors and then Grunt by default will stop running tasks unless `--force` was provided.

**Comment by segrey** [comment]
Yes, about javascript syntax errors. To be more specific when grunt console runner rejects to run specified task. IIUC, it happens when gruntfile cannot be loaded https://github.com/gruntjs/grunt/blob/2ddec56192ba6599cd3aeb0dc812f54cfe83c07b/lib/grunt/task.js#L343.
