### ISSUE TITLE
Identifying the file when template error arises

### ISSUE THREAD

**Issue by oravecz** [gruntjs/grunt#1304]
I have seem the prior posts when users complain about:

```
Running "copy:dist" (copy) task
>> A special character was detected in this template. Inside template tags, the
>> \n and \r special characters must be escaped as \\n and \\r. (grunt 0.4.0+)
Warning: An error occurred while processing a template (Unexpected token ILLEGAL). Use --force to continue.
```

However, they all new what file was causing their problem. I have no clue. :(

Running it with debug turned on results in no additional information. Is it possible to get more context regarding this failure, such as filename, line number, etc.?

**Comment by keoghpe** [comment]
Hey oravecz, 

If you run whatever task is causing the problem with ```--stack``` you should get a stack trace. In my project I have the same error in my Gruntfile.js on line 390 and the stack trace looks like the following:

```
at Function.template (/Users/keoghpe/Documents/Sites/myproject/node_modules/grunt/node_modules/lodash/lodash.js:3872:16)
at Object.template.process (/Users/keoghpe/Documents/Sites/myproject/node_modules/grunt/lib/grunt/template.js:75:27)
at Object.<anonymous> (/Users/keoghpe/Documents/Sites/myproject/Gruntfile.js:390:38)
```

Does this help?

**Comment by oravecz** [comment]
My problem turned out to be the pattern <% shows up in an image file. I was
processing templates in a copy block, and it failed on this image file. I
was able to work around my problem by separating the copying of image files
from my copying of source files, but I couldn't get grunt's process
template command to spit out the name of the image file with which it had
the problem.

**Comment by shama** [comment]
We'd review a PR that could better explain the error. Although the errors come from lodash processing the templates so there is likely not much we could fix from our perspective.
