### ISSUE TITLE
go into a folder once my yeoman script is finished

### ISSUE THREAD

**Issue by rk08** [gruntjs/grunt#1305]
do you know how to cd into a direcory after a buidl?
so I want to at the end of my build cd into the folder generated
before the end function
my folder will be applicationName
I want to go into a folder once my yeoman script is finished
so a function that will go into the folder
i want to automate that... because the directory has been created and now I want to go into that directory automatically
I am looking to switch into the folder once the project is buiklt..
the project will build a folder.. i.e. testproject1 and it puts all types of files in there... what I want to do is at the very end I want to enter into testproject1 and then do the end function.

**Comment by vladikoff** [comment]
Questions like that are better for http://stackoverflow.com/questions/ask

**Comment by rk08** [comment]
@vladikoff i asked in stackoverflow they dont know....can you help me...shall i drop u a mail
