### ISSUE TITLE
Not able to copy FontAwesome font files

### ISSUE THREAD

**Issue by perqa** [gruntjs/grunt#1306]
Running "copy:dist" (copy) task
Warning: Unable to read "fonts/FontAwesome.otf" file (Error code: ENOENT). Use --force to continue.

Aborted due to warnings.

*Permissions:*
ls -l bower_components/font-awesome/fonts/
-rw-r--r--  1 perqa  staff   93888 22 Jan 19:09 FontAwesome.otf

**Comment by vladikoff** [comment]
For support see http://stackoverflow.com/questions/tagged/gruntjs
Or submit a valid bug report for the plugin that is causing this issue.
