### ISSUE TITLE
material-design-icons make my my grunt watch task freeze

### ISSUE THREAD

**Issue by casertap** [gruntjs/grunt#1310]
the grunt serve command freeze
````
Running "concurrent:ionic" (concurrent) task
Running "ionic:serve" (ionic) task
Running "watch" task
Waiting...
````

I'm on mac osx.
I saw articles saying:
On most systems the maximum number of watches that can be created per user is limited to 8192. watchdog needs one per directory to monitor. To change this limit, edit /etc/sysctl.conf and add:
fs.inotify.max_user_watches=16384

but it does not help.
I have a basic setting (I keep the bower_components folder outside of app but I copy it inside of www during the dist task:
/app
------/images
------/styles
------/index.html
/bower_components
....
/www
-------/bower_components
-------/images
-------/styles
-------/index.html

my watch part look like this
````
watch: {
      bower: {
        files: ['bower.json'],
        tasks: ['wiredep', 'newer:copy:app']
      },
      html: {
        files: ['<%= yeoman.app %>/**/*.html'],
        tasks: ['newer:copy:app']
      },
      js: {
        files: ['<%= yeoman.app %>/<%= yeoman.scripts %>/**/*.js'],
        tasks: ['newer:copy:app', 'newer:jshint:all']
      },
      compass: {
        files: ['<%= yeoman.app %>/<%= yeoman.styles %>/**/*.{scss,sass}'],
        tasks: ['compass:server', 'autoprefixer', 'newer:copy:tmp']
      },
      gruntfile: {
        files: ['Gruntfile.js'],
        tasks: ['ngconstant:development', 'newer:copy:app']
      }
    },
````

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/gruntjs
Paste in the link to the question here so others can follow ;)

**Comment by casertap** [comment]
Ok thanks, here it is:
http://stackoverflow.com/questions/29315495/the-grunt-serve-command-freeze-after-i-added-material-design-icons
