### ISSUE TITLE
typeerror: undefined is not a function

### ISSUE THREAD

**Issue by biebergagabcbs** [gruntjs/grunt#1311]
I am trying to run grunt and it is giving the following error messages.

Loading "gruntfile.coffee" tasks
TypeError: undefined is not a function
Task: default is not found

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/gruntjs
Paste in the link to the question here so others can follow ;)
