### ISSUE TITLE
Grunt serve doesn't work anymore

### ISSUE THREAD

**Issue by lemia** [gruntjs/grunt#1315]
Hi,

We use grunt in our projects, and since a few days we can't execute the 'grunt serve' command anymore.

In fact we have this error, and we don't know why it happens : 

${projectPath}/yo $ grunt serve
Loading "connect_proxy.js" tasks...ERROR
>> TypeError: Cannot read property 'prototype' of undefined

Running "serve" task
Warning: Task "configureProxies" not found. Use --force to continue.

Aborted due to warnings.

Do you have more information to debug or to fix it??

Thank you

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/gruntjs
Paste in the link to the question here so others can follow ;)

**Comment by lemia** [comment]
Thanks ;)

**Comment by shobhitg** [comment]
I was facing similar issue.
The error was due to https://github.com/drewzboto/grunt-connect-proxy/issues/98
We fixed our issue by bumping up the middle number in the version string. i.e. moving from 0.1.x to 0.2.x.

**Comment by lemia** [comment]
Thanks ... 

A colleague also found a solution ... Just upgrade the grunt-connect-proxy in the package.json from "^0.1.11" to "^0.2.0" ... 

But I don't understand why it worked with the old version till now ...
