### ISSUE TITLE
Running Grunt from PHP

### ISSUE THREAD

**Issue by iamdriz** [gruntjs/grunt#1316]
I'm trying to make it so that people who don't know how to use NodeJS can execute grunt tasks from a GUI on a website that uses PHP to call grunt.

The basic PHP is:

~~~
exec('cd ' . __DIR__);
exec('grunt');
~~~

However I get an error: `'grunt' is not recognized as an internal or external command, operable program or batch file.`

You'd usually get this error because grunt is not installed globally... but in this case it shouldn't matter because I have cd into the folder when grunt is installed (not that the cd should even be required because I have run the PHP script in the same directory).

Any ideas?

**Comment by vladikoff** [comment]
Questions like this are better asked on stackoverflow http://stackoverflow.com/questions/tagged/gruntjs

**Comment by iamdriz** [comment]
I did. No one knows.

**Comment by vladikoff** [comment]
@iamdriz please link your stackoverflow question in this issue

**Comment by iamdriz** [comment]
http://stackoverflow.com/questions/29844152/run-nodejs-commands-from-php

The question initially talks about getting node to run from php but after changing the user that runs php I have no only the grunt issue as explained above.

**Comment by iamdriz** [comment]
http://stackoverflow.com/questions/29892890/run-grunt-commands-from-php-on-windows
