### ISSUE TITLE
Using spaces before and after shell in grunt.task.run([ 'shell' ]) gives inconsistent results

### ISSUE THREAD

**Issue by elviocb** [gruntjs/grunt#1317]
Gruntfile.js

<pre>
grunt.initConfig({ ..

    shell: {
      prodServer: {
        command: 'git push azure master'
      }

..});
</pre>

**Scenario 1:**
<pre>grunt.task.run([<code> <space> </code>"shell"<code> <space> </code>])</pre>
or
<pre>grunt.task.run(["<code> <space> </code>shell<code> <space> </code>"])</pre>
Invoke shell's children property command without passing the property name

**Scenario 2:** 
<pre>grunt.task.run(["shell"])</pre>
This scenario will return a warning and will fail:
> Command is required. Aborted due to warnings

**Comment by cowboy** [comment]
In JavaScript (the language a Gruntfile is written in), whitespace inside of strings is significant, eg. `"shell"` and `"  shell  "` are two completely separate values. Whitespace outside of strings, however, is generally insignificant, eg. `["a"]` and `[  "a"  ]` are equivalent, so are `["foo","bar"]` and `[  "foo"  ,  "bar"  ]`.

Basically, it doesn't matter what how many spaces you use outside of your strings, just don't put them inside the strings when you're specifying task names (`"  shell  "` is bad, `"shell"` is good) and Grunt should work fine.
