### ISSUE TITLE
js-bson: Failed to load c++ bson extension, using pure JS version 

### ISSUE THREAD

**Issue by chelsh** [gruntjs/grunt#1319]
----node version:v0.12.0

root@iZ2kwhZ:/var/www/Server-API/source# grunt
[Error: Module did not self-register.]
js-bson: Failed to load c++ bson extension, using pure JS version
Loading "Gruntfile.js" tasks...ERROR
>> Error: Module did not self-register.
Warning: Task "default" not found. Use --force to continue.

Aborted due to warnings.
root@iZ2kwhZ:/var/www/Server-API/source# grunt --help
[Error: Module did not self-register.]
js-bson: Failed to load c++ bson extension, using pure JS version
Loading "Gruntfile.js" tasks...ERROR
>> Error: Module did not self-register.
Grunt: The JavaScript Task Runner (v0.4.5)

Usage
 grunt [options] [task [task ...]]

Options
    --help, -h  Display this help text.                                        
        --base  Specify an alternate base path. By default, all file paths are 
                relative to the Gruntfile. (grunt.file.setBase) *              
    --no-color  Disable colored output.                                        
   --gruntfile  Specify an alternate Gruntfile. By default, grunt looks in the 
                current or parent directories for the nearest Gruntfile.js or  
                Gruntfile.coffee file.                                         
   --debug, -d  Enable debugging mode for tasks that support it.               
       --stack  Print a stack trace when exiting with a warning or fatal error.
   --force, -f  A way to force your way past warnings. Want a suggestion? Don't
                use this option, fix your code.                                
       --tasks  Additional directory paths to scan for task and "extra" files. 
                (grunt.loadTasks) *

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/gruntjs
Paste in the link to the question here so others can follow ;)
