### ISSUE TITLE
Using glob inside grunt task

### ISSUE THREAD

**Issue by TheHalcyonSavant** [gruntjs/grunt#1322]
For some reason the glob callback isn't executed inside grunt task.
```js
var glob = require('glob');

module.exports = function(grunt) {

grunt.registerTask('out-files', 'Output globbing trace', function () {
  glob('app/**/*.js', function (er, files) {
    console.log(er, 'ok');
    console.log(files);
  });
});

};
```
The callback function doesn't produce any log output on `grunt out-files`. Probably I'm doing something wrong here, or maybe the glob function is stubbed by grunt internally.

Also, I need to output ONLY all globbed files used internally by grunt (not with --verbose). Is there any easier workaround to this problem?

**Comment by sindresorhus** [comment]
`glob` is async, you need to let grunt know. https://www.google.com/search?q=grunt+async

StackOverflow is generally better for support questions.

**Comment by TheHalcyonSavant** [comment]
Thank you @sindresorhus, I've completely forgot about this.async()
