### ISSUE TITLE
Have the option to return a default from file.readJSON

### ISSUE THREAD

**Issue by JaKXz** [gruntjs/grunt#1324]
It would be great to be able to specify a default object to be returned by `file.read` if it fails to parse or find the file specified.

Attempting a PR now.

**Comment by JaKXz** [comment]
For now, I'm just using `if grunt.file.exists('my-file.json')...` as a workaround, but it would be nice to be able to inline it like: 

```javascript
grunt.file.readJSON('my-optional-file.json', { fallback: {} });
```

**Comment by shama** [comment]
Thanks for the idea. We are moving some of the APIs to be better handled by 3rd-party libs and I think this is a good use case.

Instead you can do: `npm i xtend` and then:

```js
var xtend = require('xtend')
var opts = xtend({ fallback: {} }, require('my-optional-file.json'))
```
