### ISSUE TITLE
grunt for multiple projects

### ISSUE THREAD

**Issue by zenwork** [gruntjs/grunt#1327]
I manage a framework and a set of components that depend on this framework. I have a grunt-based solution to handle all of them identically. It is pretty good but still not as good as I would like it to be. There are 10 packages in the framework and 10(and growing) components that depend on the framework. My challenge is to use grunt in the same way with all these packages. 

My requirements are:
* Can not rely on npm global installs as our build machine is a shared environment. In truth there are a couple of globals like grunt but I do not wan to add any. In the long-run I want to remove them. 
* Need to keep any jenkins overhead simple
* Need development-time commands to be identical to build-time commands... unless developer explicitly wants to change something. For example run unit tests in watch mode instead of doing a single run at build time.

What I have up to now:
* I have created a package that contains our common grunt configuration, custom tasks, our default task configs, a mechanism for overriding the grunt config with package-specific configs, and build-time utility code.
* All our packages have a devDependency on this package
* I use load-grunt-config to help with all of this

Package layout:
```
package-foo
     - package.json
     - Gruntfile.json
     - node_modules
         - shared-grunt-package
             - package.json
             - main.js
             - src
                 - shared-task-configs
                 - custom-tasks
                 - util
         - <all my grunt dependencies>
```
My Gruntfile.js looks something like 
```
module.exports = function (grunt) {
    var pkg = require('./package.json');
    var config = require("shared-grunt-package").buildConfig(grunt, pkg);
    require('load-grunt-config')(grunt, config);
};
```

What I would like to improve improvement:
* I would like all my build-time dependencies to be self-contained in my shared-grunt-package. The current approach still requires that all the grunt-* extensions be added as a top level dependency.
* I am sometimes forced to ask that people add dependencies even when they don't actively use them or know why they need to be there. 

Is there a way to do this? Am I barking up the wrong tree? Is there a better way to accomplish this.

**Comment by shama** [comment]
Closing as this doesn't appear to be an issue with Grunt. But good luck structuring your framework!
