### ISSUE TITLE
http redirect to https

### ISSUE THREAD

**Issue by ekarudianto** [gruntjs/grunt#1328]
Hi, I've been using Gruntjs and Angularjs for my project right now. And actually I've been facing this issue for a while now.. since I'm a newbie for this gruntjs thingies, I would like to ask

is there a way to make, for example if user type this

`http://www.example.com`

the gruntjs would redirect the page to here

`https://www.example.com`

could you help me ?

**Comment by sindresorhus** [comment]
https://github.com/gruntjs/grunt-contrib-connect/issues/177

**Comment by shama** [comment]
I believe those use `grunt-contrib-connect` which uses `connect` under the hood. You'll need to add middleware (or use an existing one):

Such as:
```js
function needshttps (req, res, next) {
  if (!req.secure) {
    return res.redirect('https://' + req.get('host') + req.url);
  }
  next();
}
```
