### ISSUE TITLE
Support Flow

### ISSUE THREAD

**Issue by ShashankaNataraj** [gruntjs/grunt#1333]
Don't know if this is the right place to raise this, but here goes:

Do we have a grunt-contrib-flow plugin for facebook flow? https://github.com/facebook/flow

Should we make one? I'd be willing to help out!

**Comment by arthurvr** [comment]
There is already grunt-flow: https://github.com/larsonjj/grunt-flow :)

**Comment by ShashankaNataraj** [comment]
@arthurvr  thanks, will close this issue :)
