### ISSUE TITLE
Spotify confirmed for using Grunt

### ISSUE THREAD

**Issue by aaronharding** [gruntjs/grunt#1335]
Hey,

I'm not sure if you guys are aware of this, the Mac build for the native Spotify app is using Grunt:

![confirmedlols](http://i.imgur.com/uEaJMIY.png)
![subl](http://i.imgur.com/prCdVRw.png)

These two screenshots are what is found after unpacking the Spotify app.

Congratulations, I guess!

**Comment by FagnerMartinsBrack** [comment]
According to Spotify engineers in Quora the app is entirely built in JS, so I would expect that they would be using Grunt considering it's the most popular node built tool out there.

**Comment by aaronharding** [comment]
Well, there's always npm scripts and *gasp* gulp :p

Either way, I'm just making the community aware.

**Comment by tkellen** [comment]
No need to *gasp* about Gulp. Gulp and Grunt and npm tasks are all great tools!

**Comment by aaronharding** [comment]
Oh I'm not gasping in *that* way, it's just that it's ~the other task
runner~. A bit of tongue-in-cheek.

Still, congratulations to the Grunt team for improving the standards of the
industry (as this thread was supposed to be a praise).

On 20 May 2015 at 16:58, Tyler Kellen <notifications@github.com> wrote:

> No need to *gasp* about Gulp. Gulp and Grunt and npm tasks are all great
> tools!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gruntjs/grunt/issues/1335#issuecomment-103918374>.
>



-- 
aaron

**Comment by shama** [comment]
Thanks for letting us know!
