### ISSUE TITLE
Grunt roadmap and what is next for the major version of Grunt?

### ISSUE THREAD

**Issue by xtianus79** [gruntjs/grunt#1336]
It is no secret that gulp is a viable option for work processes similar to grunt.  What is on the horizon and in store for the future of grunt?

**Comment by xtianus79** [comment]
well I guess closing it is an option but can you at least elaborate?  I love using Grunt and would like to know it will continue to see support.

**Comment by vladikoff** [comment]
Sorry this is not a valid issue or a bug report, that is why I closed this. You can track code progress on https://github.com/gruntjs  such as https://github.com/gruntjs/grunt-legacy-cli/issues/1 

Any news will be published on http://gruntjs.com/blog

**Comment by xtianus79** [comment]
thanks... I understand.  However, none of those places has a real idea of whats.next  Perhaps you guys should blog something as that would be a welcome read!

**Comment by cowboy** [comment]
We're working on it :wink:

**Comment by xtianus79** [comment]
@cowboy @vladikoff 

awesome sauce!!!  I think Grunt is great and I want to teach some courses on it.  so I don't want people trying to tell me grunt is not for the future.
