### ISSUE TITLE
Grunt build folder structure

### ISSUE THREAD

**Issue by Saneesh** [gruntjs/grunt#1337]
Hello,
Anyone can help me to make this folder structure for the build?

all/modules/module1/module1.module
all/modules/module1/module1.info
all/modules/module1/style.css
all/modules/module1/script.js
all/modules/module1/plugin/address.inc
Note: Just copy the files as it is.

all/themes/mytheme/css/main.css
all/themes/mytheme/css/mymain.css
all/themes/mytheme/css/bootstrap.css
all/themes/mytheme/css/font/fontello.eot
Note: mearge main.css and mymain.css to 2ed6bccd.main.css
      Rest of the folder/file as it is.

all/themes/mytheme/js/script.js
all/themes/mytheme/js/myscript.js
all/themes/mytheme/js/bootstrap.js
Note: mearge script.js and myscript.js to 12hfssfsd.script.js
      Rest of the folder/file as it is.

all/themes/mytheme/images
all/themes/mytheme/templates
Note: Just copy the folder structure

all/themes/mytheme/page.tpl.php
all/themes/mytheme/page--about.tpl.php
Note: Replace 'main.css' with '2ed6bccd.main.css'
      Replace 'script.js' with '12hfssfsd.script.js' in the page.tpl.php (like in index.html)

A detailed question is asked at http://stackoverflow.com/questions/30389559/grunt-build-folder-structure-for-drupal

Thanks in advance!

**Comment by jonschlinkert** [comment]
thanks for posting on stackoverflow and adding the link! going to close since this isn't an actual issue, here, but that won't prevent anyone from finding it to help you out!
