### ISSUE TITLE
Support gruntfile.babel.js

### ISSUE THREAD

**Issue by michaelBenin** [gruntjs/grunt#1346]
See: https://github.com/gulpjs/gulp/issues/830

**Comment by silkentrance** [comment]
Since node´s require() function does not support multiple extensions due to "shortcomings" in the path module, I´d rather that one would stick to the well known extensions for babel, namely ".es" or ".es6".

**Comment by fassetar** [comment]
This issue was moved to fassetar/grunt#1

**Comment by shama** [comment]
Going forward, we'll move towards [liftoff](https://github.com/js-cli/js-liftoff) which will enable support for additional languages and keeping dependencies more up to date. Look for an https://github.com/gruntjs/rfcs related to it soon (or open one if you would like to take on this endeavor sooner). Thanks!

**Comment by shama** [comment]
RFC for this started: https://github.com/gruntjs/rfcs/pull/2
