### ISSUE TITLE
working with the nodejs Benchmarking WG

### ISSUE THREAD

**Issue by trevnorris** [gruntjs/grunt#1350]
An official Benchmarking WG has been created for the nodejs foundation (information on https://github.com/nodejs/benchmarking). We are investigating ways to more thoroughly detect performance regression over different versions. Part of this has been discussion around using larger scale benchmarks, instead of relying so heavily on the micro benchmarks commonly used.

Is there an example ultra-grunt file that does everything and the kitchen sink? Would be a great way to track the full breath of performance functionality supported by grunt.

**Comment by sindresorhus** [comment]
Are you looking for a gruntfile only using grunt specific functionality or with plugins doing all kinds of things, like Sass, Uglify, image minifications, etc?

**Comment by trevnorris** [comment]
Plugins would be great. We can always scale back if needed, but right now it's about collecting as much data as possible.

**Comment by sindresorhus** [comment]
The output of [generator-webapp](https://github.com/yeoman/generator-webapp/) is pretty comprehensive.

Made a static repo for you here: https://github.com/sindresorhus/generator-webapp-output

**Comment by trevnorris** [comment]
@sindresorhus Awesome. That'll definitely be interesting to benchmark.
