### ISSUE TITLE
file.mkdir is not thread safe

### ISSUE THREAD

**Issue by Graham42** [gruntjs/grunt#1351]
`file.mkdir` is supposed to be "Like mkdir -p" but is not thread safe. The code checks if the directory exists and then creates it if needed. The problem is another thread can make that directory in between. I observed this when running multiple grunt processes.

Problematic code:
https://github.com/gruntjs/grunt/blob/master/lib/grunt/file.js#L198-L204

[node-mkdirp](https://github.com/substack/node-mkdirp) does a better job of this which we should emulate.

**Comment by slicedpan** [comment]
This is the same issue as #1242. There is a PR attached to that issue which appears to perform a similar check as the code in node-mkdirp. (i.e. if directory creation fails, check to see if the directory exists)

**Comment by fassetar** [comment]
This issue was moved to fassetar/grunt#2
