### ISSUE TITLE
Grunt file isPathAbsolute do not respect path.isAbsolute node 0.12 implementation

### ISSUE THREAD

**Issue by hikkyu** [gruntjs/grunt#1353]
Hello!

In node 0.12.x if you run: `require('path').isAbsolute('/')` it return true.

`grunt.file.isPathAbsolute('/')` return false.

Is there a way to fix this or I need to patch my condition ?

Thank's

**Comment by sindresorhus** [comment]
If you still want to support Node 0.10 you can use a polyfill like https://github.com/sindresorhus/path-is-absolute. If not, just use `require('path').isAbsolute('/')` directly.
