### ISSUE TITLE
only one file uglified or copied in windows?

### ISSUE THREAD

**Issue by ashareye** [gruntjs/grunt#1358]
i setup grunt in winxp and write a gruntfile.js which works fine in osx, but in winxp only one file was copied or uglified ? why ?

gruntfile.js like
uglify: {
            libMin: {
                files: [
                    {dest:'<%= destlib %>',cwd:'<%= srctemp %>minlib/', src:'*.js', expand: true}
                ]
            }
.......
when i run 'grunt uglify:libMin' first file copied but others not

**Comment by shama** [comment]
My guess is it's a filename case sensitivity issue. Win XP is a really old OS though. Grunt, along with many other things, no longer support it.
