### ISSUE TITLE
is 'npm install grunt' necessary for every project?

### ISSUE THREAD

**Issue by davidmaxwaterman** [gruntjs/grunt#1359]
I wrote a Gruntfile that performs 'npm install' and 'bower install' inside a 'build' task. It works fine with a clean project - so I don't need to do 'npm install grunt'. In fact, I don't really need 'grunt' in my package.json file.

Unfortunately, a colleague seems to have to do npm install grunt from a clear project before he can even do 'grunt build', which kind of defeats the object of the 'build' task running 'npm install'.

The thing is, I'm not sure what the difference is between his environment and mine.

I seem to be able to get to my set up simply by :

```
npm install -g grunt-cli
cd; npm install grunt; cd -
```

After that, `grunt build` works just fine from a clean project. That doesn't seem to work for my colleague though, and I don't know why.

Can anyone tell me which part of my config is enabling this way of running grunt, so I can tell my colleague how to duplicate it?

Thanks.

**Comment by vladikoff** [comment]
Each project should have its own of grunt and grunt-cli to make sure it never conflicts with global modules that are different version.

**Comment by davidmaxwaterman** [comment]
You seem to be implying there is no reason to have grunt installed globally (ie with -g)...that is a very common step to see in instructions...Also, I'm pretty sure this isn't a 'version' issue, so much as a path/installation issue.
Anyway, this was too long ago now and the relevant project has moved on; so I'll let it go.
