### ISSUE TITLE
Grunt Truck Factor

### ISSUE THREAD

**Issue by gavelino** [gruntjs/grunt#1360]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Grunt** and obtained a value of **1**.

The developer responsible for this TF is:

Ben Alman - author of 96% of the files 

To validate our results, we would like to ask **Grunt** developers the following three brief questions:

(a) Do you agree that the listed developer is the main developer of **Grunt**?

(b) Do you agree that **Grunt** will be in trouble if the listed developer leave the project (e.g., if he wins in the lottery, to be less morbid)?

(c) Does **Grunt** have some characteristics that would attenuate the loss of the listed developer (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by tkellen** [comment]
a) Yes.
b) Initially, yes. However, given the size of the Grunt community, I believe a new maintainer could be found.
c) Unfortunately, no. The biggest failing of the Grunt codebase is the lack of a comprehensive test suite.

**Comment by gavelino** [comment]
Thank you.

**Comment by tkellen** [comment]
Thank you for asking @gavelino! Would love to see the results of your research.

**Comment by jonschlinkert** [comment]
> As you probably know, the Truck (or Bus) Factor designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated

@gavelino I'm also curious to see the results of the research! I'd also be curious to see the actual algorithm or variable used to calculate the bus factor. (I glanced at the information on the link you provided, but I'm guessing this info is behind a firewall). 

Does the bus factor take into consideration the asymptotic distribution of "evangelists" or "vested users" versus casual users, or even the potential for clusters of "super users" who care enough about a project to figure it out no matter what happens? Just curious, my hunch is that some popular projects have a way of continuing in some form regardless of what happens to the original maintainers/creators.
