### ISSUE TITLE
task.normalizeMultiTaskFiles fails for grunt-contrib-watch files arrays

### ISSUE THREAD

**Issue by andyexeter** [gruntjs/grunt#1362]
Given an object with a files array built the same way as on the grunt-contrib-watch docs the `normalizeMultiTaskFiles` task method fails.

`grunt.task.normalizeMultiTaskFiles({files: [ 'src/assets/less/*.less' ]});`

Throws this error:

`Uncaught TypeError: Cannot use 'in' operator to search for 'src' in src/assets/less/*.less /home/andy/projects/electron-app/node_modules/grunt/lib/grunt/task.js:112`

Changing the key to `src` resolves the issue but I can't guarantee every object I pass in will be that way. I assume most people's `watch` targets will be set up the same way if they followed the docs.

Edit: I'm using Grunt v0.4.5 on Ubuntu 14.04 if that helps.

**Comment by thiakil** [comment]
It would need to follow conventions specified in http://gruntjs.com/configuring-tasks#files

Seems to me that you should be passing the 'files' object, not an object with a 'files' element.

**Comment by shama** [comment]
Also `grunt-contrib-watch` is not a multitask but rather a custom task with it's own config format. Multitasks are fed each `src/dest` block individually. Where the watch task needs to watch all the targets upon running so it's not a multitask and config'd differently on purpose.
