### ISSUE TITLE
Grunt stops executing after one task with no error message

### ISSUE THREAD

**Issue by MisterSpicy** [gruntjs/grunt#1364]
Posted it here also : http://stackoverflow.com/questions/32081961/grunt-stops-after-running-one-task-with-protractor-webdriver-manager

Basically, I have a fairly standard grunt-protractor-webdriver setup, and in order to help my teammates get up and running quickly with the framework, I tried to create a task that does the webdriver-manager update and start together.  The update is idempotent, so it should be fine to run every time.

However, after the update, no other tasks are executed and I am dumped back to shell.  It seems to have just given up without warning or error.

**Comment by shama** [comment]
Closing as I don't believe this is an issue with Grunt.

I'm not familiar with grunt-protractor-webdriver but it sounds like a task isn't finishing: `var done = this.async()` and the task never calls `done()`. That is usually the reason the process will exit prematurely, it has nothing left to do and the task doesn't tell Grunt to continue running.

You may want to ask for help on that plugin's issue tracker: https://github.com/seckardt/grunt-protractor-webdriver
