### ISSUE TITLE
Alternate "built with Grunt" badges

### ISSUE THREAD

**Issue by andersevenrud** [gruntjs/grunt#1365]
Could you make an alternate badge without borders and white text shadow ?

It looks a lot better imo and fits a lot better when having multiple badges.

![screenshot](http://i.imgur.com/XLKc0UN.png)

**Comment by sapila** [comment]
Hello there,
So is this issue still an issue , beacause i checked the OS.js repo and you dont use the badge any more.

**Comment by vladikoff** [comment]
Probably because it was ugly :( . We should just make the badge without the logo icon, a good version of https://github.com/gruntjs/gruntjs.com/issues/111#issuecomment-46463051

**Comment by andersevenrud** [comment]
@vladikoff Indeed!

@sapila I still think there should be an alternative that matches the styles of [most other badges](https://github.com/badges/shields). The Grunt one does not look as crisp/clean as the others in my opinion.

And, yes. I don-t use that badge anymore on that project. I swapped out all the others as well for custom ones from a webservice (very recently).

**Comment by sapila** [comment]
Well i dont know how this works ,my first time reaching out trying to help on an open source project ,  should i jump on it and try to create some examples by the badges standards??

**Comment by vladikoff** [comment]
@sapila Hey, are you able tweak the svg files? 

So there is a good version here: https://github.com/gruntjs/gruntjs.com/issues/111#issuecomment-44193755

But we should get rid of the logo from it to minimize the size and ship that. (make it look like badges on http://shields.io/)

Pull request the updated version to https://github.com/gruntjs/gruntjs.com/tree/master/misc and we can go from there!

cc @shama

**Comment by andersevenrud** [comment]
@sapila It'd probably have to be approved, but sure, you can probably take a stab at it and make a pull-request or something.

SVG is probably prefered since it is nicely scalable. Still though -- the same "template" is used.

**Comment by sapila** [comment]
Ok i ll give it a go :)

**Comment by andersevenrud** [comment]
:+1:

**Comment by andersevenrud** [comment]
@vladikoff I was bored, so I gave it a go. How do you feel about this one ?

[Badge PNG export example](https://www.dropbox.com/s/0hptdw8n8jfzc3k/grunt-badge-112x20.png?dl=0)

SVG: https://www.dropbox.com/s/fy1vljhtetkiuub/grunt-badge.svg?dl=0

**Comment by vladikoff** [comment]
looks cool! What are your thoughts @sapila  ?

**Comment by sapila** [comment]
Hey that looks great and very clean !! I just tried to edit the one used and to remove the logo.
![path212](https://cloud.githubusercontent.com/assets/6667204/11449123/32e11afa-9573-11e5-9ad9-cbd03e830c37.png)

Also , beacause i like the logo, i tried to make a badge with the logo but with some colors removed from the logo so that the it would be a bit cleaner but in small size it doesnt look so good, also the size is a lot smaller with no logo.

@andersevenrud nice work, looks nice and clean :+1:

**Comment by vladikoff** [comment]
@JKAussieSkater for the website

**Comment by vladikoff** [comment]
should move this to website issues

**Comment by andersevenrud** [comment]
Moved to: https://github.com/gruntjs/gruntjs.com/issues/165
