### ISSUE TITLE
Disable glob-expansion

### ISSUE THREAD

**Issue by cspotcode** [gruntjs/grunt#1367]
Is there a way to specify files for a multi-task that don't get glob-expanded?

For example, if I'm configuring a task using some machine-generated, hard-coded list of files, I don't want glob patterns to get expanded.  There's no way to turn off grunt's glob-expansion.

**Comment by shama** [comment]
You can use `this.data` from within a task to read the config raw or even `grunt.config.getRaw(this.name)`.

Although if you're not utilizing Grunt's API then it shouldn't be a multi-task. Just use `grunt.registerTask()` and read the config with `grunt.config.requires(this.name); var data = grunt.config.get(this.name);`.

**Comment by cspotcode** [comment]
My use-case is programmatically configuring an existing multi task.  For example:

```
grunt.config.set('copy.frontend.files`, someComputedListOfFiles());
```

In this situation, `someComputedListOfFiles()` returns an array of file paths.  I don't want grunt to do any glob-expansion on those paths.

**Comment by shama** [comment]
Sorry I don't believe that is supported. It is up to the task to determine how it reads files. A user only has control over the task supplied options or how Grunt expands file patterns using: http://gruntjs.com/configuring-tasks#files, https://github.com/isaacs/node-glob and https://github.com/isaacs/minimatch

**Comment by cspotcode** [comment]
Will the grunt team accept a patch that adds this capability?  It would be part of the standard files API (http://gruntjs.com/configuring-tasks#files)

For example:
```
grunt.initConfig({
    copy: {
        frontend: {
            files: [{
                globExpand: false, // This option disables glob-expansion of file paths within this files object
                src: ['docs/How does this work?.md'],
                dest: ['out/docs']
            }]
        }
    }
}
```

In this example, `src` is programmatically generated by another task, so there's no way of knowing the filenames in advance.  It's shown inline in this example for simplicity.

**Comment by cowboy** [comment]
Have you tried `src: ['docs/How does this work\\?.md'],`? I think the underlying [glob library](https://github.com/isaacs/node-glob) supports escaping in that way.

**Comment by cspotcode** [comment]
I've investigated that, yes.  I would have to write code that
programmatically escapes all special characters, not just the question
mark.  It would be nice to bypass glob altogether, since ultimately my goal
is to pass a raw list of file paths, knowing that glob expansion is not
necessary.

**Comment by cowboy** [comment]
I'd be in favor of a `noglob` boolean option for this.

**Comment by cspotcode** [comment]
Ok, cool, I'll see if I can write a patch.  No promises, since Thanksgiving
is days away.  However, I've explored the grunt source code before, so I
have some idea of where to go.
