### ISSUE TITLE
grunt.file.writeJSON & writeYAML

### ISSUE THREAD

**Issue by JulianLaval** [gruntjs/grunt#1370]
`grunt.file` possesses both `readJSON` and `readYAML` methods. Would it make sense to provide build-in companion methods `writeJSON` and `writeYAML`?

**Comment by pacav69** [comment]
it could be useful for creating user.json files that were stored globally so that when an app required user data for example user.name, user.email, git details etc. it would read this file and display it as default, so that the developer would not have to retype information for each project.

**Comment by shama** [comment]
I'd recommend using a library on npm for writing JSON or YAML. Grunt's utilities eventually will be deprecated in favor of using more up to date libraries on npm instead.
