### ISSUE TITLE
Release 0.4.6

### ISSUE THREAD

**Issue by paladox** [gruntjs/grunt#1374]
Please release grunt 0.4.6 since there hasent been an update in a year and there are minor updates since the release of 0.4.5

**Comment by vitaly-t** [comment]
+1

**Comment by solovets** [comment]
+1

**Comment by davidlemaitre** [comment]
+1

**Comment by hlfcoding** [comment]
:+1:

**Comment by zlorf** [comment]
+1 oh +2

**Comment by tangst** [comment]
+1

If there is not going to be development of this by the Grunt core team anymore, this repo should be released to the community.  There are a lot of developers at all levels of business that rely on Grunt and have not jumped on the "latest and greatest" of build tools.  We still need active development/maintenance on Grunt!

**Comment by outsideris** [comment]
+1

**Comment by phi2x** [comment]
+1

**Comment by jshemas** [comment]
+1

**Comment by michahell** [comment]
+1

**Comment by cteyton** [comment]
+1

**Comment by dmethvin** [comment]
We're looking for people who want to reboot the Grunt team to help with code, documentation, bug triage, and all the other things it takes to make a project lively. If you're interested in helping please post here: https://github.com/gruntjs/grunt/issues/1403

If you are just waiting for the next release, please just wait and *don't* post there, it's only for people who want to help.
