### ISSUE TITLE
 “error: invalid top-level expression” when running Grunt Compile?

### ISSUE THREAD

**Issue by Cypher278999** [gruntjs/grunt#1377]
What causes the below error when running Grunt Compile? Sass and Npm are installed & environment variables are setup (C:\Ruby21\bin - C:\Users\Sales4\AppData\Roaming\npm) - This if for a pre-existing Grunt Project and all that was required was that I install Sass, Npm & Grunt on my Windows 7 computer.

Please note that I had did have to install an older version (0.10.36) of Node.js to get Npm to install without error? There is also a Gist link below to the "gruntfile.js" that is in the project. I have been struggling with this for days and I am a beginner with limited knowledge. Thank you for any help.

`$ grunt compile
Running "sass:dev" (sass) task
Warning: source string:1: error: invalid top-level expression
Use --force to continue.
Aborted due to warnings`

https://gist.github.com/Cypher278999/6e2703dc3391e4509098#file-grunt_compileissue-txt

**Comment by vladikoff** [comment]
Something to do with the SASS task, check the `sass:dev` task
