### ISSUE TITLE
3 Seconds!! is this the normal time grunt takes to run a task?

### ISSUE THREAD

**Issue by rohitbind** [gruntjs/grunt#1378]
Hi Guys,
I using grunt to just compile sass to css and it is taking 3seconds sometimes more than that. Is this the normal time it takes to run a task?

Here is my configuration. 
module.exports = function(grunt) {
    require('time-grunt')(grunt);
    require('jit-grunt')(grunt);
    grunt.initConfig({
        pkg: grunt.file.readJSON('package.json'),
        concat: {
            options: {
                separator: "\n\n"
            },
            dist: {
                src: ['src/resources/js/MyApp.js'],
                dest: 'src/resources/js/<%= pkg.name %>.js'
            },
            deps: {
                src: [
                    'bower_components/modernizr/modernizr.js',
                    'bower_components/jquery/dist/jquery.min.js',
                    'bower_components/bootstrap/dist/js/bootstrap.min.js',
                    'bower_components/angularjs/angular.min.js',
                ],
                dest: 'src/resources/js/<%= pkg.name %>-deps.js'
            },
            css: {
                src: ['src/resources/css/style.css', 'src/resources/css/bootstrap-custom.css'],
                dest: 'src/resources/css/<%= pkg.name %>.css'
            }
        },
        uglify: {
            options: {
                banner: '/*! <%= pkg.name %> <%= grunt.template.today("dd-mm-yyyy") %> */\n',
                mangle: false
            },
            dist: {
                files: {
                    'src/resources/js/<%= pkg.name %>.min.js': ['<%= concat.dist.dest %>']
                }
            },
            deps: {
                files: {
                    'src/resources/js/<%= pkg.name %>-deps.min.js': ['<%= concat.deps.dest %>']
                }
            }
        },
        sass: {
            dist: {
                options: {
                    style: 'compressed'
                },
                files: {
                    'src/resources/css/bootstrap-custom.css': 'src/resources/css/bootstrap-custom.scss'
                }
            },
            dev: {
                options: {
                    style: 'compressed'
                },
                files: {
                    'src/resources/css/style.css': 'src/resources/css/style.scss',
                }
            }
        },
        watch: {
            scripts: {
                files: ['src/resources/js/**/*.js'],
                tasks: ['concat:dist'],
                options: {
                    spawn: false,
                },
            },
            styles: {
                options: {
                    livereload: true,
                },
                files: ['src/resources/css/*.scss'],
                tasks: ['sass:dev']
            }
        }
    });
    grunt.registerTask('default', 'Default Task Alias', ['build']);
    grunt.registerTask('build', 'Build the application', ['sass:dev',
        'concat:css'
    ]);
}

![grunt taking 4sec](https://cloud.githubusercontent.com/assets/4253361/9830456/67f3de16-594c-11e5-9a8e-f5a19bbeff15.PNG)

**Comment by iamntz** [comment]
Yes, that's normal, because grunt-contrib-sass is a wrapper of ruby sass, which isn't the fastest on the planet.

You could try [grunt-sass](https://github.com/sindresorhus/grunt-sass) instead, which is way faster [(although some features may miss)](http://sass-compatibility.github.io/)

**Comment by gabrielalan** [comment]
Yep, like iamntz said, the ruby compiler isn't the fastest sass compiler. I have used them both, and grunt-sass is much more fast than grunt-contrib-sass, because is made with c++. I earned more than 100% of execution time.

**Comment by rohitbind** [comment]
Thank iamntz and gabrielalan.. I already started using grunt-sasa
