### ISSUE TITLE
Registry error Invalid Version

### ISSUE THREAD

**Issue by hellboy81** [gruntjs/grunt#1382]
Missing. You might want to install these.
 ◯ grunt-contrib-clean missing                  Registry error Invalid Version: 0.4.0rc6
 ◯ grunt missing                                Registry error Invalid Version: 0.4.0rc8

grunt 
   ?? NPM ERR!  Registry error Invalid Version: 0.4.0rc8

runt-contrib-clean 
  ??  NPM ERR!  Registry error Invalid Version: 0.4.0rc6

**Comment by shama** [comment]
Try `npm install grunt grunt-contrib-clean` to install the latest versions of those packages.
