### ISSUE TITLE
Incorrect task's options while the config of the task is a template string

### ISSUE THREAD

**Issue by 0of** [gruntjs/grunt#1383]
```javascript
// grunt version 0.4.5
grunt.initConfig({
  ref: '<%= res %>',
  res: {
    options: {
      a: 10
    }
  }
});

grunt.registerTask('ref', function () {
  // equals to `options: { a: 10 }`
  // NOT `{ a: 10 }`
  this.options();
});
```

Though it is not a good practice, I'm curious about it is designing for purpose or an unintentional omission for later resolving.

**Comment by jonschlinkert** [comment]
to clarify, are you saying that the `ref` object is resolving to this:

```
{
  res: {
    options: {
      options: {
        a: 10
      }
    }
  }
}
```

**Comment by 0of** [comment]
No. The resolving of the property template string  '<%= res %>' is absolutely correct.

```javascript
grunt.config([name, 'options'])
-> config.getRaw([name, 'options']) // equals to '<%= res %>'
-> config.process() // expands to `options: { a: 10 }`
```

**Comment by shama** [comment]
Closing as this seems to be just a misuse of template strings. Although, if you have a valid use case for the above behavior please speak up. Thanks!
