### ISSUE TITLE
Upgrade find-syncup version to 0.3.0

### ISSUE THREAD

**Issue by abhijeetkpawar** [gruntjs/grunt#1384]
Older find-syncup version has Lodash dependency which increases the overall package size by ~900KB. Version 0.3.0 has removed it.

**Comment by CarlRosell** [comment]
The only deprecation left for a lot of my projects. :+1:

**Comment by danpoltawski** [comment]
:+1:  please update to get rid of this deprecation

**Comment by shama** [comment]
Done on 5357b289f9b54c8ba2fcebed97e179c4d44e4a87
