### ISSUE TITLE
How cound grunt support ES6?

### ISSUE THREAD

**Issue by hwoarangzk** [gruntjs/grunt#1385]
I wrote a grunt task which is a http server based on `koa`, but when I run `grunt default`, it reported the error that can't recognize '*' which is the symbol of the `generator` in ES6. My node version is `0.12.7`. So what should I do to solve this issue? Thanks

**Comment by shama** [comment]
You would need to use a version of Node.js that supports generators or use a library that can polyfill, such as https://babeljs.io/docs/setup/#grunt
