### ISSUE TITLE
grunt : command not found

### ISSUE THREAD

**Issue by durwasa-chakraborty** [gruntjs/grunt#1392]
I have read the documentations very carefully and I have followed every step verbatim as given in the official documentation of grunt <link> http://gruntjs.com/installing-grunt </link>.  However `grunt --version` __shows grunt : command not found.__
My path of ~/.bashrc is __export PATH="/usr/local/bin/npm:/usr/local/bin:/usr/local/sbin:~/bin:$PATH"__  the path I got after running the command `whereis npm`. `whereis grunt` shows no result but `npm list -g | grep grunt` returns __├─┬ grunt-cli@0.1.13__. After some desperate measures I tried `locate grunt` and I found out 31000 results and pastebin is not able to handle that big request. But the grunt can be found in the __.npm__ folder also in the __meanjs__ Is there a possibility that it is because of some conflict between the two or I am doing something wrong?

**Comment by charaf-des** [comment]
i have the same problem same result as you, did you find a solution ?
