### ISSUE TITLE
Questions around grunt 1.0.0

### ISSUE THREAD

**Issue by ptitgraig** [gruntjs/grunt#1393]
Hello guys !

First of all i thank you for this great tool. I've been using grunt for years and appriciated a lot the benefits of it.

I think many of grunt users are wondering whether a 1.0.0 version will be released some day and what kind of chnages a 1.0.0 will bring. I've seen a Grunt 1.0 written by T.Kellen on Github but it does not seem to be maintained: https://github.com/gruntjs/grunt-next

Since Grunt is more and more used in companies over the world, and that it's now running on a stable version of node.js (grunt is compatible with node.js v4.0 i believe ?), are there any chances that grunt version could be pushed to 1.0.0 ?

What are your plans about this ?

Thanks for all your great work.

**Comment by scurker** [comment]
See #1403 and http://blog.jquery.com/2015/11/19/grunt-rebooted/

It sounds like a push to 1.0.0 would need to be reserved for truly breaking changes and hopefully is moving that direction with further community support.
