### ISSUE TITLE
Can't get Grunt file.exist to work

### ISSUE THREAD

**Issue by kennybright** [gruntjs/grunt#1400]
module.exports= function(grunt){
    
    grunt.config.init({
        build: {
            angular:{
                src: ['bower_components/angular/angular.js',
                      'bower_components/angular-resource/angular-respurce.js'],
                dest: 'dist/angular.js'
                
            },
            
            angularWithjQuery: {
                     src: ['bower_components/jquery/dist/jquery.js',
                        'bower_components/angular/angular.js',
                           'bower_components/angular-resource/angular-respurce.js'],
                dest: 'dist/jquery-angular.js'
            }
        
        }
        
    });
    
    grunt.registerMultiTask('build','Concatenate files', function(){
        var output='';
        // access targets as an array then iterate over targets and get file
        
        this.files.forEach(function(filegroup){
            var sources = filegroup.src.map(function(file){
                
                var ret = grunt.file.exists(file);
                if (ret){
                    return(grunt.file.read(file));
                }
                else{
                    grunt.fail.fatal('file does not exist')
                }
            });
            
            output = sources.join(';');
            grunt.file.write(filegroup.dest,output);
        });
        
    });
    
}

**Comment by shama** [comment]
Could you describe more about what isn't working for you with `grunt.file.exists`?

This part looks suspect `return(grunt.file.read(file));` as I don't think you intend on `return`ing within the `forEach` function if the file exist.

**Comment by kennybright** [comment]
thanks. its been a while! i don't actually remember the context. whatever it was i found either an answer or a workaround.

cheers...

Date: Mon, 23 Nov 2015 13:09:11 -0800
