### ISSUE TITLE
Grunt project tasks for jQuery Foundation transition

### ISSUE THREAD

**Issue by dmethvin** [gruntjs/grunt#1404]
- [x] Change LICENSE-MIT to standard jQF LICENSE.txt
- [x] Do CLA checks for existing contributors
- [x] Ensure team is clear on CLA requirements for contributions
- [x] Hook up jquery-cla-checker to CI suite
- [x] Update contributing info (currently at gruntjs.com)
  - Include link to the jQF code of conduct, code style docs, etc.
  - Change CLA link to be the jQF one
  - Fix outdated links to closed tickets, replace with an issue query?
- [x] Add grunt-dev to irc.jquery.org logging

**Comment by dmethvin** [comment]
Having the contributing info at http://gruntjs.com/contributing is fine, as long as it's kept fresh. Since it covers both this repo and the others I can see the benefit of having it there.

**Comment by stevemao** [comment]
@dmethvin Where can i find the details of the transition and what's the future of grunt?

**Comment by dmethvin** [comment]
@stevemao As far as the Foundation work goes, we're just doing the items on this checklist. The future of grunt will be determined by the people who step up to participate in building it. I hope to get the items above done soon but would welcome help from others.

**Comment by JKAussieSkater** [comment]
@JKAussieSkater, tagging myself so I remember to change the licenses

**Comment by shama** [comment]
Hey @dmethvin! Is there anything I can do or someone I should talk with to start on these items? Should we start on the CLA checks for existing contributors and if so, does JQF have a tool for handling that? Thanks!

**Comment by dmethvin** [comment]
Yeah, every action item has been a battle. Sorry about the delay!

The [jquery-license tool](https://github.com/jquery/jquery-license) can be used for both auditing existing contributions and for checking new pull requests. There was a bit of a delay because we needed to [update the tool](https://github.com/jquery/jquery-license/pull/61) to handle repos other than jquery, and once that was done it turns out there is [another change](https://github.com/jquery/jquery-wp-content/issues/390) to the instruction page that needs to be made before it can work on other repos.

I have a [draft of the project onboarding document](https://docs.google.com/document/d/1eD5u1wQuvO8SeR0eXXh8pAC2w2nIjmKj1tFgzSDbJLE/edit) and have been slowly trying to get it into shape at the same time. Feel free to comment on that doc or ask questions BTW.

On that last check box regarding IRC, can I add #grunt and #grunt-dev to the IRC list and logging list?

**Comment by shama** [comment]
Thanks Dave! I'll check that out that tool and subscribe to that issue. Thanks for the link to the doc, looks very helpful for onboarding!

Yes, please add #grunt and #grunt-dev to the list.
