### ISSUE TITLE
Issue with install grunt OS X ElCapitan

### ISSUE THREAD

**Issue by Peter74** [gruntjs/grunt#1408]
Hi, I try to install grunt and I got WARN, but I am not able to find what is a problem.
...really I am new in OS X, than if that is issue related to me, please try to give me answer or link, because google know everything, but I did not find clear answer on that:

this is warns:
```
npm WARN deprecated lodash@0.9.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
```

thank you Peter

**Comment by vladikoff** [comment]
That is just a warning.

cc @jdalton

**Comment by jdalton** [comment]
Yep.

**Comment by Peter74** [comment]
Thank you. It happened yesterday and I try to check if grunt is present in system - so I did: grunt --version and i got message, that grunt is not...but when I did now, everything is OK.

really sorry for this, I thought, that I do not need restart OS X after installing something... Thanks.
