### ISSUE TITLE
grunt.util.normalizelf doesn't work on Windows 10

### ISSUE THREAD

**Issue by cuiwu** [gruntjs/grunt#1413]
I try to use the method grunt.util.normalizelf('\n') to split my file content on Windows 10, but it doesn't work.

**Comment by deostroll** [comment]
share code on how you've used it

**Comment by shama** [comment]
@cuiwu Could you post more information on what you have tried? I tried on Windows 10 and it worked for me.

**Comment by shama** [comment]
Closing for lack of response and it works for me.

**Comment by cuiwu** [comment]
@shama Sorry for forgot to response, it used to split the content of a file, like this:
`commentContent = grunt.file.read(commentFilePath),
      commentLineArr = commentContent.split('\n');
      //grunt.util.normalizelf('\n') doesn't work on Windows 10`
