### ISSUE TITLE
Install Grunt 0.4.x on NodeJS 5.2.0

### ISSUE THREAD

**Issue by Fioenix** [gruntjs/grunt#1416]
There are errors when I install Grunt 0.4.x on NodeJS 5.2.0

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\tangd\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "grunt" "--save-dev"

npm ERR! node v5.2.0
npm ERR! npm  v3.5.3
npm ERR! path f:\Business\Mobile World\Projects\nlp\node_modules\sails\node_modules\js-yaml
npm ERR! code EXDEV
npm ERR! errno -4037
npm ERR! syscall rename

npm ERR! EXDEV: cross-device link not permitted, rename 'f:\Business\Mobile World\Projects\nlp\node_modules\sails\node_modules\js-yaml' -> 'f:\Business\Mobile World\Projects\nlp\node_modules\js-yaml'

**Comment by vladikoff** [comment]
See https://github.com/npm/npm/issues/9863 , try downgrading to npm v2 and see if that fixes that
