### ISSUE TITLE
Grutn could be more forgiving? 

### ISSUE THREAD

**Issue by nternetinspired** [gruntjs/grunt#1417]
Grunt, awesome though it is, seems to insist on correct spelling of the task at all times. Is this really necessary?

npm has no problem with me using `npm isntall` so why does Grunt pretend I don't exist, several dozen times a day, when I type `grutn`?

:hear_no_evil:

**Comment by accommodavid** [comment]
You could create an alias in your shell and map `grutn` to `grunt`. See for example [this thingy](http://askubuntu.com/questions/1414/how-to-create-a-permanent-alias).

**Comment by nternetinspired** [comment]
You're entirely correct @accommodavid, thank you for your helpful answer. 

I was actually trying to be humorous, but reading back my post now (without beer googles) it doesn't seem so funny. Sorry.
