### ISSUE TITLE
Use <% %> as a string in Gruntfile.js

### ISSUE THREAD

**Issue by NextSeason** [gruntjs/grunt#1418]
I have Gruntfile.js like this :

grunt.initConfig( {
    ...
    host : '/<%= STATICPATH %>/',
    ...
} );
<%= STATICPATH %> is a template variable in my app but not for Gruntfile, I want to replace somewhere in my code to this. But grunt always parse this as grunt template variable. Is there anyway to resolve this problem ?

**Comment by shama** [comment]
You can add alternative delimiters and use those if they conflict:

```js
grunt.template.addDelimiters('curly', '{%', '%}')
grunt.template.setDelimiters('curly')
```

http://gruntjs.com/api/grunt.template#grunt.template.setdelimiters
