### ISSUE TITLE
`grunt.util.spawn` should handle `--debug` and `--debug-brk` to prevent port reusing

### ISSUE THREAD

**Issue by segrey** [gruntjs/grunt#1420]
Currently, if grunt main process is started with `--debug-brk=<debug port>` (or `--debug=<debug port>`), `grunt.util.spawn` inherits this cli option and starts child process with the same debug port. Thus, the spawned child process fails to start, because the specified debug port is already bound (by the main grunt process).
Possible fix could be to find an available port (if the main grunt process is started in debug mode) and specify the found free port when spawning the child process. Thanks!

**Comment by segrey** [comment]
JFYI, I've filed similar, but a bit more generic issue in nodejs project: https://github.com/nodejs/node/issues/4419
If it gets fixed there, this issue can be closed.

**Comment by inthegarage** [comment]
Hi Segrey,

That issue is now fixed, what is the status of this issue therefore?

**Comment by segrey** [comment]
Yep, closing.

**Comment by inthegarage** [comment]
Thanks Segrey, Do you know when this will be available? I've tried 5.10.1 and the port 0 is still rejected. I've tried debug-port=0 and debug-brk=0 all to no avail.

**Comment by segrey** [comment]
I think https://github.com/nodejs/node/pull/5025 should be tracked
