### ISSUE TITLE
command line argument is broken

### ISSUE THREAD

**Issue by mageddo** [gruntjs/grunt#1421]
I've writed a plugin for grunt and I use `this.option('my-custom-option')`, on command line I pass `grunt task --my-custom-option=1.0`

For some motive if I pass `1.0`,` 2.0`, `3.0` on plugin I get `1`, `2`, `3` o.O, there some test cases

	
	--my-custom-option 1.0		> 1
	--my-custom-option=1.0		> 1
	--my-custom-option=1.1		> 1.1
	--my-custom-option=2.0		> 2
	--my-custom-option=2.1		> 2.1
	--my-custom-option=2.0.0	> 2.0.0
	--my-custom-option=1.0.0	> 1.0.0

**Comment by sashashakun** [comment]
I can try to solve this thing. You want to have the same option that you pass?
I mean: pass `--my-custom-option=1.0 ` and get `1.0`? 
You think it's better then how it works now know?

**Comment by mageddo** [comment]
Today it works like the example, the bug is only for `x.0`. Yes, I want to get the same value that I pass on terminal, as your example:

    --my-custom-option=1.0 and get 1.0?
