### ISSUE TITLE
No grunt.file.getBase?

### ISSUE THREAD

**Issue by SmartArtsStudio** [gruntjs/grunt#1423]
Yes, everything is relative to the Gruntfile.js, but what if another grunt module has used "grunt.file.setBase()" to alias their Gruntfile.js to somewhere it is not? I could not recognise a "grunt.file.getBase" equivalent to resolve this without going to node Path. 

No big deal, I rolled my own. I just thought it odd that if grunt moves it, should it not also be able to tell others where? Sorry if I have missing something obvious in the docs? (I even did a 'getBase' search of the source.)

**Comment by shama** [comment]
`grunt.file.setBase()` is convenience method for calling `process.chdir(path.join(yourpath))`. I recommend using `process.cwd()` if you want to get the base that has been set.

https://nodejs.org/api/process.html#process_process_cwd
