### ISSUE TITLE
For loop adds random style names when iterating over a string

### ISSUE THREAD

**Issue by making3** [gruntjs/grunt#1424]
I've found an issue when iterating over a string using `for (var i in string)`. I originally thought it was in the plugin (grunt-mocha-test), but the [owner proved this wrong](https://github.com/pghalliday/grunt-mocha-test/issues/114#issuecomment-170261485) as he only had Gruntfile used in this project.

Gruntfile.js

	module.exports = function(grunt) {
	  var message = 'asdf';

	  for (var i in message) {
		  console.log('i: ', i);
	  }
	};

Output:

	i:  0
	i:  1
	i:  2
	i:  3
	i:  bold
	i:  underline
	i:  strikethrough
	i:  italic
	i:  inverse
	i:  grey
	i:  black
	i:  yellow
	i:  red
	i:  green
	i:  blue
	i:  white
	i:  cyan
	i:  magenta
	i:  greyBG
	i:  blackBG
	i:  yellowBG
	i:  redBG
	i:  greenBG
	i:  blueBG
	i:  whiteBG
	i:  cyanBG
	i:  magentaBG
	i:  rainbow
	i:  zebra
	i:  stripColors
	i:  zalgo

Expected output:

	i:  0
	i:  1
	i:  2
	i:  3

This happened on my work laptop originally, with the following versions:
OS: Windows 7 64 bit
Node: 5.1.0
Grunt-cli: 0.1.13
grunt: 0.4.5

And now tested on my home computer:
OS: Windows 7 64 bit
Node: 4.2.4
Grunt-cli: 0.1.13
grunt: 0.4.5

I'm using `for (var i = 0; i < message.length; i++)` instead for now.

**Comment by dmethvin** [comment]
Looks like the [colors](https://github.com/gruntjs/grunt/blob/00fa3badfc7cdf87fc65d90b8f4442026ec639f9/package.json#L39) module [extends the String prototype](https://github.com/Marak/colors.js/blob/9f3ace44700b8e705cb15be4767845c311b3ae11/lib/extendStringPrototype.js). That allows for nice syntax like `console.log("error".red)` and I suspect it's used by Gruntfiles, but right now the methods are defined as enumerable. Perhaps someone could file a PR against that repo to fix?

**Comment by dmethvin** [comment]
Looking at it further it seems that this just can't be changed, colors.js modifies String.prototype and that's considered a feature, which Grunt passes through.

**Comment by making3** [comment]
@dmethvin  I'll close this since it's intended, thanks for looking into it, I'll keep the work around I had in place.
