### ISSUE TITLE
Dependencies injection (multi-app)

### ISSUE THREAD

**Issue by ChuckB11** [gruntjs/grunt#1425]
Hi,
I'm new in Angular and i made a big application with many modules in it, but when i want to build it (grunt serve:dist),i have every single modules in my dist file.

I need to do custom builds with dependencies but i don't know how.

What i need is to be able to do something like "grunt serve:app1" and "grunt serve:app2" where i will have "module1" in app1 and "module2" in app2 but not "module2" in app1.

I just need different module injections for differents dist builds.
Please help me, i'm pretty lost with angular builders.
Thanks
Boris

**Comment by shama** [comment]
Grunt itself doesn't do anything with Angular. But rather just provides tooling for others to use that may use Angular. I don't use Angular or the build setup you've got so unfortunately cannot provide any help.

I recommend using a service like stackoverflow if you have a general question like above. Thanks!
