### ISSUE TITLE
Grunt v1.0.0-rc1

### ISSUE THREAD

**Issue by shama** [gruntjs/grunt#1430]
This release is to address critical issues, migrate to the jQuery Foundation and communication about the future of Grunt.

Specifically the issues we are addressing in this release are: https://github.com/gruntjs/grunt/milestones/rc1

- [ ] ~~Move to jQuery Foundation~~ 👉`1.0.0`
- [x] Create a rfcs repo: https://github.com/gruntjs/rfcs
- [x] Ensure compatibility with Node.js v0.10, v0.12, 4.x and latest npm
- [x] Drop support for Node.js v0.8
- [x] Update outdated dependencies and provide an upgrade path for breaking changes
  - [x] Update `grunt-legacy-util` dependencies
    - [x] `grunt.util._.template` now returns a compile function so `template.process` needs to be updated to accommodate `tmpl = grunt.util._.template(tmpl, options)(data);`.  
    Fixed in `next/grunt-legacy-util` 3cc26ba4caf9d673fddf4f4c4c4d3f2446a7d319
    - [x] `grunt.util._.flatten` doesn't work the same. It's now `flattenDeep` and needs to be updated in certain places to ensure compatibility.  
    Fixed in `next/grunt-legacy-util` 3cc26ba4caf9d673fddf4f4c4c4d3f2446a7d319
  - [x] `coffee-script@1.10.x`
  - [x] `iconv-lite@0.4.x` (Strips BOM by default, updated to provide `stripBOM: !file.preserveBOM`)
  - [x] `glob@6.0.x`
  - [x] `dateformat@1.0.12` (~~look into why this is tagged differently~~ Because of old fashion versioning)
  - [x] `minimatch@3.0.x`
  - [x] `js-yaml@3.5.x`
  - [x] `nopt@3.0.x`
- [x] Add bin script to local Grunt
  - [ ] ~~Add note about: `npm run grunt -- task:target` is possible `npm >= 2.0.0`~~ 👉`1.0.0`
- [x] Update `grunt-cli` dependencies
- [x] Investigate why glob/minimatch doesn't seem to sort on Node.js v0.10 (https://github.com/isaacs/node-glob/issues/215)
- [x] Extend `grunt.util._.templateSettings` instead of overriding: GH-1151
- [x] `mode` can be passed to `grunt.file.write`. GH-956

**Comment by vladikoff** [comment]
- [ ] peerDependencies ( https://github.com/gruntjs/grunt/issues/1355 )

**Comment by stevemao** [comment]
Looks like there is no series/parallel task execution plans in 1.0.0? Also no plans to remove `grunt-legacy-util`?

> coffee-script@1.10.x

I'd say many people want babel support out of the box instead.

**Comment by shama** [comment]
@stevemao Feel free to sponsor a [rfc](https://github.com/gruntjs/rfcs) for any significant feature you want for a future version of Grunt.

`1.0.0` is focused only on critical issues and Node.js compatibility.

> I'd say many people want babel support out of the box instead.

https://github.com/gruntjs/grunt/pull/1368#issuecomment-177314182

**Comment by stevemao** [comment]
I'm fine with the scope. I just thought with the release of 1.0.0, it's a really good chance to drop legacy code (`grunt-legacy-util` and `coffee-script`).

**Comment by shama** [comment]
I want to make dropping support for things extremely visible. Such as removing the coffee-script register will cause a lot of plugins to break. I want to avoid fracturing plugins (meaning some plugins will work with a specific version of Grunt), at least until we can avoid Grunt as a peer dependency.

So the plan is to release `1.0.0` then I'm going to submit rfcs for the things I'd like to see in the next version. One being deprecating a bit of things by first displaying warnings with upgrade paths and indicating the API will be fully removed in the next major version.

**Comment by stevemao** [comment]
Hm... why not `0.5.0` then?

**Comment by dmethvin** [comment]
It's really risky to release anything less than 1.0.0 because many package.json files have version specs that will automatically upgrade to it and something is bound to break. In reality, Grunt is used by a bazillion projects and certainly is far past being the pre-release pre-production project that a sub-1.0.0 version implies. So it seems like a good idea to do some minor cleanup, release a 1.0.0, and go from there.

**Comment by stevemao** [comment]
> It's really risky to release anything less than 1.0.0 because many package.json files have version specs that will automatically upgrade to it and something is bound to break.

Not exactly true. `^0.4.5` will not match `0.5.0`

> In reality, Grunt is used by a bazillion projects and certainly is far past being the pre-release pre-production project that a sub-1.0.0 version implies.

I agree. grunt should be `1.0.0` two years ago as it was quite solid back then. But now nodejs has changed a lot, a lot of philosophies of node modules have been changed. Unfortunately the project has been maintained for quite long and it keeps a lot of legacy code. If we release `v1.0.0` it give people an impression that grunt becomes a modern module but it still has `grunt-legacy-util` (this has been deprecated for two years) and `coffee-script`. 

I agree we can release 1.0.0 without adding new features. This is bikeshedding anyways. Just my 2c :)

**Comment by vladikoff** [comment]
> a lot of legacy code.

A lot of legacy stable code that works in all node.js releases. I'm not sold on the whole "modern module" argument.

**Comment by dmethvin** [comment]
Actually, node.js itself is a good model for how to treat versions, it went from 0.12 to 5.0 in about 18 months. In the past most projects have treated a major version like a precious jewel or a marketing tool that indicated it had a bunch of new stuff. Semver says that you do a new major when you're breaking something, no more and no less. There can be a Grunt 2.0 soon that removes or updates a bunch of stuff if that makes sense, but starting with a solid 1.0.0 seems good.

**Comment by kidwm** [comment]
I agree with @dmethvin, releasing 1.0.0 is good target.

**Comment by vladikoff** [comment]
@shama I'm seeing Windows tests failing after the write-options fixes: https://ci.appveyor.com/project/gruntjs/grunt/history

```
 
Running "nodeunit:all" (nodeunit) task
Testing cli_test.js....OK
Testing config_test.js.........OK
Testing event_test.js.OK
Testing file_test.js.............................F......................
>> file - write
>> Error: Expected 6 assertions, 3 ran
>>   at Object.exports.file.tearDown (test\grunt\file_test.js:414:5)
>>   at processImmediate [as _immediateCallback] (timers.js:363:15)
 
>> file - write
>> Error: EPERM, operation not permitted 'C:\Users\appveyor\AppData\Local\Temp\1\1454131631229.2422'
>>   at Object.fs.unlinkSync (fs.js:772:18)
>>   at File.unlinkSync (node_modules\temporary\lib\file.js:107:24)
>>   at Object.exports.file.write (test\grunt\file_test.js:476:13)
>>   at Object.exports.file.setUp (test\grunt\file_test.js:405:5)
>>   at processImmediate [as _immediateCallback] (timers.js:363:15)
 
Testing option_test.js...OK
Testing task_test.js...OK
Testing template_test.js..OK
Testing task_test.js......................OK
Warning: 2/387 assertions failed (2219ms) Use --force to continue.
 
Aborted due to warnings.
npm : npm ERR! Test failed.  See above for more details.
At line:1 char:1
+ npm test # PowerShell
+ ~~~~~~~~
    + CategoryInfo          : NotSpecified: (npm ERR! Test f...r more details.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Command executed with exception: npm ERR! Test failed.  See above for more details.
```

**Comment by vladikoff** [comment]
@shama could be because of the mode difference in Windows: https://github.com/gruntjs/grunt/commit/0b21d25b3b3ba498d51eae1279d3f372a841c4d9#diff-c97174579915dbed0c37822abcb5f444R475

**Comment by shama** [comment]
@vladikoff That happens when it's not ran as Administrator on Windows. Which is required for symlinks. I'll look into why appveyor isn't running as Admin anymore:

<img width="681" alt="screen shot 2016-02-06 at 8 38 00 pm" src="https://cloud.githubusercontent.com/assets/99604/12870934/d26a8c5c-cd11-11e5-8890-fa4e1137567d.png">

**Comment by shama** [comment]
Hmm maybe not because of Admin perm, checking something else...

**Comment by shama** [comment]
I should have read the failing test more clearly. It can't delete because the file isn't writeable and Windows in that environment didn't like that (but was cool with it locally for some reason).

**Comment by shama** [comment]
Fixed now: https://ci.appveyor.com/project/gruntjs/grunt/build/87
