### ISSUE TITLE
Is it possible to change the selenium server address through parameters for different tasks in grunt 

### ISSUE THREAD

**Issue by prakashomp** [gruntjs/grunt#1432]
Can I write code like bellow to change the server address but this is showing error as device name and platform require like that

protractor: {
            task1: {
                options: {
                    configFile: "Conf.js",
                    args: {
                        browser: 'chrome',
                        seleniumAddress: 'http://localhost:4444/wd/hub',
                        specs: ['....']
                    }
                }
                },
            Task2: {
                options: {
                    configFile: "Conf.js",
                    args: {
                        browserName: 'chrome',
                        platformName: 'Android',
                        deviceName: 'Galaxy S5',
                        seleniumAddress : 'http://localhost:4723/wd/hub',
                        specs:['.....']
                    }
                }
            },
			}

Can any one help to solve this one.

**Comment by vladikoff** [comment]
please ask this on StackOverflow
