### ISSUE TITLE
Installation requires, changing the environment variables concerned with the proxy settings.

### ISSUE THREAD

**Issue by GABBAR1947** [gruntjs/grunt#1433]
Installation requires, setting the environment variables HTTP: HTTPS instead of http:https in the proxy settings in the bashrc while using 
            sudo npm install  grunt-cli and sudo npm install grunt

Either we include these instructions in the README or automate this while installing.

**Comment by shama** [comment]
Installation shouldn't require those environment variables. What error are you seeing?

**Comment by GABBAR1947** [comment]
Well, nothing gets initiated. There happens to be no progress in the installation.

**Comment by vladikoff** [comment]
Never seen this happen. Could be an npm issue and not a grunt issue.

**Comment by vladikoff** [comment]
Is this on Windows? 

Ref https://github.com/npm/npm/issues/10713

**Comment by GABBAR1947** [comment]
No, this occurs in Ubuntu. Changing the environment variables solves this issue.

**Comment by shama** [comment]
Grunt doesn't specifically require environment variables for installation. If you can provide reproducible steps to what you have tried, errors you ran into and how it is specifically an issue with Grunt we can address it then. Thanks!
