### ISSUE TITLE
Allow passing config values verbatim (immune to template processing)

### ISSUE THREAD

**Issue by cspotcode** [gruntjs/grunt#1435]
Related: #1418

Grunt's template processing causes problems in certain situations.  For example:

* #1418, where someone wants to use a literal string wrapped in "<%= ... %>" and doesn't want grunt to expand it.
* In my grunt-webpack config, I need to pass a reference to a `new stylus.nodes.Object()` which internally contains a circular reference.  Grunt's trying to perform template processing, which causes "Warning: Circular reference detected"  I definitely don't want this, because I have no idea what's inside the object.
* grunt-webpack itself uses a workaround to avoid grunt clobbering config values: https://github.com/webpack/grunt-webpack/blob/master/lib/getWithPlugins.js#L9-L11

There should be a way to disable it for certain values.  A simple interface would be to expose a `noProcess` wrapper for values that shouldn't be processed.

```
const noProcess = grunt.template.noProcess;
grunt.config.set('my-task', {
    options: {
        optionA: noProcess(new MyTask.Option('bla bla')),
        host: noProcess('/<%= STATICPATH %>/')
    }
});
grunt.config.get('my-task.options.host'); // === '/<%= STATICPATH %>/'
grunt.config.getRaw('my-task.options.host'); // is an instance of noProcess wrapper object
```

EDIT: Added another real-world example

**Comment by shama** [comment]
It uses lodash templates. You can add/set your own template delimiters if the default ones are conflicting. See: http://gruntjs.com/api/grunt.template#grunt.template.setdelimiters

You can even manipulate lodash's template settings directly: `grunt.util._.templateSettings`: https://github.com/lodash/lodash/blob/1.3.1/doc/README.md#_templatetext-data-options

**Comment by cspotcode** [comment]
Changing the template delimeters doesn't fix the circular references problem (2nd example) or the grunt-webpack issue (3rd example); those are caused by grunt.util.recurse() replacing objects and trying to traverse the entire object graph, which happens regardless of if any strings contain template delimeters.

Plus, changing template delimeters applies globally to the entire gruntfile.  There's no way to scope it to a certain subset of your configuration.

**Comment by shama** [comment]
Ah I get what you're asking for. Currently that is left up to the task to decide. If an option is passed that should avoid template processing, the task should get the config raw, determine what it needs and call `grunt.template.process()` in the places it needs it. Rather than relying on the user configuring it.

**Comment by cspotcode** [comment]
In most cases, that's ok, but I believe we should still be able to explicitly configure it when necessary.  Here's my situation, where explicit configuration is necessary.  I'll make it as short as possible; thanks in advance for your time.

```js
grunt.initConfig({
    webpack: {
        entry: 'main.js', output: {path: 'out', filename: 'bundle.js'},
        module: {
            loaders: [{test: /\.styl$/, loader: 'stylus'}]
        },
        plugins: [/* ... grunt-webpack has special logic to getRaw this array ... */],
        stylus: {
            // Declare global variables to be available to my Stylus code
            // To enforce raw 
            define: {
                options: stylus.utils.coerceObject(optionsObj, true) // <--- this object contains a circular reference
            }
        }
    }
});
```

In this case, `stylus` contains options for `stylus-loader`.  This is loader-specific behavior; `grunt-webpack` only knows to `getRaw` the plugins array.  `stylus-loader` doesn't know about grunt, so it can't intervene.  It's up to me to tell grunt not to recursively traverse that object, but I have no mechanism to do so.

I don't think `grunt.template.noProcess` should be used often, but I think it should exist for when it's necessary.
