### ISSUE TITLE
grunt not working on El Capitan

### ISSUE THREAD

**Issue by haneenkrimly** [gruntjs/grunt#1439]
Something seems to be wrong with Grunt. I found this issue, and I tried to do everything that was mentioned but still. https://github.com/gruntjs/grunt/issues/757

Haneens-MacBook-Pro:~ HRK$ sudo npm uninstall -g grunt-cli
npm WARN uninstall not installed in /Users/HRK/.node/lib/node_modules: "grunt-cli"
Haneens-MacBook-Pro:~ HRK$ sudo npm install -g grunt-cli
/Users/HRK/.node/bin/grunt -> /Users/HRK/.node/lib/node_modules/grunt-cli/bin/grunt
grunt-cli@0.1.13 /Users/HRK/.node/lib/node_modules/grunt-cli
├── resolve@0.3.1
├── nopt@1.0.10 (abbrev@1.0.7)
└── findup-sync@0.1.3 (lodash@2.4.2, glob@3.2.11)
Haneens-MacBook-Pro:~ HRK$ grunt package
/Users/HRK/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'grunt' (>= 0) among 16 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/Users/HRK/.rvm/gems/ruby-2.2.1:/Users/HRK/.rvm/gems/ruby-2.2.1@global', execute `gem env` for more information
	from /Users/HRK/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:324:in `to_spec'
	from /Users/HRK/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:64:in `gem'
	from /Users/HRK/.rvm/rubies/ruby-2.2.1/bin/grunt:22:in `<main>'
	from /Users/HRK/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/HRK/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
Haneens-MacBook-Pro:~ HRK$ grunt -v
/Users/HRK/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'grunt' (>= 0) among 16 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/Users/HRK/.rvm/gems/ruby-2.2.1:/Users/HRK/.rvm/gems/ruby-2.2.1@global', execute `gem env` for more information
	from /Users/HRK/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:324:in `to_spec'
	from /Users/HRK/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:64:in `gem'
	from /Users/HRK/.rvm/rubies/ruby-2.2.1/bin/grunt:22:in `<main>'
	from /Users/HRK/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/HRK/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'

It used to work before, but now it just gives me these errors and I don’t know how to solve them.
If anyone could help out, please do!

**Comment by vladikoff** [comment]
Something from Ruby is overriding your `grunt` command, your PATH is not setup to pick up global node modules either `/Users/HRK/.node/bin/grunt -> /Users/HRK/.node/lib/node_modules/grunt-cli/bin/grunt`

This is a machine config issue and not a grunt bug.
