### ISSUE TITLE
[0.4.5] grunt.file.copy - process option destination path argument undefined

### ISSUE THREAD

**Issue by TvrtkoM** [gruntjs/grunt#1440]
Hello,

I have the following code in my grunt task:

    grunt.file.copy('node_modules/jquery/dist/jquery.min.js', 'vendor/jquery.min.js', {
      process: function(file, src, dest) {
        console.log(dest);
        return false;
      }
    });

line console.log(dest) outputs __'undefined'__ which is not according to API on http://gruntjs.com/api/grunt.file#grunt.file.copy

    // The source file contents, source file path, and destination file path 
    // are passed into this function, whose return value will be used as the
    // destination file's contents. If this function returns `false`, the file
    // copy will be aborted.
    process: processFunction,

**Comment by TvrtkoM** [comment]
I see this feature is not implemented in 0.4.5 (https://github.com/gruntjs/grunt/blob/v0.4.5/lib/grunt/file.js#L321)

Would be nice to have some kind of label indicating version inside API docs, or even better, possibility to switch documentation for specific grunt version. (e.g like https://docs.djangoproject.com/en/1.9/)

**Comment by vladikoff** [comment]
@JKAussieSkater ^

**Comment by JKAussieSkater** [comment]
Indeed, the feature has been implemented in a [later commit of Grunt](https://github.com/gruntjs/grunt/commit/2f0053f0db154f0911ff6498b4223d64dee3f76e?diff=split#diff-b86b3e259653eb32e213178c7c09cdde).

For the time being, the functionality works in the pre-release version of Grunt (or even in the latest release, if you believe "[_pr1170_author_head](https://github.com/gruntjs/grunt/releases/tag/_pr1170_author_head)" qualifies as a release).

I'll move this issue to `gruntjs/grunt-docs`, @gruntjs, could somebody close this issue?

**Comment by JKAussieSkater** [comment]
Thanks @dmethvin!
