### ISSUE TITLE
cli.js tests fail on Windows 7

### ISSUE THREAD

**Issue by gamtiq** [gruntjs/grunt#1442]
Hello,

I would like to make a contribution to grunt and have made steps described in [Contributing guide](http://gruntjs.com/contributing#modifying-grunt).
Unfortunately, tests for grunt/cli.js are failing on my system (Windows 7 64-bit SP1).
Below is output:
```
Running "nodeunit:all" (nodeunit) task
Testing cli_test.jsFFFF
>> cli - --debug taskname
>> Message: Options should parse correctly.
>> Error: {} deepEqual { debug: 1 }
>>   at E:\projects\github\grunt\test\grunt\cli_test.js:19:12
>>   at callDone (node_modules\grunt-legacy-util\index.js:159:5)
>>   at ChildProcess.<anonymous> (node_modules\grunt-legacy-util\index.js:198:5)
>>   at ChildProcess.emit (events.js:110:17)
>>   at maybeClose (child_process.js:1015:16)
>>   at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

>> cli - taskname --debug
>> Message: Options should parse correctly.
>> Error: {} deepEqual { debug: 1 }
>>   at E:\projects\github\grunt\test\grunt\cli_test.js:29:12
>>   at callDone (node_modules\grunt-legacy-util\index.js:159:5)
>>   at ChildProcess.<anonymous> (node_modules\grunt-legacy-util\index.js:198:5)
>>   at ChildProcess.emit (events.js:110:17)
>>   at maybeClose (child_process.js:1015:16)
>>   at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

>> cli - --debug --verbose
>> Message: Options should parse correctly.
>> Error: {} deepEqual { debug: 1, verbose: true }
>>   at E:\projects\github\grunt\test\grunt\cli_test.js:39:12
>>   at callDone (node_modules\grunt-legacy-util\index.js:159:5)
>>   at ChildProcess.<anonymous> (node_modules\grunt-legacy-util\index.js:198:5)
>>   at ChildProcess.emit (events.js:110:17)
>>   at maybeClose (child_process.js:1015:16)
>>   at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

>> cli - --verbose --debug
>> Message: Options should parse correctly.
>> Error: { verbose: true } deepEqual { debug: 1, verbose: true }
>>   at E:\projects\github\grunt\test\grunt\cli_test.js:49:12
>>   at callDone (node_modules\grunt-legacy-util\index.js:159:5)
>>   at ChildProcess.<anonymous> (node_modules\grunt-legacy-util\index.js:198:5)
>>   at ChildProcess.emit (events.js:110:17)
>>   at maybeClose (child_process.js:1015:16)
>>   at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
```

I run tests as a normal user (not an administrator).

**Comment by dmethvin** [comment]
Branch `master` seem to be working for me, Windows 10 with msysgit and cmder. Because Windows has problems with normal users creating symlinks I have to run as Administrator though. Here's the output I just got. 
![capture](https://cloud.githubusercontent.com/assets/157858/12869283/ed0a27ee-cce8-11e5-8b4a-2ec49b5d917e.PNG)

**Comment by gamtiq** [comment]
Actually 285f139 does not fix the problem.

**Comment by shama** [comment]
> I run tests as a normal user (not an administrator).

The tests use symlinks. Windows requires running as Administrator to create symlinks. You must run as Administrator to run the tests on Windows.

**Comment by dmethvin** [comment]
Running as admin just for that is a bit of a pain though. It would be handy if just one test group failed rather than aborting unit tests though. That way if you're doing unrelated stuff you'll just get one fail which you ignore during dev, and the message can explain you need to run as Administrator to get a complete pass. Would you accept a PR for that?

**Comment by shama** [comment]
@dmethvin Yep!
