### ISSUE TITLE
rc2

### ISSUE THREAD

**Issue by vladikoff** [gruntjs/grunt#1460]
- [x] ~~update https://github.com/gruntjs/grunt-legacy-log-utils~~ https://github.com/gruntjs/grunt-legacy-log-utils/commit/eead08d85339697038d1d0f5de584c06cc2dc730
  - [x] `grunt-legacy-log-utils` waiting on npm publish access
- [x] https://github.com/gruntjs/grunt/issues/1461 https://github.com/gruntjs/grunt-contrib-jasmine/commit/0eb7cf56029b59e4abb2fc52fd5148440bbde35e
- [x] https://github.com/gruntjs/grunt/pull/1464 Prevent `this.async()` from being called multiple times.
- [x] Update and publish new versions of `grunt-contrib-*` plugins
 - [x] https://github.com/gruntjs/grunt-contrib-clean/commit/af104010d9e35bc53635cd0bdec16791e009e530
 - [x] https://github.com/gruntjs/grunt-contrib-coffee/commit/1651944f36e8c4a838af99f025ac15b51537cc41
 - [x] https://github.com/gruntjs/grunt-contrib-compass/commit/8e17e75e4242a688cef594ac3e173394a1139104
  - [x] https://github.com/gruntjs/grunt-contrib-compress/commit/bef6a279d7d31dff34cc3807075d2365f36cbde9
  - [x] https://github.com/gruntjs/grunt-contrib-concat/commit/fb474ddfaf306077d3872c727d7f6b5abf4b13ce
  - [x] https://github.com/gruntjs/grunt-contrib-jshint/commit/cb10837839289eed8bc1cc32e655528a51cde072
  - [x] https://github.com/gruntjs/grunt-contrib-symlink/commit/9f243508f4863ef5cf7a544357d4967eecd54ed6
  - [x] https://github.com/gruntjs/grunt-contrib-watch/commit/d3d8c01b25e0c759d76b236313cf49963983cb77
- [x] Update license to jQuery Foundation https://github.com/gruntjs/grunt/commit/7e2c0653604f5d39a1eb89fc97f01144589a9ee5
- [x] create rc2 changelog

**Comment by JKAussieSkater** [comment]
rc2 already?! :open_mouth:

**Comment by vladikoff** [comment]
- [ ] need to go through all contrib plugins and publish new versions

**Comment by vladikoff** [comment]
Yes!

**Comment by kidwm** [comment]
@vladikoff rc2 changelog?

**Comment by vladikoff** [comment]
- [ ] to release https://github.com/gruntjs/grunt-contrib-connect once AppVeyor catches up with the testing

**Comment by vladikoff** [comment]
- [ ] https://github.com/gruntjs/grunt-contrib-watch

**Comment by vladikoff** [comment]
RC2 Changelog is here: https://github.com/gruntjs/grunt/pull/1485

**Comment by vladikoff** [comment]
Planning to have 1.0.0 instead of rc2 for end of next week.

**Comment by shama** [comment]
For reasons: Not many issues are being reported with the release candidates, so another rc doesn't seem necessary. Also peer deps fall apart on pre-release versions (so `>=0.4.0` wrongfully doesn't match `>=1.0.0-rc2`). So a smoother upgrade to avoid pre-release versions until peer dep requirement is removed completely.

**Comment by vladikoff** [comment]
v1.0 checklist moved to https://github.com/gruntjs/grunt/issues/1491
