### ISSUE TITLE
lodash warning:  grunt-legacy-log  /  grunt-legacy-log-utils

### ISSUE THREAD

**Issue by JKAussieSkater** [gruntjs/grunt#1463]
When installing grunt rc1, we still get a lodash deprecation warning (v2.4.1). Which is uncool.

Seems to be the `grunt-legacy-log` dependency, which calls upon the `grunt-legacy-log-utils` dependency.

`grunt-legacy-log-utils` is the cause, which has the `"lodash": "~2.4.1"` dependency.

## Possible courses of action
0. We create a special "rc1" version of `grunt-legacy-log-utils`, which has an updated lodash dependency
0. ~~We remove the `grunt-legacy-log-utils` dependency from the "rc1" version of `grunt-legacy-log`~~
0. ~~We remove `grunt-legacy-log` dependency from `grunt`~~
0. ~~We leave it as it is, ignoring the error~~

I don't understand the grunt backend yet, so I don't know what killing dependencies might do. But the word "legacy" makes me inclined to suggest we drop the deprecated dependencies.

----

_Edit: I can see option 1 has already been implemented, but the version # of the `package.json` hasn't been changed, and NPM isn't delivering the latest commits._

**Comment by JKAussieSkater** [comment]
I believe this could be resolved by changing:
* The version number of `grunt-legacy-log-utils`
* The `package.json` dependency of `grunt-legacy-log` to require the NEW version number for `grunt-legacy-log-utils`

And would properly resolve dot-point 1 of [this issue](https://github.com/gruntjs/grunt/issues/1460).

**Comment by shama** [comment]
Thanks! I have that fixed in this commit: https://github.com/gruntjs/grunt-legacy-log-utils/commit/eead08d85339697038d1d0f5de584c06cc2dc730 and will publish a new version of `grunt-legacy-log-util` and then update it up all the way to Grunt in `rc2`.
