### ISSUE TITLE
Grunt fails

### ISSUE THREAD

**Issue by robin-obrien** [gruntjs/grunt#1466]
Hi,

I am running Grunt for running tasks of CasperJS. No matter what I try it fails after around an 10 minutes, mostly with the following errors. These are usually the last messages I see when running grunt with the options "--verbose --debug --stack --force".
What might be the issue the hangs up the task?

```
[debug] [phantom] url changed to "https://www.somesite.com"
>> Exited with code: 1.
Warning: Task "exec:xyz" failed. Used --force, continuing.

Done, but with warnings. 
```
```
[debug] [phantom] opening url: www.somesite.com, HTTP GET
[debug] [phantom] Navigation requested: url=www.somesite.com, type=Other, willNavigate=true, isMainFrame=true
>> Exited with code: 1.
Warning: Task "exec:xyz" failed. Used --force, continuing.

Done, but with warnings.
```

When running without the option --force, I get the following trace:

```
Warning: Task "exec:xyz" failed. Use --force to continue.
Error: Task "exec:xyz1" failed.
    at Task.<anonymous> (project/node_modules/grunt/lib/util/task.js:205:15)
    at null._onTimeout (project/node_modules/grunt/lib/util/task.js:241:33)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by shama** [comment]
Is the task `exec:xyz` a real task? Or is this a modified example? It can be hard for others to help debug if it's not the actual failing Gruntfile/task as sometimes it could be a minor detail. Also I'm not familiar with the task you are using and how this is because of an issue with Grunt itself.

Closing as this behavior is working for me in Grunt and I'm fairly certain the result of a task failing.

**Comment by robin-obrien** [comment]
@shama  It is a task I've created 
grunt.loadNpmTasks("grunt-exec");
grunt.registerTask("xyz");
My node version is v4.3.1, grunt version grunt-cli: v0.1.13, grunt: v0.4.5, casperjs: 1.1.0-beta5

**Comment by shama** [comment]
`grunt.registerTask("xyz");` is invalid. It's registering a task that runs no other task or function.

Please see: http://gruntjs.com/getting-started#custom-tasks

**Comment by robin-obrien** [comment]
@shama, You are correct, I changed the names and removed some parts that seem to be less relevant. The code looks more like this.
Anyway the code runs, the thing is that it fails: at Timer.listOnTimeout (timers.js:92:15) 

  grunt.registerTask("xyz", "Running the xyz task", ["exec:xyz_job1","exec:xyz_job2"]);


```
grunt.initConfig({
    exec: {
      xyz_job1: "casperjs mycsaper.js --job=1",
      xyz_job2: "casperjs mycsaper.js --job-2"
  });
```

**Comment by robin-obrien** [comment]
@shama, Can you please reopen the issue, as "grunt.registerTask" is a valid API and the issue is not related to the invocation of the task

**Comment by shama** [comment]
@robin-obrien Please explain how this is an issue with `grunt.registerTask`?

**Comment by robin-obrien** [comment]
@shama, let's take a step back. I am running a task via grunt that works fine without grunt. When running with grunt it starts fine, but only after 5-10 minutes it fails, with the following stack trace. It seems as some timer is in some timeout. Please don't pay extra attention to the tasks names. 
```
Warning: Task "exec:xyz" failed. Use --force to continue.
Error: Task "exec:xyz" failed.
    at Task.<anonymous> (project/node_modules/grunt/lib/util/task.js:205:15)
    at null._onTimeout (project/node_modules/grunt/lib/util/task.js:241:33)
    at Timer.listOnTimeout (timers.js:92:15)
```

My node version is v4.3.1, grunt version grunt-cli: v0.1.13, grunt: v0.4.5, casperjs: 1.1.0-beta5
