### ISSUE TITLE
outdated glob version - upgrade to glob 7.0.0

### ISSUE THREAD

**Issue by mwittig** [gruntjs/grunt#1467]
Installing grunt@0.4.5 with nodejs 4.3.1 gives the following wanring:
```
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
``` 

Solution: Upgrade to glob@7.0.0 which no longer depends on graceful-fs

**Comment by atuttle** [comment]
For anyone out there that may still be running into this issue:

```
$ node --version
v6.1.0
$ npm --version
3.8.6
$ grunt --version
grunt-cli v1.2.0
grunt v1.0.1

$ grunt some-task
(node:46145) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
```

I resolved this by updating all of my grunt plugins: grunt-contrib-*, etc, to their latest versions.

**Comment by schmod** [comment]
Is there any chance we can get a Grunt 0.4.6 release that updates `glob` and `graceful-fs`, for those of us still waiting on the last few plugins to be made compatibile with 1.0.0?

**Comment by shama** [comment]
@schmod We can't publish breaking changes on a patch release, it would fix this warning but would likely break many users builds. Which plugins are you waiting on compatibility for? For most, updating is just a matter of changing the `peerDependencies` tag from `~0.4.0` to `>= 0.4.0`.
