### ISSUE TITLE
What's adding <style type="text/css">body { display: none !important }</style> in my <head> tag

### ISSUE THREAD

**Issue by Vulle** [gruntjs/grunt#1472]
**I followed these instructions for my app:**

https://github.com/yeoman/generator-angular#readme

**My Index** (before build)

```
  <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
  <!-- build:css(.) styles/vendor.css -->
  <!-- bower:css -->
  <link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.css" />
  <!-- endbower -->
  <!-- endbuild -->
  <!-- build:css(.tmp) styles/app.css -->
  <link href="app.less" type="text/css" rel="stylesheet/less">
  <!-- endbuild -->
```

**My dist Index** (in text-editor)

`<html ng-app="myApp"> <head> <meta charset="utf-8"> <title>Datavalidering</title> <meta name="description" content=""> <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"> <!-- Place favicon.ico and apple-touch-icon.png in the root directory --> <link rel="stylesheet" href="styles/vendor.2ac5f564.css"> <link rel="stylesheet" href="styles/app.d41d8cd9.css"> </head> <body>`

**Dist index** (browser)
```
<head>
<style type="text/css">@charset "UTF-8";[ng\:cloak],[ng-cloak],[data-ng-cloak],[x-ng-cloak],.ng-cloak,.x-ng-cloak,.ng-hide:not(.ng-hide-animate){display:none !important;}ng\:form{display:block;}.ng-animate-shim{visibility:hidden;}.ng-anchor{position:absolute;}</style>
 <meta charset="utf-8">
 <title></title> 
<meta name="description" content=""> 
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
 <link rel="stylesheet" href="styles/vendor.2ac5f564.css"> <link rel="stylesheet" href="styles/app.d41d8cd9.css"> 
<style type="text/css">body { display: none !important }</style></head>
<body>
```

**The problem may be in gruntfile.js**

http://plnkr.co/edit/r2hdhWY7olIw0pBHJ4VF?p=preview

Thank you in advance for your answers!

**Comment by shama** [comment]
This issue tracker is for issues with Grunt itself. I am also not familiar with that yeoman generator or angular so can't provide any help. You'll likely get better help asking questions on stackoverflow or the yeoman generator's issue tracker instead.
