### ISSUE TITLE
emm...path.join error again...

### ISSUE THREAD

**Issue by dtysky** [gruntjs/grunt#1473]
Environment：

OSX 10.10.5
Node 0.10.37
"grunt": "^0.4.5",
"grunt-contrib-clean": "^1.0.0",
"grunt-contrib-copy": "^0.8.2",
"grunt-contrib-uglify": "^0.11.0",
"grunt-open": "^0.2.3",
"grunt-webpack": "^1.0.11",

I used grunt and webpack for my project and all of them worked well, but after i reboot my Mac and run "grunt debug" again then this error was throwed:

>Task diectory "debug" not defined.

At last, i traced here and print the informations, then i found someting strenge:

Line 179 in "grunt/util/task.js"

> arguments: ["0" : "debug"]

What the reason of  this bug?

my Gruntfile:
`'use strict';

var mountFolder = function (connect, dir) {
    return connect.static(require('path').resolve(dir));
};

var webpackDistConfig = require('./webpack.dist.config.js'),
    webpackDevConfig = require('./webpack.config.js');

module.exports = function (grunt) {
    // Let *load-grunt-tasks* require everything
    require('load-grunt-tasks')(grunt);

    // Read configuration from package.json
    var pkgConfig = grunt.file.readJSON('package.json');

    grunt.initConfig({
        pkg: pkgConfig,

        webpack: {
            options: webpackDistConfig,
            dist: {
                cache: false
            }
        },

        'webpack-dev-server': {
            options: {
                hot: true,
                port: 8000,
                webpack: webpackDevConfig,
                publicPath: '/assets/',
                contentBase: './<%= pkg.src %>/',
                historyApiFallback: true
            },

            start: {
                keepAlive: true
            }
        },

        connect: {
            options: {
                port: 8000
            },

            dist: {
                options: {
                    keepalive: true,
                    middleware: function (connect) {
                        return [
                            mountFolder(connect, pkgConfig.dist)
                        ];
                    }
                }
            }
        },

        open: {
            options: {
                delay: 500
            },
            dev: {
                path: 'http://localhost:<%= connect.options.port %>/webpack-dev-server/'
            },
            dist: {
                path: 'http://localhost:<%= connect.options.port %>/'
            }
        },
        //
        //karma: {
        //    unit: {
        //        configFile: 'karma.conf.js'
        //    }
        //},

        copy: {
            dist: {
                files: [
                    // includes files within path
                    {
                        flatten: true,
                        expand: true,
                        src: ['<%= pkg.src %>/*'],
                        dest: '<%= pkg.dist %>/',
                        filter: 'isFile'
                    },
                    {
                        flatten: true,
                        expand: true,
                        src: ['<%= pkg.src %>/images/*'],
                        dest: '<%= pkg.dist %>/images/'
                    }
                ]
            }
        },

        clean: {
            dist: {
                files: [{
                    dot: true,
                    src: [
                        '<%= pkg.dist %>'
                    ]
                }]
            }
        }
    });

    grunt.registerTask('server', function (target) {
        if (target === 'dist') {
            return grunt.task.run(['build', 'open:dist', 'connect:dist']);
        }

        grunt.task.run([
            'open:dev',
            'webpack-dev-server'
        ]);
    });

    //grunt.registerTask('test', ['karma']);

    grunt.registerTask('debug', ['webpack-dev-server']);

    grunt.registerTask('build', ['clean', 'copy', 'webpack']);

    grunt.registerTask('default', []);
};
`

Thanks.

**Comment by shama** [comment]
Could you post the full stack trace (`grunt --stack`)?

**Comment by dtysky** [comment]
Hi
@shama 

Here is the stack:

![image](https://cloud.githubusercontent.com/assets/7337763/13360435/426305ec-dcf4-11e5-9224-10c663397021.png)

**Comment by shama** [comment]
`>> TypeError: undefined is not a function` seems to indicate you have a problem in your `debug` task which runs `webpack-dev-server`. I'm guessing something didn't get installed correctly and recommend `rm -rf node_modules && npm i`. Closing as this isn't an issue with Grunt but a task it is running.

**Comment by dtysky** [comment]
...I reboot my Mac again and all resolved...
