### ISSUE TITLE
Update copyright notices

### ISSUE THREAD

**Issue by dmethvin** [gruntjs/grunt#1478]
Although Grunt joined the Dojo Foundation a while back, the copyright notices were never updated from Ben's name. Before I submit a PR I wanted to see whether you really want so many notices here. Just a LICENSE file would be sufficient. Would it be okay to [remove all of these](https://github.com/gruntjs/grunt/search?utf8=%E2%9C%93&q=Copyright), rename LICENSE-MIT to LICENSE, and update the owner? Or does it make sense to keep some of them? That might be the case, for example, if files were distributed independently, but I am not sure if that applies for any of these.

**Comment by shama** [comment]
:+1: SGTM. Less to update each year too :)

**Comment by cowboy** [comment]
YES PLEASE <3
