### ISSUE TITLE
Grunt support company

### ISSUE THREAD

**Issue by jjcc1421** [gruntjs/grunt#1479]
Hello, do you have a grunt oficial company for support contact?
Good day.

**Comment by dmethvin** [comment]
What type of support are you looking for?

**Comment by jjcc1421** [comment]
Enterprise support.
In case that grunt fail or incompatibility bugs in updated or merge versions, and others. I am finding a contact for Somebody or some company to contact for support service.

**Comment by boazsender** [comment]
Hi @jjcc1421, 
We offer consulting and support services at @bocoup. You can email me at the address in my profile, or use https://bocoup.com/contact.
