### ISSUE TITLE
no local grunt installation possible with actual node and npm on windows 8.1

### ISSUE THREAD

**Issue by universalien** [gruntjs/grunt#1483]
local grunt installation with actual node 5.7.1 and npm 3.8.0 on windows 8.1 fails:

		npm install grunt --save-dev
		npm ERR! Windows_NT 6.3.9600
		npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\...\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "
		grunt" "--save-dev"
		npm ERR! node v5.7.1
		npm ERR! npm  v3.8.0
		npm ERR! code ENOSELF

		npm ERR! Refusing to install grunt as a dependency of itself
		npm ERR!
		npm ERR! If you need help, you may report this error at:
		npm ERR!     <https://github.com/npm/npm/issues>

		npm ERR! Please include the following file with any support request:
		npm ERR!     C:\...\grunt\npm-debug.log

**Comment by shama** [comment]
Please change the `name` in your `package.json` to something other then `"grunt"`. As that will cause npm to think it's installing a dependency of itself.
