### ISSUE TITLE
Grunt stopped working and not showing any error

### ISSUE THREAD

**Issue by hitesh5** [gruntjs/grunt#1484]
I am using grunt from past 3 months but from last 2 weeks my grunt is not working properly. Sometimes it works properly and sometime it will not work. Whenever I type grunt build then it just not work and also console does not show any error. I am very stucked and irritated by this behavior. What should I do?? Plz help me guyz.

FYI! I have to delete node_modules always and again install to make it run.

**Comment by shama** [comment]
Could you post your Gruntfile? What version of your OS, Node.js and npm you are using? Also what command are you using or what error are you seeing? Also try with `grunt --verbose` or `grunt --stack` to get more info.

/cc @vladikoff What do you think about adding an issue template with the above sorts of questions ^?

**Comment by vladikoff** [comment]
@shama yeah that would be good, for plugins it should probably be added as part of https://github.com/gruntjs/grunt-contrib-internal

**Comment by hitesh5** [comment]
Today my grunt again working as normal and not showing any error. I haven't do anything. Its just start again.
OS: Windows 8.1 Pro
Node.js: v0.12.3
npm: 2.9.1

May be its environment issue.

**Comment by hitesh5** [comment]
Thanks Shama for helping me out. Its the webfont issue. Now everything working fine.
