### ISSUE TITLE
Grunt fails with peerinvalid The package grunt does not satisfy its siblings' peerDependencies requirements!

### ISSUE THREAD

**Issue by paladox** [gruntjs/grunt#1488]
But the packages requested should not fail. See https://github.com/karma-runner/grunt-karma/issues/185

Also it fails like this 

19:34:30 npm WARN optional dep failed, continuing fsevents@1.0.8

19:34:58 npm ERR! peerinvalid The package grunt does not satisfy its siblings' peerDependencies requirements!
19:34:58 npm ERR! peerinvalid Peer grunt-contrib-copy@0.8.2 wants grunt@>=0.4.0
19:34:58 npm ERR! peerinvalid Peer grunt-contrib-jshint@1.0.0 wants grunt@>=0.4.0
19:34:58 npm ERR! peerinvalid Peer grunt-karma@0.12.1 wants grunt@0.4.x
19:34:58 

Im testing using grunt 1.0.0 which is in rc1. I doint know why it fails since your docs recommend doing this for migrating from grunt 0.4 to 1.x.

**Comment by paladox** [comment]
https://integration.wikimedia.org/ci/job/mediawiki-core-npm-node-4.3/312/console

**Comment by vladikoff** [comment]
npm issue they do not calculate `1.0.0-rc1` versions properly. We are going to be releasing 1.0.0 soon.

**Comment by paladox** [comment]
@vladikoff oh thanks.

**Comment by shahid1ansari** [comment]
im not able to run grunt dist successfully as it aborts saying task dist not found...... because of this my app is failing

**Comment by shahid1ansari** [comment]
im not able to run grunt dist successfully as it aborts saying task dist not found...... because of this my app is failing...can somebody help?

**Comment by shahid1ansari** [comment]
when I try run following just to solve grunt dist issue it results into same siblings peer dependencies error.
npm install  grunt-contrib-uglify
npm install  grunt-contrib-watch
npm install  grunt-contrib-concat
npm install  grunt-jshint

**Comment by blacksonic** [comment]
Same goes with stable version 1.0.1

**Comment by vladikoff** [comment]
@blacksonic what goes?

**Comment by blacksonic** [comment]
@vladikoff getting insane amount of peerinvalid errors

**Comment by vladikoff** [comment]
@blacksonic anywhere you see 

`19:34:58 npm ERR! peerinvalid Peer .... wants grunt@0.4.x`

it either must be something like:  `@>=0.4.x` or not have peerDeps.

Read: http://gruntjs.com/blog/2016-04-04-grunt-1.0.0-released#peer-dependencies

**Comment by shama** [comment]
Also if a lot of your dependencies haven't updated, you should use `grunt@0.4.5` until those plugins update.

Or `sudo npm i npm@3 -g` to install npm@3 which will only give you a warning on invalid peer deps and not halt the install.

**Comment by porjo** [comment]
I'm getting this on a package that already has the correct semver specified!?
```
npm ERR! peerinvalid The package grunt does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer grunt-karma@0.12.2 wants grunt@>=0.4.x
```

```
$ grunt -V
grunt-cli v1.2.0
grunt v1.0.1
```

**Comment by vladikoff** [comment]
@porjo npm lists almost everything that has a conflicting peerDeps set, so you need to take a look at the whole list and find a bad one.

**Comment by AdrianoCahete** [comment]
Fixed this problem updating package.js with `"grunt": ">=0.4.5 <1.0.0"`

**Comment by jared-cxz** [comment]
I got similar error when I run `grunt install` on Bamboo. By adding `"grunt": "~0.4.5"` into the dependencies section in package.json, it was fixed.

**Comment by distinctdan** [comment]
I was able to fix this by deleting my nodemodules folder. In my particular case, I had changed the package.json versions of about 8 packages, including grunt, all at the same time. The final state was valid, but it looks like npm tried to evaluate them 1 at a time, so it thought the siblings were still on the old versions.

**Comment by beetlerom** [comment]
In my case grunt wasn't explicitly mentioned as a dependency. Both @AdrianoCahete and @jared-cxz solutions worked. Thanks guys!
