### ISSUE TITLE
v1.0

### ISSUE THREAD

**Issue by vladikoff** [gruntjs/grunt#1491]
- [ ] Update to grunt-cli 1.0.0

**Comment by vladikoff** [comment]
@shama I did a bit of testing and I had an issue where the included `grunt-cli` in the `grunt` package did not add a runner into `.bin`. Have you seen that happen?

**Comment by niemyjski** [comment]
What's the status of this? When will 1.0 be released?

**Comment by richard-bt** [comment]
I'm seeing failures from a clean slate `npm install grunt` with the published 1.0.0 release that I think @vladikoff was seeing.

```
$ npm install grunt
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "grunt"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! path D:\REDACTED\node_modules\grunt\node_modules\grunt-cli\bin\grunt
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod 'D:\REDACTED\node_modules\grunt\node_modules\grunt-cli\bin\grunt'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     D:\REDACTED\npm-debug.log
```

**Comment by vladikoff** [comment]
@richard-bt you might need to clear your `node_modules` directory and reinstall. please try that

**Comment by shama** [comment]
@richard-bt Try `npm uninstall grunt-cli --save-dev && npm install grunt --save-dev`. It's no longer required to install `grunt-cli` locally for the `grunt` bin locally.

**Comment by blacksonic** [comment]
@vladikoff deleting ```node_modules``` doesnt help

**Comment by shama** [comment]
Try running `npm i grunt-cli gruntjs/grunt#fixbin` and let us know if that fixes the issue. We'll be getting out a patch release soon.
