### ISSUE TITLE
Clean up issues

### ISSUE THREAD

**Issue by sateffen** [gruntjs/grunt#1496]
Hey there,

I'm a huge fan of grunt, I use it for every project, so I'd like to contribute to this project, but there is like no way to contribute. The issues are still from 2014, the milestones are pointing to project versions, that most likely will never be reached (0.4.6, 0.4.7, 0.5.0 ?) - short: It's hard to decide, what's still relevant.

As far as I know grunt will "restart" with version 1.0.0, but I can't figure out what to actually do to help (due to the very old issues and questions).

It would be nice to clean up this old ballast. What do you think?

**Comment by shama** [comment]
Hi there!

We would really appreciate your help. I recommend starting with any topic that interests you personally. Some ideas are fixing a bug you hit often, contributing to the [documentation](https://github.com/gruntjs/grunt-docs) (maybe improvements to [our contributing page](http://gruntjs.com/contributing) with ways we could help new contributors?), the `grunt-contrib` projects need help too and usually have some good starter issues.

If you would like to propose more significant changes, feel free to open a PR on https://github.com/gruntjs/rfcs to solicit feedback from the team and community.

If you have any specific questions on an issue, feel free to mention the grunt team and we'll do our best to answer.

Thanks!
