### ISSUE TITLE
Installing grunt-processhtml package warns that grunt@~0.4.1 or grunt@^0.4.1 is not installed.

### ISSUE THREAD

**Issue by billyromano** [gruntjs/grunt#1501]
I'm having an issue installing the `grunt-processhtml` package and it's giving three warnings that it can't find grunt even though I have v1.0.0 installed.

Command:
```
npm i grunt-processhtml --save-dev
```

Result:
```
npm WARN grunt-release@0.13.0 requires a peer of grunt@^0.4.1 but none was installed.
npm WARN grunt-strip-code@0.1.2 requires a peer of grunt@~0.4.1 but none was installed.
npm WARN grunt-verbosity@0.2.2 requires a peer of grunt@~0.4.1 but none was installed.
```

Any ideas on how to fix this? Should I install both grunt v0.4.1 and v1.0.0 in my project?

**Comment by shama** [comment]
@billyromano It looks like those plugins haven't updated their `peerDependencies` to `>=0.4.0` yet. A way to fix it now, is keep installing `grunt@0.4.5` or `sudo npm i npm@latest -g` to update to `npm@3` which will no longer halt on peer dependencies but just give a warning.

Also please ping the authors on those packages to merge and publish:

https://github.com/geddski/grunt-release/pull/149 @geddski o/ hi!
https://github.com/nuzzio/grunt-strip-code @nuzzio
https://github.com/ericclemmons/grunt-verbosity/pull/8 @ericclemmons

**Comment by nuzzio** [comment]
Thanks for pointing this out @billyromano

**Comment by billyromano** [comment]
@shama I updated to the latest npm and realized that it was just giving a warning now and it does work for the time being. I appreciate your help and the quick response!

@nuzzio you're welcome! : )

Thanks peeps!
