### ISSUE TITLE
INSTALL: No compatible version found: grunt-legacy-log@~1.0.0

### ISSUE THREAD

**Issue by ihorskyi** [gruntjs/grunt#1504]
```$ npm i -g grunt```
```
npm ERR! Darwin 13.4.0
npm ERR! argv "/Users/ihorskyi/.nvm/versions/node/v4.2.2/bin/node" "/Users/ihorskyi/.nvm/versions/node/v4.2.2/bin/npm" "i" "-g" "grunt"
npm ERR! node v4.2.2
npm ERR! npm  v3.8.5

npm ERR! No compatible version found: grunt-legacy-log@~1.0.0
npm ERR! Valid install targets:
npm ERR! 0.1.3, 0.1.2, 0.1.1, 0.1.0
npm ERR! 
...
```

**Comment by vladikoff** [comment]
@shama that's weird ....

**Comment by vladikoff** [comment]
it's right there https://www.npmjs.com/package/grunt-legacy-log

**Comment by shama** [comment]
@ihorskyi Try `npm cache clean && npm i grunt`. Also I don't recommend installing `grunt` globally. If you want the `grunt` command, please `npm i grunt-cli -g`.

**Comment by shama** [comment]
Closing, please reopen if our instructions did not fix your issue.
