### ISSUE TITLE
npm ERR! peerinvalid The package grunt@1.0.1 does not satisfy its siblings' peerDependencies requirements!

### ISSUE THREAD

**Issue by gabramsua** [gruntjs/grunt#1506]
I have updated the package.json dependencies with npm check updates. Once done, I tried npm install -d and this insane errors appeared.

npm ERR! peerinvalid The package grunt@1.0.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer grunt-newer@1.1.2 wants grunt@>=0.4.1
npm ERR! peerinvalid Peer grunt-connect-proxy@0.2.0 wants grunt@~0.4.1
npm ERR! peerinvalid Peer grunt-autoprefixer@3.0.4 wants grunt@>=0.4.2
npm ERR! peerinvalid Peer grunt-contrib-concat@1.0.0 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-filerev@2.3.1 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-shell@1.2.1 wants grunt@>=0.4
npm ERR! peerinvalid Peer grunt-usemin@3.1.1 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-contrib-connect@1.0.1 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer load-grunt-tasks@3.5.0 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-contrib-clean@1.0.0 wants grunt@>= 0.4.5
npm ERR! peerinvalid Peer grunt-contrib-jshint@1.0.0 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-wiredep@3.0.1 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-svgmin@3.2.0 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-concurrent@2.3.0 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-contrib-compass@1.1.1 wants grunt@>= 0.4.5
npm ERR! peerinvalid Peer grunt-contrib-imagemin@1.0.0 wants grunt@>=0.4.0

npm ERR! Please include the following file with any support request:
npm ERR!     C:\xampp\htdocs\prangue\npm-debug.log

What´s the problem here? How can I resolve this issue? I really don´t know whats happening here...

**Comment by vladikoff** [comment]
> Update npm ERR! peerinvalid Peer grunt-connect-proxy@0.2.0 wants grunt@~0.4.1

http://gruntjs.com/blog/2016-04-04-grunt-1.0.0-released#peer-dependencies

update to latest  grunt-connect-proxy (or with one that has a grunt peerDep as >=0.4.x
