### ISSUE TITLE
Local Npm module "grunt-ng-ng_html2js" not found.

### ISSUE THREAD

**Issue by Ahmed0406** [gruntjs/grunt#1507]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'grunt-ng-ng_html2js',
1 verbose cli   '--save-dev' ]
2 info using npm@3.8.7
3 info using node@v5.10.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData grunt-ng-ng_html2js
8 silly fetchNamedPackageData grunt-ng-ng_html2js
9 silly mapToRegistry name grunt-ng-ng_html2js
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'grunt-ng-ng_html2js',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   name: 'grunt-ng-ng_html2js',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/grunt-ng-ng_html2js
14 verbose request uri https://registry.npmjs.org/grunt-ng-ng_html2js
15 verbose request no auth needed
16 info attempt registry request try #1 at 11:49:37 PM
17 verbose request id aee1949441601a24
18 http request GET https://registry.npmjs.org/grunt-ng-ng_html2js
19 http 404 https://registry.npmjs.org/grunt-ng-ng_html2js
20 verbose headers { 'content-type': 'application/json',
20 verbose headers   'cache-control': 'max-age=0',
20 verbose headers   'content-length': '2',
20 verbose headers   'accept-ranges': 'bytes',
20 verbose headers   date: 'Thu, 14 Apr 2016 21:49:38 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   age: '0',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-ams4124-AMS',
20 verbose headers   'x-cache': 'MISS',
20 verbose headers   'x-cache-hits': '0',
20 verbose headers   'x-timer': 'S1460670578.001257,VS0,VE96',
20 verbose headers   vary: 'Accept-Encoding' }
21 silly get cb [ 404,
21 silly get   { 'content-type': 'application/json',
21 silly get     'cache-control': 'max-age=0',
21 silly get     'content-length': '2',
21 silly get     'accept-ranges': 'bytes',
21 silly get     date: 'Thu, 14 Apr 2016 21:49:38 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     age: '0',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-ams4124-AMS',
21 silly get     'x-cache': 'MISS',
21 silly get     'x-cache-hits': '0',
21 silly get     'x-timer': 'S1460670578.001257,VS0,VE96',
21 silly get     vary: 'Accept-Encoding' } ]
22 silly fetchPackageMetaData Error: Registry returned 404 for GET on https://registry.npmjs.org/grunt-ng-ng_html2js
22 silly fetchPackageMetaData     at makeError (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
22 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:242:14)
22 silly fetchPackageMetaData     at Request._callback (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
22 silly fetchPackageMetaData     at Request.self.callback (/usr/lib/node_modules/npm/node_modules/request/request.js:200:22)
22 silly fetchPackageMetaData     at emitTwo (events.js:100:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:185:7)
22 silly fetchPackageMetaData     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1041:10)
22 silly fetchPackageMetaData     at emitOne (events.js:95:20)
22 silly fetchPackageMetaData     at Request.emit (events.js:182:7)
22 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:968:12)
22 silly fetchPackageMetaData  error for grunt-ng-ng_html2js { [Error: Registry returned 404 for GET on https://registry.npmjs.org/grunt-ng-ng_html2js] pkgid: 'grunt-ng-ng_html2js', statusCode: 404, code: 'E404' }
23 silly rollbackFailedOptional Starting
24 silly rollbackFailedOptional Finishing
25 silly runTopLevelLifecycles Starting
26 silly runTopLevelLifecycles Finishing
27 silly install printInstalled
28 verbose stack Error: Registry returned 404 for GET on https://registry.npmjs.org/grunt-ng-ng_html2js
28 verbose stack     at makeError (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
28 verbose stack     at CachingRegistryClient.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:242:14)
28 verbose stack     at Request._callback (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
28 verbose stack     at Request.self.callback (/usr/lib/node_modules/npm/node_modules/request/request.js:200:22)
28 verbose stack     at emitTwo (events.js:100:13)
28 verbose stack     at Request.emit (events.js:185:7)
28 verbose stack     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1041:10)
28 verbose stack     at emitOne (events.js:95:20)
28 verbose stack     at Request.emit (events.js:182:7)
28 verbose stack     at IncomingMessage.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:968:12)
29 verbose statusCode 404
30 verbose pkgid grunt-ng-ng_html2js
31 verbose cwd /home/ahmed/www-dev/ImmoB
32 error Linux 4.2.0-35-generic
33 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "grunt-ng-ng_html2js" "--save-dev"
34 error node v5.10.1
35 error npm  v3.8.7
36 error code E404
37 error 404 Registry returned 404 for GET on https://registry.npmjs.org/grunt-ng-ng_html2js
38 error 404
39 error 404 'grunt-ng-ng_html2js' is not in the npm registry.
40 error 404 You should bug the author to publish it (or use the name yourself!)
41 error 404 Note that you can also install from a
42 error 404 tarball, folder, http url, or git url.
43 verbose exit [ 1, true ]

**Comment by shama** [comment]
It looks like you're trying to install a package named `grunt-ng-ng_html2js` which does not exist in the npm registry:

> 37 error 404 Registry returned 404 for GET on https://registry.npmjs.org/grunt-ng-ng_html2js
