### ISSUE TITLE
Filenames are larger than is supported by the file system

### ISSUE THREAD

**Issue by cristian-sima** [gruntjs/grunt#1509]
Hi. I have Windows 10 Pro and I installed grunt

I want to re-install grunt so I deleted the folder, but I get this error:

![image](https://cloud.githubusercontent.com/assets/12199042/14642831/ad426c48-0654-11e6-928e-25c1b0b88b35.png)

The file tree:
![image](https://cloud.githubusercontent.com/assets/12199042/14642968/44fed4a4-0655-11e6-9ef6-b2fc51f7c785.png)

The only solution is to drag and drop the children folders to the parents, but this is very difficult. 

Any idea?

**Comment by vladikoff** [comment]
https://github.com/npm/npm/issues/3697

Try npm 3
