### ISSUE TITLE
Arguments to path.resolve must be strings Use --force to continue

### ISSUE THREAD

**Issue by GomesL** [gruntjs/grunt#1514]
While running the Gruntfile from eclipse, I got the following error. Yeoman also used.

> Running "newer:jshint:all" (newer) task
> 
> Running "jshint:all" (jshint) task Warning: Arguments to path.resolve must be strings Use --force to continue.
> 
> Aborted due to warnings.

* grunt-cli - v1.2.0
* grunt - v1.0.1
* node version - v0.10.42

Following is the Gruntfile content for jshint

> jshint: {
>         options: { 
>             jshintrc: '.jshintrc',
>             reporter: require('jshint-stylish')
>         },
>         all: [
>             'Gruntfile.js',
>             '<%= yeoman.app %>/scripts/{,*/}*.js',
>             '<%= yeoman.app %>/spssm/scripts/{,*/}*.js'
>         ],
>         test: {
>             options: {
>                 jshintrc: '../test/.jshintrc'
>             },
>             src: ['../test/spec/{,*/}*.js']
>         }
>     },
>

**Comment by shama** [comment]
Could you post the results from `grunt newer:jshint:all --stack`? That way we can see the stack trace and see where the error comes from.

**Comment by GomesL** [comment]
> Running "newer:jshint:all" (newer) task
> 
> Running "jshint:all" (jshint) task
> Warning: Arguments to path.resolve must be strings Use --force to continue.
> TypeError: Arguments to path.resolve must be strings
>   at Object.exports.resolve (path.js:313:15)
>   at Object.exports.selectReporter (/var/source_dir/src/main/webapp/WEB-INF/pages/config/node_modules/grunt-contrib-jshint/tasks/lib/jshint.js:62:31)
>   at Object.exports.lint (/var/source_dir/src/main/webapp/WEB-INF/pages/config/node_modules/grunt-contrib-jshint/tasks/lib/jshint.js:184:28)
>   at Object.<anonymous> (/var/source_dir/src/main/webapp/WEB-INF/pages/config/node_modules/grunt-contrib-jshint/tasks/jshint.js:47:12)
>   at Object.<anonymous> (/var/source_dir/src/main/webapp/WEB-INF/pages/config/node_modules/grunt/lib/grunt/task.js:255:15)
>   at Object.thisTask.fn (/var/source_dir/src/main/webapp/WEB-INF/pages/config/node_modules/grunt/lib/grunt/task.js:73:16)
>   at Object.<anonymous> (/var/source_dir/src/main/webapp/WEB-INF/pages/config/node_modules/grunt/lib/util/task.js:294:30)
>   at Task.runTaskFn (/var/source_dir/src/main/webapp/WEB-INF/pages/config/node_modules/grunt/lib/util/task.js:244:24)
>   at Task.<anonymous> (/var/source_dir/src/main/webapp/WEB-INF/pages/config/node_modules/grunt/lib/util/task.js:293:12)
>   at /var/source_dir/src/main/webapp/WEB-INF/pages/config/node_modules/grunt/lib/util/task.js:220:11
>   at process._tickCallback (node.js:448:13)
>   at Function.Module.runMain (module.js:499:11)
>   at startup (node.js:119:16)
>   at node.js:935:3
>

**Comment by GomesL** [comment]
Seems like when installing tern ide from eclipse, I installed few versions (both eclipse marketplace and install new software). When updating to 1.1.0 from 0.10.0, some components of tern wasn't updated to 1.1.0. By default those are not upgraded and had to set it upgrade once the installer loads the dependencies to install. Apart from that I add grunt and jquery for tern modules.
