### ISSUE TITLE
Hook up jquery-cla-checker to CI suite

### ISSUE THREAD

**Issue by vladikoff** [gruntjs/grunt#1518]
Need to add this, just like https://github.com/theintern/intern/pull/632#issuecomment-219216902

**Comment by vladikoff** [comment]
@XhmikosR @shama Hm I wonder if this should be part of the grunt-contrib-internal somehow...

**Comment by XhmikosR** [comment]
I'm not sure how we can add that to internal to be honest.

Can't we add that per GitHub project?

**Comment by shama** [comment]
@vladikoff Could @dmethvin help point us to someone who could set that up for us?

**Comment by Arkni** [comment]
`jquerybot` is an instance of https://github.com/jquery/jquery-license. Maybe you could try to open an issue in their tracker.

> Can't we add that per GitHub project?

You can add it to the org too, as per jquery/jquery-license#68

**Comment by dmethvin** [comment]
Yep, we can add jquerybot at the Gruntjs org level, that's probably easiest. I'll get that going this weekend.

**Comment by dmethvin** [comment]
Should be working now, see #1519. New PRs or commits on old PRs will be checked to see if the committer(s) have signed the CLA. The names and emails on the commits vs signatures must match.

**Comment by vladikoff** [comment]
awww yissss 😃
