### ISSUE TITLE
Error: Cannot find module 'block-stream'

### ISSUE THREAD

**Issue by fantiq** [gruntjs/grunt#1521]
npm 3.8.9
node 6.2.0
grunt 1.0.1
grunt-cli v1.2.0

the full error
```
(node:5960) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:5960) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Loading "bower.js" tasks...ERROR
>> Error: Cannot find module 'block-stream'
Warning: Task "bower:dev" not found. Use --force to continue.
```

help me !!

**Comment by shama** [comment]
`grunt` doesn't use `block-stream` in its dependency tree. I recommend looking into which modules you're using to run the "bower.js" task and report to their issue tracker. But my guess is npm failed to install a module and you'll just need to try again.
