### ISSUE TITLE
Issue with npm for version 2.14.1

### ISSUE THREAD

**Issue by aatifbandey** [gruntjs/grunt#1522]
I am using windows machine and i have installed node and when i check node js version
it shows - v0.10.0 and npm version - v.1.2.14 but when i want to install grunt it shows compatibility version issue, how can i upgrade my npm version to 2.14.1

i have tried
`npm install npm@latest -g`

but it throws an error related to filter method.

**Comment by shama** [comment]
Were you able to successfully update to npm 2.14.1? You can run `npm -v` to get the version.

Could you paste the error you are getting? Also unless there is a specific reason you're on node `v0.10`, I highly recommend upgrading to at least `v4.4.5`.

**Comment by aatifbandey** [comment]
it requires a version of node >=4

**Comment by shama** [comment]
Grunt doesn't require node >= 4, it is just recommended.
