### ISSUE TITLE
Load grunt task from sub folder inside node_modules folder

### ISSUE THREAD

**Issue by terenc3** [gruntjs/grunt#1523]
I'de like to load grunt task from a dedicated module which contains my global grunt config. But at the moment the tasks can only be loaded from project/node_modules.

My Target is the following:
__structure__
```
project/
    Gruntfile.js
    node_modules/
        grunt-config-widgets/
            index.js
            node_modules/
                grunt-contrib-clean
```

__Gruntfile.js__
```
module.exports = function(grunt) {
    require('grunt-config-widgets')(grunt);
};
```

__index.js__
```
module.exports = function(grunt) {
    var gruntConfig = {
        clean: ['foo', 'bar']
    };

    grunt.initConfig(gruntConfig);

    // the loadNpmTasks should be accepting am aditional parameter so tasks can be searched inside a node_module
    grunt.loadNpmTasks('grunt-contrib-clean', __dirname);

    grunt.registerTask('default', ['clean']);
}
```

**Comment by shama** [comment]
Currently all tasks are loaded into a shared global space. If we provide an API for 3rd party modules to load tasks from their own node_modules, it will create conflicts for end users.

For instance `grunt-config-widgets` may use `clean@1.0.0` while my Gruntfile also uses `clean@2.0.0`, which clean task wins?

So I'd rather not alter this API but instead move to standalone tasks. Basically enable tasks to be ran independently, so if a 3rd party module depends on other tasks, it just `require()`s them and uses as needed. This way the task global space always belongs to the end user.

This will require a [rfc](https://github.com/gruntjs/rfcs) but I haven't gotten around to finish writing it yet.

**Comment by terenc3** [comment]
Thank you for your comment. I agree, that this can lead to issues, but i had an all or nothing approach in mind. So that the proect specific Gruntfile only includes what i have shown earlier and also all grunt depdencies (besides "grunt") should be in the grunt-config-widgets module. I try if i can find another solution which requires no changes in grunt.

**Comment by terenc3** [comment]
It's a shame i didn't find this method earlier. I can set a different base in my grunt-config-widgets module before loading the tasks. Works perfectly in my test, so i renameing this issue and close it.

__index.js__
```
module.exports = function(grunt) {
    var gruntConfig = {
        clean: ['foo', 'bar']
    };

    grunt.initConfig(gruntConfig);

    // the loadNpmTasks should be accepting am aditional parameter so tasks can be searched inside a node_module

    var cwd = process.cwd();

    grunt.file.setBase(__dirname);
    grunt.loadNpmTasks('grunt-contrib-clean');
    grunt.file.setBase(cwd);

    grunt.registerTask('default', ['clean']);
}
```
