### ISSUE TITLE
Installing grunt dependencies globally 

### ISSUE THREAD

**Issue by tailhook** [gruntjs/grunt#1525]
First, thing to mention that yes I'm aware of #438, but it's 2016 now, and something has changed.

So I want to open this topic again because we want to install `grunt`, `grunt-cli` and all of its dependencies and all of the project dependencies into the **container**. From the npm point of view it's `npm install --global` but without any consequences that we have with global installation.

Currently, we need either to mount `node_modules` from the project dir into `/usr/lib/node_modules` or visa-versa: or mount Gruntfile and sources into the bad place like `/usr/lib/Gruntfile`. Both solutions are ugly. 

In case it's not clear, when I'm speaking of containers, I'm talking about docker or similar containers (vagga) where we mount project dir into docker container but use every other dependency from container itself (like this `docker --volume=/work:$(pwd)`)

So what stops us to fix it now? Global dependencies doesn't have to work by default, some configuration like environment variable `GRUNT_DEPENDENCIES=/usr/lib/node_modules` or a command-line flag may be used for that.

**Comment by vladikoff** [comment]
We are not planning to support the global dependency use case. Even though it's been several years, npm still works the same way. However **we will review a pull request** that would somehow make it easier to work with this stuff. Personally I suggest keeping the node_modules the way they are everywhere to avoid confusing your own developers. (Maybe take a look at how other Docker projects deal with node_modules?)

**Comment by tailhook** [comment]
@vladikoff okay, we can do a pull request. Where can we discuss the aproach? Shouldn't we leave this issue open discussing it? Is the environment variable proposed above fine enough for pull request?

**Comment by AlexMost** [comment]
I have achieved what I wanted in simple 2 line fixes. One in grunt-cli (to prevent failure with 'Unable to find local grunt.')

*file - grunt-cli/bin/grunt*

```javascript
try {
  gruntpath = resolve('grunt', {basedir: process.env.GRUNT_NODE_MODULES_PATH || basedir});
}
..
```
And another one in grunt repo
*file - grunt/lib/grunt/task.js*

```javascript
task.loadNpmTasks = function(name) {
  loadTasksMessage('"' + name + '" local Npm module');
  var root = path.resolve(process.env.GRUNT_NODE_MODULES_PATH || '', 'node_modules');
....
```
and I was able to launch build without node_modules dir near the Gruntfile.

The question is how should I implement this changes properly? Maybe it is worth placing this configuration somewhere inside grunt-known-options repository?

What do you think @vladikoff ?
