### ISSUE TITLE
Grunt Build fails at "bowerInstall:app"

### ISSUE THREAD

**Issue by mju516** [gruntjs/grunt#1529]
First, I would like to apologize in advance. I am not particularly skilled when it comes to Grunt. I am attempting to install an angular theme in Visual Studio, and have been learning Grunt, NPM, and Bower on the fly.

I've been able to successfully _bower install_ and _npm install_ the files in my project, and am now attempting to run _grunt build_. When I do, I am getting the following output:

`Running "bowerInstall:app (bowerInstall) task
Warning: Cannot read property 'main' of undefined Use --force to continue.

Aborted due to warnings."`

From my gruntfile.js:

<hr>
`
grunt.initConfig({

    // Project settings
    yeoman: {
      // configurable paths
      app: require('./bower.json').appPath || 'app',
      dist: 'dist'
    },

    // Watches files for changes and runs tasks based on the changed files
    watch: {
      bower: {
        files: ['bower.json'],
        tasks: ['bowerInstall']
      },
`
<hr>

and later in the file: 
<hr>
`bowerInstall: {
      app: {
        src: ['<%= yeoman.app %>/index.html'],
        ignorePath: '<%= yeoman.app %>/',

        // we're not going to inject these as they're lazyloaded

        exclude: ['requirejs',
                  'mocha',
                  'jquery.vmap.europe.js',
                  'jquery.vmap.usa.js',
                  'Chart.min.js',
                  'raphael',
                  'morris',
                  'jquery.inputmask',
                  'jquery.validate.js',
                  'jquery.stepy.js',
                  'fullcalendar.js'
                  ]
      }
    },`
<hr>

I've seen a couple of similar StackOverflow questions, where re-running _bower install_ fixed their issues, but that doesn't seem to be it. If anyone has ideas for what I may be missing, I appreciate all the help that I can get.

**Comment by shama** [comment]
> Warning: Cannot read property 'main' of undefined Use --force to continue.

Means the JS somewhere is trying to read a property `main` of something that is `undefined`. Such as `variableThatTotallyHasNotBeenDefined.main`.

You can try running `grunt --stack` to get a stack trace on where the error is coming from. Unfortunately I'm not familiar enough with the specific tasks you're using to provide further help.
