### ISSUE TITLE
Deleting a dependency caused problems

### ISSUE THREAD

**Issue by smajazayeri** [gruntjs/grunt#1532]
I installed webpack-dev-server first using npm. After a short while, I uninstalled it as I didn't benefit enough from that lib.
`npm uninstall --save webpack-dev-server`
Now, whenever I run my grunt tasks, I receive this error in my console:
`Loading "webpack-dev-server.js" tasks...ERROR
Error: Cannot find module 'webpack-dev-server'`

Would you please help me to get rid of this nasty error in my console?...

**Comment by shama** [comment]
This question would be better served on [webpack-dev-server's](https://github.com/webpack/webpack-dev-server) issue board as that error isn't related to Grunt. It sounds like you have a task trying to require that dependency you removed.
