### ISSUE TITLE
Replace jshint+jscs with eslint

### ISSUE THREAD

**Issue by markelog** [gruntjs/grunt#1533]
JSCS is now [unmaintained](http://eslint.org/blog/2016/07/jscs-end-of-life), in order to provide full compatibility with ESLint, ESLint team [identifying](https://github.com/eslint/eslint/issues/5858) most popular JSCS presets and providing for them ESLint replacement.

Grunt config is one of them, sharable config for it is now published - https://github.com/markelog/eslint-config-grunt

Would you like to switch to it?

**Comment by vladikoff** [comment]
Thanks for the issue! @shama what are your thoughts on this?

**Comment by shama** [comment]
SGTM!

**Comment by markelog** [comment]
Okay, cool, will try to send PR soon
