### ISSUE TITLE
Met "UNMET PEER DEPENDENCY grunt@1.0.1" error

### ISSUE THREAD

**Issue by MathRobin** [gruntjs/grunt#1537]
Hi !

I have a problem with installing grunt via "npm i". I have tried with 0.4.5 too, but same error. Any idea about what happening ?

For helping, these are my dependencies : 

      "dependencies": {
        "arrify": "1.0.1",
        "as-jqplot": "1.0.8",
        "babel-runtime": "6.9.2",
        "bootstrap": "3.3.6",
        "bootstrap-slider": "9.1.1",
        "chart.js": "1.0.2",
        "chunk": "0.0.2",
        "clone": "1.0.2",
        "co": "4.6.0",
        "co-body": "4.2.0",
        "co-pg": "2.0.0",
        "expect": "1.20.2",
        "font-awesome": "4.6.3",
        "github": "2.2.0",
        "grunt": "1.0.1",
        "grunt-babel": "6.0.0",
        "grunt-bump": "0.8.0",
        "grunt-cli": "1.2.0",
        "grunt-contrib-concat": "1.0.1",
        "grunt-contrib-copy": "1.0.0",
        "grunt-contrib-imagemin": "1.0.1",
        "grunt-contrib-less": "1.3.0",
        "grunt-contrib-uglify": "2.0.0",
        "grunt-contrib-watch": "1.0.0",
        "grunt-eslint": "19.0.0",
        "grunt-jsonlint": "1.1.0",
        "grunt-plato": "1.2.1",
        "grunt-shell": "1.3.0",
        "jquery": "3.1.0",
        "koa": "1.2.1",
        "koa-bodyparser": "2.2.0",
        "koa-compress": "1.0.9",
        "koa-cors": "0.0.16",
        "koa-jade": "2.1.0",
        "koa-logger": "1.3.0",
        "koa-router": "5.4.0",
        "koa-sql-select": "1.1.1",
        "koa-static-folder": "0.1.6",
        "koa-useragent": "0.1.4",
        "load-grunt-tasks": "3.5.0",
        "mandrill-api": "1.0.45",
        "md5": "2.1.0",
        "moment": "2.14.1",
        "nconf": "0.8.4",
        "node-noop": "1.0.0",
        "node-persist": "0.0.11",
        "nodemon": "1.9.2",
        "pg": "6.0.3",
        "platform": "1.3.1",
        "plato": "1.6.0",
        "throng": "4.0.0",
        "time-grunt": "1.4.0",
        "typeahead.js": "0.11.1",
        "validator": "5.5.0"
      },
      "devDependencies": {
        "grunt-aws": "0.6.2"
      }

Even there is the error, grunt is installed. But this error made continuous intgration and deployment on heroku failing.

**Comment by MathRobin** [comment]
I forgot to precise that even there is the error, grunt is installed. But this error made continuous intgration and deployment on heroku failing.

**Comment by shama** [comment]
It's likely because one of the grunt plugins has `"grunt": "~0.4.5"` or some other bad peer dependency definition in their `package.json`. We've advised all plugins to update to `>=0.4.5` (or remove) their peer dependency definition to avoid this.

They plugin author may have already updated their plugin in which case `rm -rf node_modules && npm cache clean && npm i` might fix it.

If not, look into which grunt plugin has grunt listed as a peer dependency. If it's `~0.4.5` or similar, it's likely incorrect. I would open an issue on their tracker and ask them to remove the peerDependency definition to grunt.

**Comment by MathRobin** [comment]
Hey, ok thanks, fount it : https://github.com/mazerte/grunt-jscpd/

Have a nice day :)
