### ISSUE TITLE
Arrays and objects in templates

### ISSUE THREAD

**Issue by ArmorDarks** [gruntjs/grunt#1541]
Hi

There seems to be a bit of oddity with arrays and objects, which are declared within lodash templates.

Consider this:

``` coffee
grunt.initConfig
  array:
    test:     '<%= ["value1", "value2"] %>'
    expected: ["value1", "value2"]

  object:
    test:     '<%= {test: "value"} %>'
    expected: {test: "value"}

# array test
console.log('test:     ', grunt.config('array.test'))
console.log('expected: ', grunt.config('array.expected'))

# object test
console.log('test:     ', grunt.config('object.test'))
console.log('expected: ', grunt.config('object.expected'))
```

I think most people would expect to see in log following:

```
test:      [ 'value1', 'value2' ]
expected:  [ 'value1', 'value2' ]

test:      { test: 'value' }
expected:  { test: 'value' }
```

but instead you will see this:

```
test:      value1,value2
expected:  [ 'value1', 'value2' ]

test:      [object Object]
expected:  { test: 'value' }
```

As you can see, test case has been stringified by lodash template. This should be expected behavior, because lodash templates always returning string.

However, in Grunt it's not uncommon when you for one or another reason need to pass via template exactly array or maybe an object, and it seems like perfectly valid case.

The only workaround is setting via `grunt.config.set()` which always preserving type of input. But in some configs it might be not as elegant, as using of templates.

So, I wonder, is there any way to force templates not to stringify result?

**Comment by shama** [comment]
Just use JavaScript instead of lodash templates:

```coffee
grunt.initConfig
  array:
    test: ["value1", "value2"]
  object:
    test: {test: "value"}
```

**Comment by ArmorDarks** [comment]
I guess my example wasn't perfectly clear, because I simplified it to illustrate potential issue.

Here is more relevant one:

``` coffee
grunt.initConfig
  array:
    test:     '<%= array.expected %>'
    expected: ["value1", "value2"]

  object:
    test:     '<%= object.expected %>'
    expected: {test: "value"}
```

Will yield:

```
test:      value1,value2
expected:  [ 'value1', 'value2' ]

test:      [object Object]
expected:  { test: 'value' }
```

As I've said in my first post, you might need it to pass properties of init config into other properties of same config during initialization.

**Comment by UncleM** [comment]
close
