### ISSUE TITLE
failing grunt serve due to plugin for clean

### ISSUE THREAD

**Issue by masoud-moghini** [gruntjs/grunt#1542]
hi
I'm gonna get start client-side application development using angular js and conforming to [Professional Angular.js](http://www.wrox.com/WileyCDA/WroxTitle/Professional-AngularJS.productCd-1118832078.html)and conforming its approach in getting use of Yeoman followed steps of launching a project.in one of the elementary steps we must configure application general skeleton using the following command:
`grunt serve`
but when running the following commands on terminal is displayed 
```
jit-grunt: Plugin for the "clean" task not found.
If you have installed the plugin already, please setting the static mapping.
See https://github.com/shootaroo/jit-grunt#static-mappings

Warning: Task "clean:server" failed. Use --force to continue.

Aborted due to warnings.
```

```
Execution Time (2016-08-10 21:02:56 UTC+4:30)
loading tasks  142ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 95%
serve            7ms  ▇▇▇ 5%
Total 150ms
and execution is terminated.
```
I really what have to do?

**Comment by shama** [comment]
It looks like that message is coming from [jit-grunt](https://www.npmjs.com/package/jit-grunt). I'm not familiar with jit-grunt so unfortunately cannot help you. I recommend trying their issue tracker or stackoverflow.
