### ISSUE TITLE
'grunt' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by AmitAKB** [gruntjs/grunt#1550]
Hello Team,

I am using window-7 OS. I have already install grunt globally, but I tried to start grunt then ## 'grunt' is not recognized as an internal or external command" error message shows.
I'm follow the below step:

install cmd: npm install -g grunt
                   npm install -g grunt-cli
Grunt install on this path: Users\user_name\AppData\Roaming\npm\node_modules\grunt-cli

Install successfuly completed but when I'm typing the grunt then shows the above error message.

Please suggest me what is the wrong?

Regards & Thanks,
Amit

**Comment by shama** [comment]
You don't need to install `grunt` globally (`npm uninstall grunt -g`). Only `npm i grunt-cli -g` to get the `grunt` command.

Ensure that your `PATH` is set correctly: `SET PATH=C:\Program Files\Nodejs;%PATH%` to recognize npm installed commands.

http://gruntjs.com/getting-started

**Comment by AmitAKB** [comment]
Thanks for reply!

I'm follow the same steps mention on this site (http://gruntjs.com/getting-started).
But again showing as a same error message.

**Comment by javafun** [comment]
I am currently experiencing the same issue and wondering how did you resolve this issue.

**Comment by praneethjonna** [comment]
type echo %path% in the command prompt. Check if you find this path there "C:\Users\<username>\AppData\Roaming\npm". If you have already added this path to path variable then you need move this path to starting of string.

**Comment by JETWLL** [comment]
I am currently experiencing the same issue as well when using 'Cmder', while 'Cmd' is normal.

**Comment by FlavorScape** [comment]
same issue. tried all kinds of path tricks, changed the tc user, rebooted, re-installed as admin. even put npm install -g grunt and npp install -g grunt-cli in the build steps.

**Comment by tHand** [comment]
Try re-installing or repairing node.js. This worked for me on Windows 10 while all the other suggestions did not.

**Comment by heenathk18** [comment]
> Try re-installing or repairing node.js. This worked for me on Windows 10 while all the other suggestions did not.

Thanks ! works for me on Window 10

**Comment by lakshyamcs16** [comment]
@praneethjonna Adding the path to env. variables worked! Thanks!

**Comment by Chelo19** [comment]
For me, the solution was to downgrade my node version after installing the grunt cli and checking the env path. I was trying with 20.12.2 but i had to downgrade to 18.20.2 at least.
