### ISSUE TITLE
What is new, in a conceptual point of view, for grunt 1.0+  

### ISSUE THREAD

**Issue by xtianus79** [gruntjs/grunt#1552]
I get the differences between Gulp and Grunt but in reality what has changed for Grunt 1.0.  Sell me on it.

**Comment by cowboy** [comment]
@xtianus79 Grunt 1.0 leverages the power and synergy of semantic versioning to move the 0 from the left side of the dot to the right side, resulting in a sustainable paradigm shift in customer satisfaction

**Comment by leobalter** [comment]
@xtianus79 selling you Grunt is not the most important part here - you can actually fork it for free - [semver](http://semver.org/) is the answer @cowboy is referring to.

You should take a look on it, specially the [item 4](http://semver.org/#spec-item-4):

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

That means the team behind Grunt is setting a goal to follow updates using semver format and users can expect some quality time knowing what kinds of update you'll get on any new version.

In terms of using Gulp or Grunt, that's your decision and I'll respect that, both are ok.
