### ISSUE TITLE
Glob security warning.

### ISSUE THREAD

**Issue by misterdai** [gruntjs/grunt#1557]
Grunt is using Glob `~7.0.0`.  Suggest that it be set at a minimum of `~7.0.5` which contains patched version of `minimatch`.

https://nodesecurity.io/advisories/118

```
warning grunt > glob > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```

**Comment by michael-fei** [comment]
I'm getting the same warning. Please update this ASAP to avoid the RegExp DoS issue mentioned in the warning message.

**Comment by shama** [comment]
Since we have the glob dependency tagged at `~7.0.0` (notice the tilde), npm will download the latest patch version.

If you're hitting this warning, please `npm cache clean && npm install` to get the latest dependency tree.
