### ISSUE TITLE
grunt is not recognized as an internal or external command

### ISSUE THREAD

**Issue by Bikhtashi** [gruntjs/grunt#1569]
**Hi guys,**
 I really need help with Grunt installation on windows 7.
I have node v6.9.2 installed and npm v3.10.9
The steps I followed.
1. `install npm install -g grunt-cli` 
2. I create package.json with `npm init`  on my project directory
3. npm install grunt --save-dev`
4.  I add configuration to Gruntfile.js
5. `npm install `
5. `npm install grunt-contrib-uglify --save-dev` 
finally I run `grunt` 
grunt is not recognized as an internal or external command
I changed the User vaiables to
C:\Users\MUB\AppData\Roaming\npm

**Comment by bhldev** [comment]
echo %PATH% , see if "grunt" is located in any of the paths
See http://stackoverflow.com/a/9588052

**Comment by mawa1** [comment]
@Bikhtashi  Your problem helped me solve mine. Cheers!
