### ISSUE TITLE
Please allow by option to run globally grunt

### ISSUE THREAD

**Issue by bastien-roucaries** [gruntjs/grunt#1573]
Hi,

For distribution like debian it is not possible to run from build daemon grunt locally. 

therefore could be possible to add a mode that allow (with option passing) to run grunt globally.

A grunt cli --global-i-know-what-i-am-doing will be fine.

Thank you

**Comment by vladikoff** [comment]
Sorry, there are no plans to do that because that goes against how `node_modules` are structured and how NPM works. The best solution is to fix the Debian configuration to handle that. Sorry about that!
