### ISSUE TITLE
Documentation for absolute beginner

### ISSUE THREAD

**Issue by MandarSant** [gruntjs/grunt#1575]
The documentation of gruntjs  should be created in considering who doesn't know js or node js so that the one like me who is pashionate to learn.

**Comment by shama** [comment]
There is always going to be some level of previous required knowledge. I don't think the Grunt website needs to teach JS and Node.js as there are other better resources for that.

But if you have any more specific ideas on how to improve the documentation for beginners, feel free to suggest those ideas here: https://github.com/gruntjs/gruntjs.com/issues
