### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by josepmc** [gruntjs/grunt#1579]
I'm asking myself why doesn't grunt support loading of TypeScript files when it does support CoffeeScript.
Before submitting any PR I'd like to enquiry into this topic (perhaps there was already some decision made on this topic/whatsoever).
The lines needed to change are:
- Add `require('ts-node/register');` in grunt.js:8
- Modify task.js:351 to `var files = grunt.file.glob.sync('*.{ts,js,coffee}', {cwd: tasksdir, maxDepth: 1});`

Ideally, though, loadTasks would just accept a glob pattern which would allow for extra languages/customization.

**Comment by shama** [comment]
Please see https://github.com/gruntjs/rfcs/blob/master/text/0001-liftoff.md

**Comment by josepmc** [comment]
For the record, should anyone want to have support while liftoff hasn't been implemented:
`
    require('ts-node/register');
    for (const file of grunt.file.glob.sync('*.ts', {cwd: 'Path where the tasks are located', maxDepth: 1, realpath: true})) {
        require(file)(grunt);
    }`
