### ISSUE TITLE
teardown

### ISSUE THREAD

**Issue by patrikx3** [gruntjs/grunt#1587]
Hi!

How are you?

Do you know to use a teardown event or function? Can't find it. It says events are my own, how can I execute a post task teardown function?

Thanks so much!

**Comment by shama** [comment]
There isn't an event for teardown but you can create a task for it:

```js
grunt.registerTask('teardown', function () {
  /* Do tear down things */
});

grunt.registerTask('default', ['first', 'second', 'teardown']);
```
