### ISSUE TITLE
loadNpmTasks doesn't find ancestor node_modules

### ISSUE THREAD

**Issue by richburdon** [gruntjs/grunt#1599]
I'm using `lerna` which "hoists" npm packages into a root directory's node_modules.

AFAIK, node is supposed to iteratively search each ancestor directory for node_modules, but `grunt.loadNpmTasks` doesn't seem to do that, so I get errors, e.g.,

Local Npm module "grunt-contrib-clean" not found. Is it installed?

Is grunt doing something special (different from require)? Is there a way to configure it?

**Comment by shama** [comment]
This has been asked [a number of times](https://github.com/gruntjs/grunt/search?p=2&q=loadNpmTasks&type=Issues&utf8=%E2%9C%93). Basically `grunt.loadNpmTasks` only loads modules `node_modules/` folder relative to the Gruntfile and above.

Please see this comment about a way to RFC a new API to load using a `require` based approach: https://github.com/gruntjs/grunt/issues/1523#issuecomment-229517873
