### ISSUE TITLE
Detect whether Grunt has run once

### ISSUE THREAD

**Issue by ArmorDarks** [gruntjs/grunt#1600]
I wonder, is there any way to detect when Grunt has run once?

In docs said that Grunt supports adding events, but doesn't emit any events itself. That's quite unfortunate, since it could help this issue.

Just to be more clear, I need to start another emitter, but it should happen only once, during init of Grunt. Right now any edits will invoke Grunt again via `grunt-contrib-watch`, thus reinitializing emitter too.

I know that I can store value that it already had run once somewhere else in cache, but it would be much better to avoid disk operations. And right now there seems to be no way to store any persistent data in-memory.

**Comment by shama** [comment]
This is because `grunt-contrib-watch` by default runs tasks in a new process. You can set [`spawn: false`](https://github.com/gruntjs/grunt-contrib-watch#optionsspawn) to have it run tasks in the same process.

**Comment by ArmorDarks** [comment]
Thanks for reply!

Yes, I know that is launches it in a new process, and `spawn: false` in some cases can be undesired. I had to clarify that in my first post — is it possible somehow to overcome this issue without specifying `spawn: false` or relying on disk operations? Maybe I'm missing something obvious?

**Comment by ArmorDarks** [comment]
Just a reminder why `spawn: false` as of right now unusable in complex projects: https://github.com/gruntjs/grunt-contrib-watch/issues/510

**Comment by shama** [comment]
Feel free to submit an [rfc](https://github.com/gruntjs/rfcs) if you have an idea for a better API you would like to implement.

I'm not sure what your use case is. `grunt-contrib-watch` can either spawn tasks or not spawn tasks. If that isn't sufficient, one could implement their own task that watches files if further customization is needed by using [gaze](https://github.com/shama/gaze), [chokidar](https://github.com/paulmillr/chokidar) or many there is a better watch lib out there now.

Re: https://github.com/gruntjs/grunt-contrib-watch/issues/510 sometimes an issue is really just a misunderstanding. Glancing at that issue, it looks like they are misunderstanding what `spawn: false` actually does. Unfortunately I don't have the time to look into their issue and help them resolve it or make changes that might better accommodate their use case though.

I use `grunt-contrib-watch` just fine on many complex projects.
