### ISSUE TITLE
Upgrade eventemitter2 to latest stable version 4.1.2

### ISSUE THREAD

**Issue by palashmon** [gruntjs/grunt#1602]
There is a newer version of [`eventemitter2`](https://www.npmjs.com/package/eventemitter2) released that this project depends on.

**Required:** ~0.4.13
**Stable:** 4.1.2

Please update to latest and test it out.
Regards!

**Comment by shama** [comment]
Is there a specific reason you think Grunt should update to these versions?

Also thanks for the ping, we are aware when versions become out of date and don't need an issue opened for each dependency that goes out of date. Not unless there is a specific reason, such as a security issue etc. Thanks!
