### ISSUE TITLE
Question: Executing multiple Tasks in multiple Folders

### ISSUE THREAD

**Issue by Disane87** [gruntjs/grunt#1603]
Hey guys, thank you for this awesome tool you've created!
Actually I'm stuck with a question I can't solve on my own.

I have to projects with grunt:
- Website
- API

Both with an embedded webserver.
I need to start the API and then the website to getting productive and have a happy coding.
Currently I have to start the "server" tasks both on my own in separate batches/bashes.

Is thete any possibiity to execute both of them from one point? How do you handle such constructs of startung an API and a website?

**Comment by shama** [comment]
The Grunt issue tracker is mainly for tracking issues with Grunt. You'll likely get more and better answers to questions by using stackoverflow.com.

The answer to your above question depends on a lot of things. You can run a process in the background by appending `&` to the command or use `nohup` to keep the process running even after you logout. Or use a more robust process management tool like https://www.npmjs.com/package/pm2

You should find lots of ways by googling `node.js server management`
