### ISSUE TITLE
grunt.file.expand ignores brackets - "[", "]" - in src path for directory name "A[A]" pattern

### ISSUE THREAD

**Issue by cnrdi** [gruntjs/grunt#1607]
When I try to expand files of directory that name matches the 'pattern' - "A[A]" where "A" is any string, ``grunt.file.expand`` ignores those brackets and looks at directory "AA".

```
grunt.file.expand({cwd:  './'}, "C:/source/tmp/A[A]/src/**/*.less"); 
```
... should return:
```
 [ 'C:/source/tmp/A[A]/src/styles/cards.less',
  'C:/source/tmp/A[A]/src/styles/core.less' ]
```
but gives:
```
[]
```
until I copy "A[A]" directory content to "AA" folder and then rerun task. After that, for same parameters as before:
```
grunt.file.expand({cwd:  './'}, "C:/source/tmp/A[A]/src/**/*.less"); 
```
I got:
```
[ 'C:/source/tmp/AA/src/styles/cards.less',
  'C:/source/tmp/AA/cbp-bos-cards-web-component/src/styles/core.less' ]
```
What is incorrect, it's just the case that confirms problem.

When directory name is like "A[]" (without text between "[" "]") everything is ok.

node: 7.4.0
grunt: 1.0.1

**Comment by shama** [comment]
`[ ]` is a file matching pattern, `grunt.file.expand('file[0-9]')` so you'll need to escape it if you intend on matching a bracket specifically `grunt.file.expand('tmp/A\\[A\\]/src')`. See https://en.wikipedia.org/wiki/Glob_(programming)

A better solution though is to set your cwd more closely to the sub folder you're matching: `grunt.file.expand({cwd:  'C:/source/tmp/A[A]/src/'}, "**/*.less");

**Comment by cnrdi** [comment]
Escape attempts seems to not working:
```
var dirname = _dirname.replace("[", "\\[").replace("]", "\\]");
console.log("dirname", dirname);
console.log(grunt.file.expand(dirname));
```
Lines above are under global "xxx" command. Some output:
```
C:\_>xxx
dirname C:\_
[ 'C:/_' ]

C:\_>cd "a[a]"

C:\_\a[a]>xxx
dirname C:\_\a\[a\]
[]
```
I was trying to "escape" it using from 1 (``"\["``) up to 4 (``"\\\\["``) backslashes, nothing helped.

But yes, you're right about putting this fullpath to ``cwd``, not as file pattern - it's better idea and I hope so it will be ok :). 

Thanks for help!
