### ISSUE TITLE
Consider deprecating Grunt.

### ISSUE THREAD

**Issue by thecotne** [gruntjs/grunt#1608]
bower/bower#2298 https://github.com/graingert/bower/commit/4e3b3ddbef07ed38eb934424a009b20d140c3f57

**Comment by shama** [comment]
No.

Deprecating would benefit nobody. Grunt is still a valid tool that lots of people use, including myself. It is also still a great entry point to the JavaScript community.

The issue you referenced has no bearing on this project. Grunt is not Bower.
