### ISSUE TITLE
Unhandled rejection Error

### ISSUE THREAD

**Issue by shervud** [gruntjs/grunt#1613]
Hello everyone.
grunt version 0.4.5
I have faced with several errors and don't know how to resolve them. Several of them appear randomly, so I even don't know how to reproduce them. The worst thing is that these Unhandled errors break my build and then break full deploy. For example, deploy of 30 sites (30 builds) would go about 4 hour and at 29th build deploy can fail because of build fail :(
So it is high risk to use grunt tasks.

This is the list of errors:
1. Unhandled rejection Error: socket hang up
2. Unhandled rejection Error: Wrong status code 502

I have described the situation here: https://github.com/bezoerb/grunt-critical/issues/46

So my question, is there any way to apply **try catch** logic to grunt tasks to resolve Unhandled rejection Error?

Of course, I run my tasks with force: true. And I try usual try catch logic, but it does not work. Like that:

>     try {
>       grunt.task.run('sometask');
>     }
>     catch (e) {
>       someCode(); // <-- this is never run
>     }

Probably because grunt tasks runs in async mode?

**Comment by shama** [comment]
It's up to the plugin on how they handle errors. If the plugin has decided that a particular error should fail then it will fail. So at the moment, duck punching Grunt is the only way around errors that plugins report as failures.
