### ISSUE TITLE
Unhandled exception breaks down grunt task

### ISSUE THREAD

**Issue by shervud** [gruntjs/grunt#1614]
Hi again. 
Here is my question: https://github.com/gruntjs/grunt/issues/1613
But that question was closed right after it had been commented. And now I have even more questions, because my situation with grunt looks strange to me.

If some Unhandled rejection Error or the other kind of error occurs, How grunt should behave itself who can give me a complete answer?

Imagine we have 2 case:
1) Self-written task of mine and there is some programmer error in the task (error done by me)
2) Some hidden error in npm package (that package is used in one of grunt plugin) placed behind grunt control, rather under control Node.js.

What will be in these two above cases, if we try to run them in two ways: with --force and without --force option?

1. If there is no --force option, what will grunt give me? 
It would be rather something like that, right? 
> grunt try:exception
> Running "try:exception" (try) task
> 
> Running "exception" task
> Warning: qweqweqwe Use --force to continue.
> 
> Aborted due to warnings.
Or it may be full crash with interrupting of running of the further grunt tasks and without showing the warning "Use --force to continue"? <-- is 

2. If there is --force option is enabled, what will grunt show me?
> grunt try:exception
> Running "try:exception" (try) task
> 
> Running "exception" task
> Warning: qweqweqwe Used --force, continuing.
> 
> Running "log" task
> Nothing here
> 
> Done, but with warnings.
Or is there a probability of crash grunt and stopping of running the next tasks?

Here is my code:
>   grunt.registerTask('log', 'Log task', function () {
>     console.log('Nothing here');
>   });
> 
>   grunt.registerTask('exception', 'Task with exception', function () {
>     var done = this.async();
>     throw new Error('Danger error. Oops.');
>     done();
>   });
> 
>   grunt.registerTask('try', 'Try task', function () {
>       grunt.option('force',true);
>       grunt.task.run(task);
>       grunt.task.run('log');
>   })

**Comment by shervud** [comment]
All tasks run with --force. Here you can see appeared error, but grunt did not fail:
![grunt-task-fails](https://user-images.githubusercontent.com/24463666/33934291-8ba44c7e-e009-11e7-8851-c14320e2e058.png)

Here grunt failed:
![grunt-task-fails-1](https://user-images.githubusercontent.com/24463666/33934293-8bc4fcf8-e009-11e7-9ac9-77c79accf165.png)

Here grunt failed:
![grunt-task-fails-2](https://user-images.githubusercontent.com/24463666/33934294-8be5753c-e009-11e7-862b-00111e6015fc.png)

![grunt-task-fails-3](https://user-images.githubusercontent.com/24463666/33934555-4a4ab942-e00a-11e7-90ef-9afbcc717197.png)

Grunt plugin grunt-critical uses [penthouse](https://github.com/pocketjoso/penthouse) npm packege. At the 3rd screenshot you may see it fails after 60s of timeout, because I had set timeout to 60s. But with the same run options and parameters on the 4th screenshot it was handled by grunt successfully!

**# What is that?**
Sometime errors are handled OK, sometime no.  I would be appreciate any answer which help to find root cause.
Is problem in npm package penthouse or is problem in Node.js processes?

**Comment by shama** [comment]
You're more likely going to get a better answer on [stackoverflow.com](stackoverflow.com) or another general question support channel.

This issue tracker is _mostly_ for tracking issues with Grunt itself and not really a support channel. I sometimes try to answer if I know but I don't use those plugins you're using.

**Comment by shervud** [comment]
Ok, thank you. I'll try
