### ISSUE TITLE
grunt cannot run because dyld library not loaded

### ISSUE THREAD

**Issue by brothman01** [gruntjs/grunt#1616]
when I run the command `$ grunt -v` I get the following error:
dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.58.dylib
  Referenced from: /usr/local/bin/node
  Reason: image not found
Trace/BPT trap: 5
This error means I cannot use grunt in my projects.  How do I fix this error?

**Comment by shama** [comment]
Grunt doesn't use that library. So it's likely a dependency/grunt plugin you're using that is trying to load it.

Or it could be a problem when node was installed... a quick Google search of the error resulted in this: https://github.com/Homebrew/homebrew-core/issues/11713
