### ISSUE TITLE
Release latest `master` to npm

### ISSUE THREAD

**Issue by vladikoff** [gruntjs/grunt#1623]
Hey @shama,

I want to pick up the changes from master and publish them to npm

Should it be a 1.1.0?

See https://github.com/gruntjs/grunt/commits/master

**Comment by ArmorDarks** [comment]
I hoped that https://github.com/gruntjs/grunt/issues/1556 would be implemented before release...

**Comment by vladikoff** [comment]
@ArmorDarks the plan is to fix the deprecation warning. However "Remove coffeescript dependency" (removing the dep) is probably not happening.

**Comment by shama** [comment]
Looking at the diff https://github.com/gruntjs/grunt/compare/8ada4948b69c6ec9b1e956b5e6b2e6814fa054ca...master, I don't see anything new being added or breaking. Assuming nothing has changed but the name from `coffee-script` to `coffeescript`, it looks like only bug fixes.

I think we're safe releasing as `1.0.2`. Thanks @vladikoff!

**Comment by vladikoff** [comment]
https://github.com/gruntjs/grunt/commit/ccc316360ba9056ccb794cc358a46cc7b8cafef9

https://www.npmjs.com/package/grunt

Thanks @shama !
