### ISSUE TITLE
Opening any file on OSX causes grunt-watch to trigger.

### ISSUE THREAD

**Issue by NoelBaron** [gruntjs/grunt#1626]
I posted about this [on the grunt-watch repository](https://github.com/gruntjs/grunt-contrib-watch/issues/552), but I thought there might be more active folks here.

Anytime I open any watched file, regardless of IDE, my watch events are triggered. It also detects mass-changes when my IDE opens with pre-loaded files. Anyone ever experience this? If so, how did you resolve it?

**Comment by shama** [comment]
I have not experienced that. It sounds like your IDE or environment is setup to write files that grunt is watching. Perhaps it is creating lock files. `grunt-contrib-watch` doesn't/can't listen to any file open events.
