### ISSUE TITLE
Security vulnerability in lodash@3.10.1 from grunt-legacy-log

### ISSUE THREAD

**Issue by marcysutton** [gruntjs/grunt#1628]
I filed this over in https://github.com/gruntjs/grunt-legacy-log/issues/28, but there's a security vulnerability being reported in lodash@3.10.1. Grunt-legacy-log includes that version, and this project includes grunt-legacy-log. They need to update to the latest version of lodash and put out a new release, but I figured I'd also file it here since it will require a new release of Grunt to address the vulnerability.

https://hackerone.com/reports/310443

**Comment by shama** [comment]
Fixed with https://github.com/gruntjs/grunt-legacy-log/commit/e772b48009c4025277a5d15d225570dc1c780c14 Thanks!

**Comment by marcysutton** [comment]
Thanks for the quick update! 🙌
