### ISSUE TITLE
Grunt task exception at async await function

### ISSUE THREAD

**Issue by louisnelza** [gruntjs/grunt#1632]
Hi there,

My grunt task is giving an exception at this code line:

```
async function order() {

}
```
I presure it is because it does not recognize the async syntax?

Grunt version 1.0.2
Grunt contrib-uglify 3.3.0

**Comment by shama** [comment]
Which version of Node.js? Only later versions natively support async/await syntax. For instance this works for me in `node@8.11.1`:

```js
module.exports = function(grunt) {
  const fs = require('fs');
  const util = require('util');
  const readFile = util.promisify(fs.readFile);
  grunt.initConfig({});
  grunt.registerTask('default', async function () {
    const done = this.async();
    const gruntfile = await readFile('Gruntfile.js');
    console.log(gruntfile.toString());
    done();
  });
};
```

**Comment by louisnelza** [comment]
Hi Shama, using the same version of `node@8.11.1`.

Thanks for sending that solution!
