### ISSUE TITLE
Grunt Install Error

### ISSUE THREAD

**Issue by dtone1** [gruntjs/grunt#1633]
Hi, 
I'm trying to install Grunt on on my mac (High Sierra version). When I execute the commands (with and with out sudo) I either get an error message or a request to enter my password (See screen shot)

![screen shot 2018-05-11 at 12 04 06](https://user-images.githubusercontent.com/39187960/39919404-cc29a666-5513-11e8-9e19-b7f6bd8502a3.png)

Can someone help?

**Comment by shama** [comment]
It's because you've installed Node.js/npm in a place where it doesn't have permission to install global dependencies. Read this: https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by shama** [comment]
Or https://gist.github.com/isaacs/579814
