### ISSUE TITLE
Stable Node.js version for Grunt

### ISSUE THREAD

**Issue by dtone1** [gruntjs/grunt#1634]
Hi, 

on https://gruntjs.com/getting-started it says that a even vesion of Node.js (i.e. a stable version) is required for Grunt. (See screen shot)

![screen shot 2018-05-11 at 12 11 34](https://user-images.githubusercontent.com/39187960/39919671-a6abf546-5514-11e8-842b-fbea4482ee0e.png)

The current LTS version is 8.11.1 (https://nodejs.org/en/) does this pose a problem? Can someone explain this?

**Comment by shama** [comment]
Node.js used to publish unstable development versions on odd version numbers before `1.0.0`. Node.js doesn't anymore, so we could probably remove that from our docs now.
