### ISSUE TITLE
Security issues

### ISSUE THREAD

**Issue by brettz9** [gruntjs/grunt#1635]
As a result of issues for dependencies [grunt-legacy-util](https://github.com/gruntjs/grunt-legacy-util/issues/20) and grunt-legacy-log -> [grunt-legacy-log-utils](https://github.com/gruntjs/grunt-legacy-log-utils/issues/3), npm's new `npm audit` flags grunt with these problems (and any repo depending on grunt).

It would be great to have these two issues fixed (with upgrades to the lodash version in use).

Thanks!

**Comment by jbruni** [comment]
Indeed... we'll need new releases for `grunt`, `grunt-legacy-util`, `grunt-legacy-log` and `grunt-legacy-log-utils`, in order to have `npm audit` to cease reporting about `lodash` when we install `grunt`.

Thanks in advance.

**Comment by vladikoff** [comment]
@brettz9 @jbruni we are gonna attempt to fix this up in the next few days

**Comment by vladikoff** [comment]
Quick update, I'm blocked by npm issues in https://github.com/gruntjs/grunt-legacy-log-utils/pull/5 

Will have to wait until @shama comes back from camp.

**Comment by brettz9** [comment]
Indeed--how about an npm release? Thanks a lot!

**Comment by vladikoff** [comment]
will give another 2-3 biz day for a new jshint version, if that doesn't arrive then we will tag a new release
