### ISSUE TITLE
Warning: Cannot read property 'bigint' of undefined Use --force to continue

### ISSUE THREAD

**Issue by erwinsetiawan** [gruntjs/grunt#1645]
Grunt-cli version: 1.2.0
Grunt version: 1.0.3
Node version: 10.5.0

I run grunt on my current project using sails and it working well for grunt watch on node 9.6.x but after upgrade to node 10.5 it suddenly have this warning error on watch and failed to sync file "Warning: Cannot read property 'bigint' of undefined Use --force to continue" 

```
Running "watch" task
Waiting...
>> File "assets/styles/project/_colors.scss" changed.
Running "less:dev" (less) task
>> 1 stylesheet created.

Running "sass:dev" (sass) task

Running "sync:dev" (sync) task
Warning: Cannot read property 'bigint' of undefined Use --force to continue.
```

Is there any way to solve this issue?

**Comment by erwinsetiawan** [comment]
I downgrade to node 10.4.1 fix this problem. So the problem is when running grunt on node version 10.5.0.

**Comment by shama** [comment]
You can add `grunt --stack` or `grunt --verbose` to get more info on where the error originates. I dont think Grunt uses a `bigint` property anywhere, so it's likely an issue in the task.

**Comment by Singularetantum** [comment]
try to update grunt-sync to 0.8.0, they fixed it

**Comment by DanielRuf** [comment]
But why was this closed?

**Comment by shama** [comment]
Because it's not an issue with Grunt.

**Comment by DanielRuf** [comment]
> Because it's not an issue with Grunt.

I don't think so because it stems from Grunt and one of its dependencies which makes it unusable on Node.js 10.

**Comment by DanielRuf** [comment]
At least a warning for `postinstall` would be helpful here.

**Comment by shama** [comment]
This was an issue with a 3rd party plugin not affiliated nor a dependency of Grunt (the project) whatsoever.
