### ISSUE TITLE
grunt not taking $PATH into account

### ISSUE THREAD

**Issue by ulicodex** [gruntjs/grunt#1649]
The error I got was:

> There are no commands defined in the "dev:source-theme" namespace.

when I was calling `grunt exec:<theme>`
It results from grunt just using `/usr/bin/php` instead of the first php that can be found via my `$PATH` variable.
I am on an up to date macOS, I solved this by setting `csrutil disable` and then linking `/usr/bin/php` to a supported version.

**Comment by shama** [comment]
This is the issue board for Grunt itself. Issues with 3rd party plugins should be reported to those plugin maintainers instead. I'm guessing [this is the exec task you're using](https://github.com/jharding/grunt-exec).
