### ISSUE TITLE
Support yarn workspaces

### ISSUE THREAD

**Issue by peterjanes** [gruntjs/grunt#1650]
When using `yarn`'s [workspaces feature](https://yarnpkg.com/en/docs/workspaces), it's currently necessary to add a `.loot()`ed module to the [`nohoist` property](https://yarnpkg.com/blog/2018/02/15/nohoist/) so that it's present in the local `node_modules` directory, e.g.

```
{
  "name": "workspace-project",
  "workspaces": {
    "nohoist": [
      "**/my-horde",
      "**/my-horde/**"
    ]
  }
}
```

Without that configuration, the module isn't found:

```
$ grunt
Loading "Gruntfile.js" tasks...ERROR
>> GruntHordeError: loot: no such module 'my-horde' (resolved to '/home/me/devel/workspace-project/packages/my-module/node_modules/my-horde')
```
(The `my-horde` module itself is found in `/home/me/devel/workspace-project/node_modules`, as well as in some generated "aggregator" projects in the same directory.)

**Comment by shama** [comment]
This seems odd to require 3rd party libraries (Grunt) to provide support for an alternative module structure invented by another 3rd party module (yarn). It sounds like a flaw in workspaces if it is not compatible with [Node.js modules](https://nodejs.org/api/modules.html).

**Comment by peterjanes** [comment]
My understanding is that Yarn's module structure is meant to be compatible with Node's module structure (it's similar to Lerna, which appears to behave in a similar fashion) and that Grunt is (or may be) not using `node_modules` in a standard fashion.

**Comment by shama** [comment]
I'm not familiar with yarn workspaces or lerna. If you require a module in your Gruntfile or task and it doesn't exist in your `./node_modules/` folder, it's not going to be found. Grunt doesn't handle any of that. It's just part of Node.js.

**Comment by peterjanes** [comment]
Acknowledging that I don't know what yarn or lerna are actually doing, I think your comment about Grunt using `./node_modules` is probably the issue. From the page you referenced:

```
If the module identifier passed to require() is not a core module, and does not begin with '/', '../', or './', then Node.js starts at the parent directory of the current module, and adds /node_modules, and attempts to load the module from that location. Node will not append node_modules to a path already ending in node_modules.

If it is not found there, then it moves to the parent directory, and so on, until the root of the file system is reached.
```

Perhaps that's what using `findup` in `grunt/task.js` is meant to do, but it seems it isn't working in this situation. Whether that's down to `grunt` or `yarn` doing untoward things I don't know; I do know that it's something that doesn't work.

In any case: this isn't a demand, it's a request for either a bug fix (if `grunt` is misbehaving in its handling of `node_modules`) or an enhancement (if `yarn` really is doing something that's against the rules).

**Comment by shama** [comment]
Grunt doesn't have anything to do with `require()`, that is all Node.js. Calling `require()` from within your Gruntfile or task does not touch any part of Grunt whatsoever.

You can confirm this by creating a file `test.js`. In that file try requiring your module `require('my-module)`. Then run `node test.js`. If that module isn't found, yarn is not installing it correctly.

Unless you are talking about Grunt's `grunt.loadNpmTasks()` API. That is an entirely separate thing which loads tasks from the relative `node_modules` folder. Is that what you are talking about?

**Comment by peterjanes** [comment]
Sorry, I think I may have wasted your time here; I use Grunt and [Grunt Horde](https://github.com/codeactual/grunt-horde) together so much I think of them as the same thing. It seems to be *Horde* that's the issue. Apologies for the confusion.
