### ISSUE TITLE
Grunt displays angular version

### ISSUE THREAD

**Issue by vijigit** [gruntjs/grunt#1654]
We have grunt for creating the distribution for the Angular js (V1.5.0) code. The angular version is displayed in the minified version ie., vendor.<hash>.js as below. 

![image](https://user-images.githubusercontent.com/2079571/48925809-de5b8600-eeed-11e8-895d-62319a27c60c.png)

This is reported as security issue. Please can someone advise how this can be removed

**Comment by shama** [comment]
This most likely isn't related to Grunt as it doesn't handle any versioning in builds. It's likely related to Angular or the tools Angular uses to build itself.

If you can provide more information someone might be able to help. Otherwise closing as not related to Grunt.
