### ISSUE TITLE
Grunt crashes with Node 10.14.2

### ISSUE THREAD

**Issue by ahmetcetin** [gruntjs/grunt#1658]
When using node 10.14.2, it crashes with "ReferenceError: internalBinding is not defined"

**Comment by shama** [comment]
I'm not seeing that error with node 10.14.2. If possible could you provide your `package.json` and `Gruntfile.js`?

**Comment by ahmetcetin** [comment]
both of these two tasks are failing with "ReferenceError: internalBinding is not defined" in node 10.14.2, it works with 10.14.1 though:
```
  grunt.registerTask('buildDocker', [
    'ngconstant:devdocker',
    'build',
    'env:devdocker',
    'preprocess:dev',
  ]);

  grunt.registerTask('buildProd', [
    'ngconstant:production',
    'build',
    'env:prod',
    'preprocess:dev',
  ]);
```

**Comment by ahmetcetin** [comment]
I found this issue in node, same problem with gulp:
https://github.com/nodejs/node/issues/24985

**Comment by shama** [comment]
It looks like this is an issue with the `natives` package and it needs to be updated. You can force it with `npm i natives@1.1.6`.

Grunt doesn't have `natives` as a dependency so I don't think this is related to Grunt. The plugin `grunt-cache-busting` however does have it as a dependency tagged with `^1.1.0`. So you may just need to delete your `package-lock.json`, `rm -rf node_modules` and `npm i` again to get the latest version.

**Comment by Blatmann** [comment]
Thanks @shama.
Deleting my `package-lock.json`, `rm -rf node_modules` and `npm i` worked for me
