### ISSUE TITLE
HTML build plugin documentation is confusing

### ISSUE THREAD

**Issue by Stefany93** [gruntjs/grunt#1659]
I am trying to extract the css from an external file and add it to inline css (I am building an AMP app)

   ```
<!-- build:style inline home [amp-custom] -->
        <link rel="stylesheet" href="dist/styles/css/styles.css">
   <!-- /build -->
```
Does anyone have grunt code examples how they did it with that plugin? The documentation is spaghetti. Thanks so much.

**Comment by shama** [comment]
Hi @Stefany93! I'm not sure what plugin or documentation you're referring to. This issue board is for issues with Grunt itself. You'll likely receive better answers to more general questions on stackoverflow.com. Or if it's an issue with documentation or a plugin, please open the issue on the plugin's issue tracker or their support channels. Thanks!
