### ISSUE TITLE
Getting This error while running "grunt serve" for angular js project. src\node_contextify.cc:628: Assertion `args[1]->IsString()' failed.

### ISSUE THREAD

**Issue by techsavvypp** [gruntjs/grunt#1660]
![image](https://user-images.githubusercontent.com/42607623/50753875-8ef0cf80-1279-11e9-9963-6fa2e8ccd1db.png)

Getting above error while running "grunt serve" command. Any resolution and root cause for thiis issue?
Node and NPM version.
![image](https://user-images.githubusercontent.com/42607623/50753925-db3c0f80-1279-11e9-959f-0ef892882be2.png)

**Comment by shama** [comment]
This issue doesn't look related to Grunt itself.

I did a google search with your error for you and it led to this: https://github.com/gulpjs/gulp/issues/2162 which shows it is likely an out of date dependency.

I'm guessing `angular-ui` has some dependency that is out of date and is solved by https://github.com/gruntjs/grunt/issues/1658#issuecomment-449176540

**Comment by Yalhu** [comment]
I reset native@1.1.3 as /gulpjs/gulp#2162 but it doesn't work. And I remove node_modules first before install.
node:10.14.2
npm: 6.4.1
os: windows 7(64-bit) 

I also try node 8.11.1 via nvm, failed.
