### ISSUE TITLE
Disable a task

### ISSUE THREAD

**Issue by rashnk** [gruntjs/grunt#1661]
I have configured multiple task in grunt, all the task calls 'uglify' task, uglify takes timeto complete as it has many js files to process, so I'm looking for a way to disable(dont run) the task while development without removing 'uglify' from tasks array, how can I achieve this ?

**Comment by Xelonix** [comment]
Remove the 'uglify' task from the common task array, create a finishing task for 'uglify' and run as necessary.

**Comment by Xelonix** [comment]
Perhaps for your task fit plugin 'grunt-newer'.

**Comment by rashnk** [comment]
I solved this 
```

    uglify: {
      compile: {
        options: {
          banner: '<%= meta.banner %>'
        },
        files: {
          // '<%= dist_js.min_dest %>': '<%= src_js.dest %>'
        }
      }
    },

```
