### ISSUE TITLE
Support monorepo

### ISSUE THREAD

**Issue by micellius** [gruntjs/grunt#1676]
There is a common practice of splitting up large codebases into multiple separate packages, while developing them within a single repository (e.g. Babel, React, Angular, Ember, Meteor, Jest). This kind of project setup is known as "monorepo". Packages within monorepo usually have same dev dependencies (e.g. grunt and it's plugins). Various tools, including Yarn and Lerna tend to hoist shared dependencies of individual packages to `node_modules` above them. While NPM and Node.js are able to resolve hoisted packages location, grunt looks-up only in `node_modules` of current working directory. This leads to broken functionality of `loadNpmTask()` API.

Node.js (since v0.3.0) has a [built-in API](https://nodejs.org/dist/latest-v10.x/docs/api/modules.html#modules_require_resolve_request_options) to resolve location of packages by name: `require.resolve(request[, options])`. Using it, grunt may overcome the limitation described above and may be used with monorepo setup.

__Current Implementation__

```js
task.loadNpmTasks = function(name) {
  loadTasksMessage('"' + name + '" local Npm module');
  var root = path.resolve('node_modules'); // <= Hard-coded
  var pkgfile = path.join(root, name, 'package.json');
  ...
}
```

__Proposial__

```js
task.loadNpmTasks = function(name) {
  loadTasksMessage('"' + name + '" local Npm module');
  var pkgfile = require.resolve(path.join(name, 'package.json')); // <= Uses Node.js package resolution machanism
  var root = pkgfile.substr(0, pkgfile.length - name.length - path.sep.length - 'package.json'.length);
  ...
}
```

**Comment by avizov** [comment]
Any updates about this issue? Do you plan to approve and merge this pull request?

**Comment by DemianX0** [comment]
Yarn 2 takes this issue a [step further](https://yarnpkg.com/features/pnp): packages aren't extracted. Running grunt with yarn 2 (berry) results in the following output (arbitrary choice of plugins):
```
$ yarn test
>> Local Npm module "grunt-banana-checker" not found. Is it installed?
>> Local Npm module "grunt-contrib-copy" not found. Is it installed?
>> Local Npm module "grunt-eslint" not found. Is it installed?
>> Local Npm module "grunt-karma" not found. Is it installed?
>> Local Npm module "grunt-stylelint" not found. Is it installed?
>> Local Npm module "grunt-svgmin" not found. Is it installed?

Aborted due to warnings.
```
