### ISSUE TITLE
Security Issue in js-yaml

### ISSUE THREAD

**Issue by mbglasser** [gruntjs/grunt#1679]
A security vulnerability is reported in js-yaml as per advisory https://www.npmjs.com/advisories/813.

The issue is fixed in js-yaml >= 3.13.1.

Grunt is currently using ~3.13.0.

**Comment by vladikoff** [comment]
the new version is included in the semver range

![](http://v14d.com/i/1aaa4863c44eb12873afd23a49d1d07b1162c223ba4ae4bbb324f27696237b2d.jpg)

You probably just need to regenerate your package lock file
