### ISSUE TITLE
underscore.string vulnerability 

### ISSUE THREAD

**Issue by shades3002** [gruntjs/grunt#1685]
grunt -> grunt-legacy-util ->

Upgrade underscore.string to version 3.3.5 or later. For example:

"dependencies": {
  "underscore.string": ">=3.3.5"
}

**Comment by ydegtyar** [comment]
This issue should be created at grunt-legacy-util repo. It can't be done in this repo

**Comment by silviuburceadev** [comment]
grunt 1.3.0 uses grunt-legacy-util ~2.0.0, which uses underscore.string ~3.3.5. This issue should be closed. (cc: @vladikoff)

**Comment by Krinkle** [comment]
Duplicate of https://github.com/gruntjs/grunt/issues/1664.
