### ISSUE TITLE
js-yaml Vulnerable versions: < 3.13.0 

### ISSUE THREAD

**Issue by shades3002** [gruntjs/grunt#1686]
Vulnerable versions: < 3.13.0
Patched version: 3.13.0
Versions js-yaml prior to 3.13.0 are vulnerable to Denial of Service. By parsing a carefully-crafted YAML file, the node process stalls and may exhaust system resources leading to a Denial of Service.

**Comment by silviuburceadev** [comment]
grunt 1.3.0 uses js-yaml ~3.14.0, this issue should be closed.
