### ISSUE TITLE
Why is the plugin list page I am accessing empty?

### ISSUE THREAD

**Issue by zhwangart** [gruntjs/grunt#1689]
Why is the plugin list page I am accessing empty?
为什么我访问到的插件列表页面是空的呢？

[https://gruntjs.com/plugins](https://gruntjs.com/plugins)
[https://www.gruntjs.net/plugins](https://gruntjs.com/plugins)

**Comment by vladikoff** [comment]
Hm looks like the site deployed but the plugin script failed. We can try investigating...

**Comment by TiwariShubham** [comment]
Are we doing anything about it?

**Comment by goky91** [comment]
Hi, is this going to be fixed?

**Comment by TiwariShubham** [comment]
Not sure if this is a priority for getting fixed.

**Comment by Falcikas** [comment]
It is fixed now, issue closed?
