### ISSUE TITLE
Need to fix these vulnerabilities

### ISSUE THREAD

**Issue by sanjowinson** [gruntjs/grunt#1690]
￼
￼
￼How I can Fix this  after npm install. I tried versioning and made changes in dependencies. Can someone please guide me on this because I am new on this and having facing this issue from last one week. **Am using npm latest and grunt to build meanwhile am getting vulnerabilities after npm install, I would like to know is there any issues after the build or it will affect the application while those vulnerabilities exits. Or can I ignore those vulnerabilities**

**Comment by sanjowinson** [comment]
can someone please give any update on this?


Thanks

**Comment by sanjowinson** [comment]
any one is available to give a solution tip :(

**Comment by Falcikas** [comment]
Before you make an issue, please read the [Contributing guide->Filing issues section](https://gruntjs.com/contributing#filing-issues). 

Can you post the log of warnings or errors you get?

**Comment by Krinkle** [comment]
I'm going to assume this old issue is about underscore.string. See https://github.com/gruntjs/grunt/issues/1664 for details

> it allows automatic updates of patch versions. If you see a warning, remove `package-lock.json` and re-run `npm install`. No changes to grunt were needed.
