### ISSUE TITLE
Who made the Grunt logo?

### ISSUE THREAD

**Issue by n-ham** [gruntjs/grunt#1691]
I would love to get a similar logo made for Nift (https://nift.cc), maybe a Tassie Devil or something like that..

I also put Grunt up top for JS frameworks on the Nift site for having such a cool logo, see https://nift.cc/resources/js_frameworks.html

**Comment by n-ham** [comment]
Nevermind, I found someone on freelance.com that has made me two awesome logos. Good work with the Grunt logo and Grunt though folks, I will look in to making some Grunt site repository templates for Nift.

**Comment by nebrelbug** [comment]
@n-ham who was the person you found? I'd love to get some logos done as well

**Comment by n-ham** [comment]
@nebrelbug I found the person on freelancer.com but have them on facebook now. Have asked them about putting them in contact with you, feel free to email me contact@n-ham.com 

I paid AUD$260 for the bunny and a little less for the badger that's down in the footor of the Nift website. You can probably get cheaper on freelancer.com while still being pretty good, but I'm really happy with the Nift bunny and badger mascots.

**Comment by nebrelbug** [comment]
@n-ham thanks for the recommendation! Unfortunately that's a little out of my price range, so I'll work on improving the logo myself for the next little while.

As for Nift, that's a great idea! Squirrelly is the 2nd fastest template engine right now, and is 50 times smaller than the fastest. I'll let you know when I have a better logo :)

**Comment by n-ham** [comment]
You can definitely get a decent logo much cheaper on websites like freelancer.com and fiverr.
