### ISSUE TITLE
Regular Expression Denial of Service

### ISSUE THREAD

**Issue by mcandre** [gruntjs/grunt#1692]
Please update the dateformat dependency to at least v2.0.0, in order to resolve a security risk:

https://www.npmjs.com/advisories/31

**Comment by trannzfsg** [comment]
Upvote on this one, for minimist version (grunt => dateformat => meow => minimist) 1.1.3, it needs to be updated to 1.2.2+, otherwise triggering github security vulnerability alerts.

BTW, the newest version of dateformat is now 3.0.3.

**Comment by silviuburceadev** [comment]
grunt 1.3.0 uses dateformat ~3.0.3, so this should be closed.
