### ISSUE TITLE
Unable to find local grunt. 

### ISSUE THREAD

**Issue by sburke56** [gruntjs/grunt#1711]
I know this is beating a dead horse from years ago but I'm running into this issue and can't seem to get around it.  I have ran through the startup documentation a bunch of times now.  Is this a regression of some sort and is there a way to start over in a clean environment and verify this works on my machine?  I put all my info below on my files and versions. Any help would be appreciated. 

https://github.com/gruntjs/grunt-docs/issues/38

```
sburke@sburke-xps:/tmp/g1$ cat Gruntfile.js 
var grunt = require('grunt');
grunt.loadNpmTasks('grunt-aws-lambda');

grunt.initConfig({
    lambda_invoke: {
        default: {
        }
    },
    lambda_deploy: {
        default: {
            arn: '<some arn>'
        }
    },
    lambda_package: {
        default: {
        }
    }
});

grunt.registerTask('deploy', ['lambda_package', 'lambda_deploy']);
sburke@sburke-xps:/tmp/g1$ cat package.json 
{
  "name": "lambda",
  "version": "0.1.0",
  "dependencies": {
    "aws-sdk": "^2.676.0",
    "node": ">= 0.10.0"
  },
  "devDependencies": {
    "grunt": ""^0.4.5",
    "grunt-contrib-jshint": "~0.10.0",
    "grunt-contrib-nodeunit": "~0.4.1",
    "grunt-contrib-uglify": "~0.5.0"
  }
}
sburke@sburke-xps:/tmp/g1$ npm install 
npm WARN lambda@0.1.0 No description
npm WARN lambda@0.1.0 No repository field.
npm WARN lambda@0.1.0 No license field.

up to date in 2.29s
sburke@sburke-xps:/tmp/g1$ grunt --version 
grunt-cli v1.3.2
sburke@sburke-xps:/tmp/g1$ grunt 
grunt-cli: The grunt command line interface (v1.3.2)

Fatal error: Unable to find local grunt.

If you're seeing this message, grunt hasn't been installed locally to
your project. For more information about installing and configuring grunt,
please see the Getting Started guide:

https://gruntjs.com/getting-started
sburke@sburke-xps:/tmp/g1$ 
sburke@sburke-xps:/tmp/g1$ npm --version 
6.14.5
sburke@sburke-xps:/tmp/g1$ lsb_release -a 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS (beaver-osp1-melisa X30)
Release:	18.04
Codename:	bionic
```

**Comment by vladikoff** [comment]
```

Fatal error: Unable to find local grunt.
```

means there's no `grunt` in your `node_modules`. did you `npm i` your project?

**Comment by sburke56** [comment]
Above I cat out the files and then issue the `npm install`.  That should be all I have to do with that Gruntfile with a devdependency of grunt correct?

**Comment by vladikoff** [comment]
@sburke56 I see in the cat file:

```
   "grunt": ""^0.4.5",
```

too many doublequotes in there? is your json file properly formatted?

should be :
```
   "grunt": "^0.4.5",
```

**Comment by sburke56** [comment]
That was simply a typo when writing up this ticket.  I was grabbing the latest from github when trying the last time before making this ticket.  

Anyway, I removed everything grunt related according to [this post](https://stackoverflow.com/questions/22642655/how-to-uninstall-npm-package) and installed again and things are working now. 

This is a new machine and I was updating some code from years ago so somehow it got into that state.  Dunno, it's working now.

**Comment by sburke56** [comment]
I believe the issue I keep running into is that when I run `npm install grunt --save-dev` it saves the entry in the devdependencies section but never actually downloads it.  Running `npm install` does not pull it down either.  Only running `npm install --only=dev` is the only way the package gets pulled down and then the local grunt is actually found.  Is this a package setup issue or fault with `npm install` not pulling down dev dependencies after you specify an install?

**Comment by Abhishek2kr** [comment]
After running all right commands it fails then try those commands after running this
```npm config set registry https://registry.npmjs.com/```

It will work.

[https://stackoverflow.com/a/75183131/10373693](ref)
