### ISSUE TITLE
report an issue about mkdirp moudle while using `grunt --force`

### ISSUE THREAD

**Issue by chenhb-zte** [gruntjs/grunt#1716]
HELLO  please help.
node version is v6.17.1,  grunt version is 1.2.1 and mkdirp version is 1.0.4.
report the issue:
/var/www/fbctf/node_modules/grunt/node_modules/mkdirp/lib/opts-arg.js:7
    opts = { mode: 0o777, fs, ...opts }

looks like the new grunt can not run well on node6.

**Comment by vladikoff** [comment]
node 6 reached end-of-life (EOL) on April 30, 2019.

for your projects, shrinkwrap grunt with versions pre `1.1.0`: https://github.com/gruntjs/grunt/blob/master/CHANGELOG#L30

https://github.com/gruntjs/grunt/blob/master/CHANGELOG#L30
