### ISSUE TITLE
Error: Grunt attempted to load a .coffee file but CoffeeScript was not installed.

### ISSUE THREAD

**Issue by derrickb** [gruntjs/grunt#1725]
I've just come back to my project on a fresh Windows install after some months away from it. I've been using grunt with a Gruntfile.js for years without this issue.

I installed grunt-cli 1.4.0 and get this error when attempting to run grunt in my project:
```
Loading "main.coffee" tasks...ERROR
    >> Error: Grunt attempted to load a .coffee file but CoffeeScript was not installed.
    >> Please run `npm install --dev coffeescript` to enable loading CoffeeScript.
```
I'm not using any CoffeeScript files, and do not want to add it as a dependency just to clear this error. I get the error for almost every task in my grunt file.

I tried running `npm i -f` as I saw that referenced elsewhere from a google search. I also updated local grunt to 1.3.0

**Comment by vladikoff** [comment]
should be fixed via https://github.com/gruntjs/grunt-cli/releases/tag/v1.4.1

**Comment by vladikoff** [comment]
could you please try https://github.com/gruntjs/grunt-cli/releases/tag/v1.3.2

**Comment by derrickb** [comment]
@vladikoff I managed to track it down to this Grunt plugin: https://github.com/berlysia/grunt-encode-asset-base64

The error occurs no matter what grunt-cli version I use, I tried 1.0.0 through 1.4.1

This is really weird as I was using grunt & grunt-cli with this plugin for several years without this error. The plugin is 6 years old!

Is this something that can/should be fixed on the grunt side? Or is it on the plugin author to fix?

**Comment by derrickb** [comment]
Ah it occurs with grunt versions 1.2.0 and later, and this behavior was called out in the change notes.

The plugin I linked uses both a js file and a coffee file... can grunt simply prioritize the js one to avoid the missing Coffee dependency issue?

**Comment by vladikoff** [comment]
@derrickb i think migrating from plugin from coffeescript should fix it
