### ISSUE TITLE
grunt.file.copy not compatible with grunt-contrib-copy in case of copying symlink

### ISSUE THREAD

**Issue by nejindal** [gruntjs/grunt#1741]
grunt-contrib-copy appends fileName in destPath but grunt.file.copy works fine if fileName is not appended.

**Comment by vladikoff** [comment]
@evilaliv3 hey could you try grunt 1.5.1 , the point release fix should address it

**Comment by evilaliv3** [comment]
Yes! I confirm this @vladikoff 

This issue can be closed!
