### ISSUE TITLE
Getting Started with Grunt 

### ISSUE THREAD

**Issue by Luxcium** [gruntjs/grunt#1744]
## Where to start if you are new to Grunt?

Can you help me start with using Grunt (_or is it a legacy tool???_)

Is the documentation up to date?
 
I am unsure how to start using Grunt (with VS Code in a TypeScript project) and I do not know if it is still a thing that many people are using or not... I have the impression that it could help me fix many many problems I have at managing my (too many) projects...

I am new to Grunt and I was looking at the documentation and the version was off compared to the available version on NPM.

At the moment of writing this:
 - Stable: [v1.4.1](https://www.npmjs.org/package/grunt) _on the web site_  
 - npmjs.com: [v1.5.2](https://www.npmjs.com/package/grunt/v/1.5.2) _on NPM_ 

> It appears that the version was updated only 12 hours ago 🎉

### Useless rant to make you smile

I have that same feeling as when you arrive at the party and the best food in the buffet is all gone... I am unsure if I am too late to get into the Grunt adventure when I read stuff like -> *Grunt 0.4.x requires stable Node.js versions >= 0.8.0* or ***Be advised Grunt 1.0.0 no longer supports Node.js v0.8.*** 

> I think I started using Node.js at v8.x and I have looked up on Wikipedia for insight but the information about older versions only starts at 0.10 (Node.js 0.8.0 was introduced on 2012-06-22).

**Comment by noelforte** [comment]
Hey @Luxcium, although Grunt is an older project, it is still maintained for security patches and basic quality-of-life updates (see #1700). 

To answer your question about whether Grunt is still the best thing worth "getting into" these days, that's really up to you. At its core, Grunt is a simple task runner that lets you automate parts of your build pipeline. Given that there are other, more complex, more specific tools out there that will do everything grunt can and more, it really depends on what you're looking to do with whatever project you're considering using Grunt on. If your needs are simple and you're happy working with an older but solid build pipeline then Grunt will be very approachable in 2022, however understand that there might be tools out there that might better serve your needs if they're more complex or specific.

**Comment by jimmywarting** [comment]
could close this issue now i think - this is pretty old
