### ISSUE TITLE
start testing 3 latest stable branches  

### ISSUE THREAD

**Issue by jimmywarting** [gruntjs/grunt#1749]
https://github.com/gruntjs/grunt/blob/82d79b803798f2a5f19662df9e12bef977dfa189/.github/workflows/test.yml#L16
https://github.com/gruntjs/grunt/blob/82d79b803798f2a5f19662df9e12bef977dfa189/package.json#L10

Propose doing: 

```
node: [14, 16, 18] 
"node": ">=14.14"
```
why 14.14 specifically? fs has `rm` that can replace rimraf

**Comment by vladikoff** [comment]
This was updated 👍
