### ISSUE TITLE
Latest version of grunt failing if we use path.join for windows

### ISSUE THREAD

**Issue by vanshika2702** [gruntjs/grunt#1753]
Grunt is using glob to get file paths. Glob now expects forward slashes in path and treats backward slashes as escape characters due to which grunt task fail on windows. But when you use path.join in file paths for windows it returns path with backward slashes leading to incorrect outputs

**Comment by vladikoff** [comment]
Fixed in 1.6.1. Thanks for the report!

**Comment by vanshika2702** [comment]
glob provides option for path.join compatibility. Instead of downgrading glob we should use windowsPathsNoEscape option in glog.sync

please review PR for fix:

https://github.com/gruntjs/grunt/pull/1757
