### ISSUE TITLE
fix : Change twitter icon to new one 'X'

### ISSUE THREAD

**Issue by maheshsvm** [gruntjs/grunt#1769]
**Description :** 
Twitter icon is changed from a Bird to 'X'

**Steps to Reproduce :** 
1 . Go to [https://gruntjs.com/](url)
2. Scroll down to  "Who uses Grunt" section in homepage
3. See old twitter icon

![image](https://github.com/gruntjs/grunt/assets/102215218/0295b42d-ff85-4978-85e2-97690dafdac6)

**Comment by Sugamgoel28** [comment]
Hello, I would like to work on this issue, Could you please assign it to me?

**Comment by sushilmagare10** [comment]
Hello Can i work on this **@maheshsvm**

**Comment by LEO1612D** [comment]
Hey, i would like to work on this, thanks!

**Comment by artbindu** [comment]
This issue already resolved in PR- [!222](https://github.com/gruntjs/gruntjs.com/pull/222)

This is current changes
<img width="817" alt="image" src="https://github.com/gruntjs/grunt/assets/44528087/c18621ee-50f9-46e8-804c-3a3adbc18ad1">

May be wait for review & deployment

**Comment by rahat2134** [comment]
Is this issue still open? If yes, then please assign me.

**Comment by rahat2134** [comment]
<img width="764" alt="Screenshot 2024-10-06 at 12 41 27 AM" src="https://github.com/user-attachments/assets/d0ca8e1f-fdec-4364-8e95-043c60be804c">

This is how it looks now.
