### ISSUE TITLE
Security Policy needs updating

### ISSUE THREAD

**Issue by ljharb** [gruntjs/grunt#1770]
huntr.dev no longer supports things that aren't ML or AI, so the security policy will need to be updated.

If you don't want to have an email address in the policy, you can enable Github's PVR (private vulnerability reporting) feature (which you may want to do anyways), and the policy can refer to that.

cc @vladikoff; see #1738 and #1746.

**Comment by vladikoff** [comment]
@ljharb oh wow, okay let's do that!
