### ISSUE TITLE
Loading "Gruntfile.js" tasks...ERROR

### ISSUE THREAD

**Issue by chris3122** [gruntjs/grunt#1782]
Bonjour, 
je tape ceci :+1: grunt --verbose
il me donne erreurs 

Registering Gruntfile tasks.
Loading "Gruntfile.js" tasks...ERROR
>> C:\www\templates\frontOffice\Gruntfile.js:41
>>         files:'default_test/assets/src/css/thelia.css':'default_test/assets/src/less/thelia.less'
>>         ^^^^^
Quelqu'un à t'il eu ce problème
le 41 fait réfférence à la ligle 41 de gruntfile.js 
Merci par avance,

**Comment by Krinkle** [comment]
I'm sorry but there are insufficient details here to answer your question.
