### ISSUE TITLE
Concat and remote files

### ISSUE THREAD

**Issue by mintbridge** [gruntjs/grunt#195]
Just wondering about the feasibility of adding the ability to include remote files to the concat task eg:

```
concat: {
  src:[
   'http://code.jquery.com/jquery-1.7.2.min.js',
   'path/to/my/app/that/use/jquery.js'
  ],
  dest: 'one/nice/script/file.js'
}
```

removing the need to have a copy of jquery in the repo

**Comment by dshen-expert360** [comment]
I think it's nice to have the option of concatenating remote files. Appreciating  your consideration about the drawback when taking care of the remote files, however it's quite useful for dev environment. For example, if I need to setup a live reload server with a custom port number, what I need to do is set up a variable for the port number and use it in the concat task, usually the script url would be http://0.0.0.0:3257/livereload.js,  and use to config the port number in the live reload task of the grunt file.
For that scenario, remote files concatenation can be beneficial to the development.
