### ISSUE TITLE
Grunt Install Error

### ISSUE THREAD

**Issue by ijy** [gruntjs/grunt#351]
I've seen a couple of other similar issues listed but they were some months ago and I also haven't been able to find a solution to the problem so I'm just hoping someone can suggest a fix wherever the problem may lie...

I have node v0.8.2 and npm 1.1.36 installed on Mac OS X Lion. Both were installed via Homebrew (it seems that npm is once again included when you install node via homebrew).

When trying to install grunt I get the following errors:

→ npm install grunt -g
npm http GET https://registry.npmjs.org/grunt
npm http 200 https://registry.npmjs.org/grunt
npm http GET https://registry.npmjs.org/grunt/-/grunt-0.3.12.tgz
npm http 200 https://registry.npmjs.org/grunt/-/grunt-0.3.12.tgz
npm ERR! Error: EACCES, mkdir '/usr/local/lib/node_modules/grunt'
npm ERR!  { [Error: EACCES, mkdir '/usr/local/lib/node_modules/grunt']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/grunt',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/grunt',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ 'DirWriter._create (/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23)',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:51:17',
npm ERR!      'Object.oncomplete (fs.js:297:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Darwin 11.4.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "grunt" "-g"
npm ERR! cwd /Users/user
npm ERR! node -v v0.8.2
npm ERR! npm -v 1.1.36
npm ERR! path /usr/local/lib/node_modules/grunt
npm ERR! fstream_path /usr/local/lib/node_modules/grunt
npm ERR! fstream_type Directory
npm ERR! fstream_class DirWriter
npm ERR! code EACCES
npm ERR! message EACCES, mkdir '/usr/local/lib/node_modules/grunt'
npm ERR! errno 3
npm ERR! fstream_stack DirWriter._create (/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23)
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:51:17
npm ERR! fstream_stack Object.oncomplete (fs.js:297:15)
npm ERR! 3 errno
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/user/npm-debug.log
npm ERR! not ok code 0

I'm still getting familiar with the shell side of things and have recently switched to .zsh instead of bash. I have the following export path in my .zshrc file:

export PATH="/usr/local/bin:$PATH"

Following on from (other recommendations)[http://shapeshed.com/setting-up-nodejs-and-npm-on-mac-osx/] I've also include a NODE_PATH in my .zshrc file:

export NODE_PATH="/usr/local/bin/node"

Just in case there's a problem with that. I've checked that the appropriate links are in the correct locations.

Any ideas why this isn't working or how I can resolve the issue?

**Comment by Arsenich** [comment]
I would recommend installing Node and NPM with Homebrew here is great article on how to do that.
for MAC: http://blog.teamtreehouse.com/install-node-js-npm-mac
for Win: http://blog.teamtreehouse.com/install-node-js-npm-windows
