### ISSUE TITLE
Option for file.copy() not to resolve symbolic links

### ISSUE THREAD

**Issue by ghost** [gruntjs/grunt#371]
As part of a copy task, I have a symlink leading to a shared library folder that I want copied to the deploy folder. `file.copy()` resolves the symlink and creates a duplicate of the whole lib folder instead of copying the symlink. Although this works somewhat, I'd prefer to keep the symlink instead of copying its contents.

Can we add an option to `copy()` that leaves symlinks intact?

**Comment by prashant-pokhriyal** [comment]
please anyone can  provide snippet for copying the symbolic link instead of content using grunt-conrtib-copy

**Comment by chhaymenghong** [comment]
@prashant-pokhriyal : you can use this :
https://github.com/gruntjs/grunt-contrib-symlink

Just make sure to exclude the symlink files and directories in your copy tasks, so that it doesn't copy over empty directories which is problematic for grunt-contrib-symlink

**Comment by chhaymenghong** [comment]
Here my config:
  copy: {
            all: {
                files: [
                    {expand: true, cwd: 'WebRoot', src: ['**',
                        // ignore all the files and folder that have symlinks
                        // because "copy plugin" doesn't maintain those links
                        // instead "symlink" task will handle that.
                        '!js/symlinkFolder1',
                       '!js/symlinkFolder2',

                    ], dest: 'dist'}
                ]
            }
        },

 symlink: {
            options: {
                // Enable overwrite to delete symlinks before recreating them
                overwrite: false,
                // Enable force to overwrite symlinks outside the current working directory
                force: false
            },

            expanded: {
                files: [
                    {
                        // you can use relative path to your current Gruntfile.js as well
                        src: ['path to where the actual folder that has all the stuffs'],
                        dest: 'path to where you want to put a new folder that has link to symlinkFolder1'
                    },
                   // same idea here
                   {
                         src: ['path to where the actual folder that has all the stuffs'],
                        dest: 'path to where you want to put a new folder that has link to symlinkFolder2'
                    },
                  

                ]
            }
        },
