### ISSUE TITLE
console.log objects outputs [object object] in qunit tests

### ISSUE THREAD

**Issue by Radagaisus** [gruntjs/grunt#473]
Hi,

Writing `console.log({a: 2})` in QUnit tests will output `[object Object]` to the grunt log.

I have no idea why this is happening. I suspect it's somewhere between stringifying and parsing the object from the temp file that is used to communicate with phantom.

Also, `QUnit.testStart` and `QUnit.testDone` does not work. `QUnit.begin`, oth, does.

Thanks,

**Comment by marcelopm** [comment]
This might be helpful (lodash dependency can be easily remove)

```javascript
...
         log: function() {
		var args = _.toArray(arguments);
		var prepend = '';
		
		var index = _.indexOf(args, 'debug');
		if (index > -1) {
			// remove debug arg
			_.pullAt(args, index);
			
			try {
				// to generate the stack
				throw new Error();
			}
			catch(e) {
				prepend = e.stack.toString().replace(/^Error:/, 'stack:') + "\n\n";
			}
		}
		
                // The last arg for JSON.stringify beautifies the output
		console.log(prepend + JSON.stringify(args, null, 2));
	}
...
```
