### ISSUE TITLE
Starting server on alternate ports.

### ISSUE THREAD

**Issue by sebv** [gruntjs/grunt#534]
Is it possible? The code below seems to imply that only one set of port/base can be configured in Gruntfile.

```
var port = grunt.config('server.port') || 8000;
var base = path.resolve(grunt.config('server.base') || '.');
```

**Comment by dportabella** [comment]
if Gruntfile.js contains:
```
    express: {
      options: {
        port: process.env.PORT || 9000
      },
```
then you can change the port as follows:
`$ PORT=8999 grunt serve`

**Comment by MdShuaib** [comment]
open Gruntfile.js and search for:

`options: {
                port: 9000, // Change this to port: `9001`
                hostname: 'localhost',
                livereload: 35729 // Change this to 35728
},`

> **Just in case you want to run two grunt server at the same time**
