### ISSUE TITLE
Allow for all grunt node.js components to be installed globally

### ISSUE THREAD

**Issue by doberkofler** [gruntjs/grunt#557]
Grunt itself can be installed as global npm module but unfortunately all plugins must be installed locally.
This very much complicates the use of grunt and it would be great to have all grunt modules installed globally.

**Comment by titoBouzout** [comment]
is possible or is not possible to install grunt plugins globally?

**Comment by vladikoff** [comment]
> is possible or is not possible to install grunt plugins globally?

Globally installed modules are an anti-pattern in node/npm.
We don't make the rules, that's how node and npm tooling does things

**Comment by titoBouzout** [comment]
when I create a node project I can use the global modules just fine. Is this really a limitation of grunt, or grunt is following npm on this thing forcing everyone to install locally?

**Comment by vladikoff** [comment]
> Is this really a limitation of grunt, or grunt is following npm on this thing forcing everyone to install locally?

You can probably hack something together but you are on your own with that and we (or plugin authors) cannot support that use case.
