### ISSUE TITLE
Log stacktrace when a task fails

### ISSUE THREAD

**Issue by jzaefferer** [gruntjs/grunt#591]
Grunt 0.4 is terrible about debugging tasks, since it only logs exception messages and throws away the stack. Adding `--verbose --debug` doesn't make a difference. Grunt should log the exception stacktrace by default, since an exception always is a fatal error, there's no point in hiding that behind options.

See also #578 and my comment there.

**Comment by okor** [comment]
+1 This option by default. 

If an author is writing a task for non-authors then it should be up to them to make the call to suppress errors or not.

**Comment by bobfields** [comment]
I can't think of any reason why this wouldn't be the default. No errors means no stack trace, even with it turned on, same as pretty. Errors give us a place to look, to fix the problem. Even those who are not task authors can report the error to the authors.

**Comment by Kuroky360** [comment]
+1

**Comment by r-tanner-f** [comment]
-1 for on by default. I don't want a stack trace dumped for every legitimate error that a plugin throws at me. `--stack` is accessible enough, and `grunt.option('stack', true);` is portable enough if your dev team can't handle a CLI flag.

**Comment by SteveHarris** [comment]
-1 for on by default, but maybe offer info in the error display like (--stack for details)

**Comment by ccorcos** [comment]
I'm confused about the contention here. I don't see any reason you'd want to hide the stack trace when you get an error and grunt exits with 1. Its completely worthless when that happens.

**Comment by FaJo8080** [comment]
+1 for default

**Comment by joeytwiddle** [comment]
If the developers don't want to make it a default, a middle ground solution could be to raise awareness of the `--stack` option:

    // before
    Warning: Test Error Use --force to continue.

    // after
    Warning: Test Error Use --force to continue or --stack for details.

Alternatively, enable the stack option when `--verbose` or `--debug` are used. (I tried both of those options, then `grunt --help`, and then I started googling, which brought me here.)

**Comment by ArmorDarks** [comment]
I think the issue is that some errors do not have any meaning without stacks, and in rare cases it would be better to Task author to enforce stacks output for some fatal errors.

I'd propose following addition:

```js
// Last argument when set to `true` enforces output of the error with stack trace
grunt.log.error(new Error('Hey, too bad :('), true)
```
