### ISSUE TITLE
Unable to make full use of options because of how nopt works

### ISSUE THREAD

**Issue by sbrandwoo** [gruntjs/grunt#603]
Currently the use of flags for command line options (where a flag is an option with no value) is limited in Grunt, due to how nopt handles unknown arguments.

There is a [relevant issue for nopt](https://github.com/isaacs/nopt/issues/11) for this, but here is also an example - if I run:

```
$ grunt test --one --two three
```

I would get the following back from grunt:

```
{ one: '--two', tasks: [], npm: [] }
```

Because `--one` is an unknown parameter to nopt, it assumes that its value is `--two` and as a result all of my parameters get destroyed.

The only workaround I know is to use the flag as the very last argument of the command, but this limits the user to one flag per command:

```
$ grunt test --two three --one
```

```
{ two: 'three', one: true, tasks: [], npm: [] }
```

I'm not quite sure how you'd fix this, perhaps wait for an upstream change, or perhaps allow tasks to submit a list of known options to grunt?

**Comment by mitchelldavis** [comment]
:+1:

**Comment by viniciuspires** [comment]
+1
