### ISSUE TITLE
npm install -g grunt isn't copying the grunt binary into my bin folder

### ISSUE THREAD

**Issue by ChrisWren** [gruntjs/grunt#672]
After installing the grunt dependencies, my terminal doesn't output a message that states the grunt binary is now in my local binary folder.

Usually global node modules are copied into your binary folder, like when I run `npm install -g docco`, my terminal outputs:
`/usr/local/bin/docco -> /usr/local/lib/node_modules/docco/bin/docco`

Because the grunt binary isn't in my local binary, it is not available in the terminal, so when I type `grunt`, I get back:

`-bash: /usr/local/bin/grunt: No such file or directory`

**Comment by ekkis** [comment]
I have the same issue on OSX 10.11.6 running Node v7.3.0 and npm 3.10.10 (which I installed using brew).  when I run `sudo npm install grunt-cli -g` everything seems fine but if I try to actually run it I get the error ChrisWren points to.

I have read through the getting started link provided but it does not address the problem.  can you help?

**Comment by ekkis** [comment]
I should mention that in my `~/.npmrc` I have set `prefix=~/.npm` and, curiously, even though my install specifies `-g` (which to my mind means it should install to some system place (like `/usr/local/bin`)) I see the installation where the prefix indicates... which might explain the problem but leaves me wondering how to do the installation globally

**Comment by ekkis** [comment]
here's the output of my command, from which it is evident that no copy to the `/usr/local/bin` is taking place

```
aprilis:~ ekkis$ sudo npm install grunt-cli -g
/Users/ekkis/.npm/bin/grunt -> /Users/ekkis/.npm/lib/node_modules/grunt-cli/bin/grunt
/Users/ekkis/.npm/lib
└─┬ grunt-cli@1.2.0 
  ├─┬ findup-sync@0.3.0 
  │ └─┬ glob@5.0.15 
  │   ├─┬ inflight@1.0.6 
  │   │ └── wrappy@1.0.2 
  │   ├── inherits@2.0.3 
  │   ├─┬ minimatch@3.0.3 
  │   │ └─┬ brace-expansion@1.1.6 
  │   │   ├── balanced-match@0.4.2 
  │   │   └── concat-map@0.0.1 
  │   ├── once@1.4.0 
  │   └── path-is-absolute@1.0.1 
  ├── grunt-known-options@1.1.0 
  ├─┬ nopt@3.0.6 
  │ └── abbrev@1.0.9 
  └── resolve@1.1.7 
```

**Comment by latheva** [comment]
Hello, on mac
`sudo npm install grunt -g --prefix=/usr/local` fix the issue

Cheers
