### ISSUE TITLE
Windows: 'grunt' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by mcandre** [gruntjs/grunt#774]
When I `npm install -g grunt`, grunt is not adding a binary to `C:\Documents and Settings\apenneba\npm\`. The result is that attempts to run `grunt` in Command Prompt fail with:

```
'grunt' is not recognized as an internal or external command
```

System:

I repeated `npm install -g grunt`, `grunt` in Command Prompt as well as Git Bash. In either case, grunt fails to add itself to `PATH`.

Other packages like mocha, jshint, nodeunit, and tap are successfulling adding themselves to `PATH`.

```
$ specs node git os
Specs:

specs 0.4
https://github.com/mcandre/specs#readme

npm --version
1.2.17

node --version
v0.10.3

git --version
git version 1.8.0.msysgit.0

systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows XP Professional
OS Version:                5.1.2600 Service Pack 3 Build 2600
```

**Comment by JediMindtrick** [comment]
@rofrol Thanks for the hint on how to determine npm path being used.  In my case I'm using chocolatey to install and that's a strong preference.  Some variation of this is going to end up working for me in powershell
```
$oldPath = [Environment]::GetEnvironmentVariable('Path','Machine')
$npmBin = (npm config get prefix)
$newPath = $oldPath + 'C:\Users\Administrator\AppData\Roaming\npm;' + $npmBin + ';'
[Environment]::SetEnvironmentVariable('Path',$newPath,'Machine')
```

**Comment by rakeshsagar29** [comment]
Still not working for me. Did the above steps.S
Steps that I followed : 
1 . npm install -g grunt-cli
2 . echo ~ path=%PATH%;%APPDATA%\npm

I infact ran "npm install -g grunt-cli" again . Then npm update. Still when I ran "where grunt" ,I got  "INFO: Could not find files for the given pattern(s)." 
Can someone please help.. :( . Its damn frustrating.

**Comment by Stephn-R** [comment]
Have you tried looking into the source files for the terminal you are using? If you are using Terminal vs iTerm vs [ some other terminal ], your source file may reference a different location for your binary files.

For example, my machine [ Mac ] installs npm global binaries like grunt into the ~/usr/bin directory rather than AppData\Roaming\npm

**Comment by JediMindtrick** [comment]
@rakeshsagar29 Forgive me if you've already done this bit...
but if you open a command prompt/powershell, and run 
```echo %PATH%``` 
do you see the \AppData\Roaming\npm directory in your path?

**Comment by rakeshsagar29** [comment]
@Stephn-R  and @JediMindtrick  Thanks for the response. 
I did everything that you have mentioned in your comments. I could see  \AppData\Roaming\npm in path too. Seems , there was some problem in my system itself(unidentified) . I had run the same set of commands in my colleagues system and was working fine for her. Now I got my system changed , and did everything again. And whoa..grunt is running :) . I think there is a reason my lead hates windows.

**Comment by Stephn-R** [comment]
@rakeshsagar29 I am glad to hear the good news! We all have our reasons for preference of OS :) #MacLife

**Comment by krishnajpsnr** [comment]
path=%PATH%;%APPDATA%\npm   .... is working . Thank you @andi69 .  But it looks like a temporary fix. This command should be  given every time you restart you PC. 

To have permanent fix  I have added ' %APPDATA%\npm ' to the path variable . It has been working fine.

**Comment by sravananantula** [comment]
Thanks it is working for me

**Comment by sravananantula** [comment]
path=%PATH%;%APPDATA%\npm working for me

**Comment by Theowdfb** [comment]
@shama, @nschonni Thanks, this works for me as well!

**Comment by rams0404** [comment]
install Grunt's command line interface (CLI) globally,
npm install -g grunt-cli.
No need to set the path.. This will put the grunt command in your system path, allowing it to be run from any directory.(http://gruntjs.com/getting-started)

**Comment by paragwaghela** [comment]
path=%PATH%;%APPDATA%\npm  
Work for me too

**Comment by bashisha** [comment]
This worked for me:
$env:path += ";" + (Get-Item "Env:AppData").Value + "\npm".
The catch is you need to run the above command in ur profile, as soon as you open powershell script.

**Comment by haephrati** [comment]
I had that problem and solved it by calling
`npm install -g grunt-cli `
