### ISSUE TITLE
How to tell grunt to copy all images to dist?

### ISSUE THREAD

**Issue by heygambo** [gruntjs/grunt#794]
Hi,

I have a project where I load some images client side via javascript.
grunt doesn't recognize those and doesn't copy them to "dist".

How can I modify grunt to copy everything?

Regards,
Christian

**Comment by NEOLPAR** [comment]
Thanks it also was useful to me!

**Comment by NavinST** [comment]
Awesome!. It works for me

**Comment by maryamklabib** [comment]
Thanks so much! 👍

**Comment by Ajaykumarkonda** [comment]
1) I am able to copy app/images from these <%= yeoman.app %>/images. How to copy assets images that are not in app folder to dist folder.
2) I cannot change file rev for static images that are in html file and i am able to change in css file.

Can any one help me to resolve it.
