### ISSUE TITLE
grunt.task.run - passing arguments

### ISSUE THREAD

**Issue by netpoetica** [gruntjs/grunt#829]
When you have a task that relies on command line input which it retrieves via the grunt.options helper, but you want to be able to call that task programatically, you should be able to pass an command line args object or options object of some sort to the grunt.task.run function, and/or there should be a more robust run function that will allow for this.

``` javascript
// As String
grunt.task.run('mytask', { 
  cmdargs: '--all --cleanup'
});
// As Array (boolean commands only)
grunt.task.run('mytask', { 
  cmdargs: ['all',' cleanup']
});
// As Object
grunt.task.run('mytask', { 
  cmdargs: {
     cleanup: true,
     all: true
  }
});
```

Looking at the source in utils/task, it seems like this may be possible already but it's not clear to me how I could achieve this without playing magic with the args object.

Based on the current system and the way you guys parse args via grunt.task.run, I think the only way to achieve this would be something like

```
grunt.task.run('myTask:myTarget --cleanup --all')
```

And make the parse function a little more robust, capable of then parsing the target string for args.

**Comment by johnteh** [comment]
@netpoetica, @shama
Apologises for returning to this thread so late after it has been closed, but i have been wrestling with this exact problem for a while and wondered if anyone could shed light on it.

Based on this example below (not live code so forgive syntax mistakes), if we run 'grunt' then #1 is set to 'false', then #2 gets the value 'false'.

If i run 'grunt live-watch' then #1 is 'false', #2 is assigned 'false', #3 sets 'lr' to 'true' and #4 outputs 'true'. But the command at #5 is always 'false'.

It seems all options are initialised from the command line, then tasks are initialised - then it seems any logic within the tasks cannot be changed via a registeredTask.

I have logic in my tasks i wish to move out into the registeredTasks so i don't have to enter values on the command line. Replacing the line at #3 with the suggestions in this thread has not been successful.

```
module.exports = function(grunt) {
  var lr = grunt.option('lr') || false;    // #1
  grunt.initConfig({
    watch: {
        html: {
            files: [], 
            tasks: [],
            options: {
                livereload: lr    // #2
            }
        }
    })()
  });
  grunt.registerTask('default', ['watch']);
  grunt.registerTask('live-watch', function() {
      grunt.option('lr', true);    // #3
      grunt.task.run('watch');    //#5
      grunt.log.writeln(lr)    // #4
  });
};
```

Is there any advice to point me in the right direction to a solution?

Thanks

**Comment by shama** [comment]
@johnteh Try this instead:

```js
grunt.registerTask('live-watch', function() {
      grunt.config('watch.html.options.livereload', true);    // #3
      grunt.task.run('watch');    //#5
      grunt.log.writeln(lr)    // #4
  });
```

The issue is `var lr = grunt.option('lr') || false` will create a variable named `lr`. That variable isn't bound to `grunt.option('lr', true)`. So once you set that variable, calling `grunt.option()` won't update that variable.

To modify that variable you would need to `lr = true` but it's better to set the config directly with `grunt.config()` when dynamically running tasks.

**Comment by johnteh** [comment]
@shama ah yes i see my error there.
Would having a js function '#1' inside a plugin option effect the assigning of values '#2'? When i try this out im not able to change the value of 'lr'.

```
module.exports = function(grunt) {
  var lr = grunt.option('lr') || false;    // sets 'lr' to 'false' by default
  grunt.initConfig({
    watch: {
        html: {
            files: [], 
            tasks: [],
            options: {
                livereload: (function() { // #1
                  if (lr) {
                    // something true
                  } else {
                    // something false
                  }
                })();
            }
        }
    })()
  });
  grunt.registerTask('default', ['watch']);
  grunt.registerTask('live-watch', function() {
      lr = true  // #2
      grunt.task.run('watch');
  });
};
```

**Comment by shama** [comment]
@johnteh Unfortunately the function wouldn't help you there either. As `(function() {})()` (IIFE) calls that anonymous function immediately when the Gruntfile is evaluated. If that option took just a `function () { return lr }`, changing `lr` would work as the function would get called when the option was retrieved thus have the latest value.

But that value already lives in the config, so instead we just change the value in the config instead: `grunt.config('watch.html.options.livereload', true)`.

**Comment by RobinHerbots** [comment]
@johnteh,

You can try it like this.

```
module.exports = function(grunt) {

 function generateConfig() {
        return _.extend(grunt.config.data, 
{
    watch: {
        html: {
            files: [], 
            tasks: [],
            options: {
                livereload: (function() { // #1
                  if (lr) {
                    // something true
                  } else {
                    // something false
                  }
                })();
            }
        }
    })()
  }

  var lr = grunt.option('lr') || false;    // sets 'lr' to 'false' by default
  grunt.initConfig(generateConfig());
  grunt.registerTask('default', ['watch']);
  grunt.registerTask('live-watch', function() {
      lr = true  // #2
      generateConfig();
      grunt.task.run('watch');
  });
};
```

**Comment by RobinHerbots** [comment]
@johnteh , 

Sorry, didn't notice the year (2013 & 2017)
