### ISSUE TITLE
grunt.file.expand exclude files in a directory pattern

### ISSUE THREAD

**Issue by tinganho** [gruntjs/grunt#891]
I want to achieve this:

``` javascript
var src = [
   'some-folder/**/*',
   '!some-folder/test/test.js'
];
grunt.file.expand({ filter: 'isFile'}, src).forEach(function(path) {
  // Remove file or folder in path
});
```

Removes all files except `some-folder/test/test.js`. But the problem is if `some-folder` is empty, the folder is not removed. I could add a check if the folder is empty, though it would be cleaner to do it like this:

``` javascript
var src = [
   'some-folder', // Removed wild cards
   '!some-folder/test/test.js'
];
grunt.file.expand(src).forEach(function(path) {// Removed filter option
  // It now return the whole folder path if no matching exclusion occurs
  // If matching exclusion occurs it returns all file paths, except excluded files and folders
});
```

It is much more intuitive, simpler and lesser code to write

**Comment by Samvanst** [comment]
Nice @shama  i was looking for this !

**Comment by shama** [comment]
@Samvanst Check out https://gruntjs.com/configuring-tasks#custom-filter-function The built-in filter functions themselves come from Node's fs.Stats: https://nodejs.org/docs/latest/api/fs.html#fs_class_fs_stats
