### ISSUE TITLE
Update nopt to 2.x.x

### ISSUE THREAD

**Issue by cowboy** [gruntjs/grunt#908]
Note that non-standard CLI arguments will default to booleans, which is a change. This will need to be documented. It can't be changed before 0.5.0 because it will break backwards compatibility with users expecting the current behavior.

nopt@0.1.x (now):

* `--foo bar` results in `grunt.option("foo") === "bar"`
* `--foo=bar` results in `grunt.option("foo") === "bar"`

nopt@0.2.x (the future):

* `--foo` results in `grunt.option("foo") === true`
* `--foo bar` results in `grunt.option("foo") === true` and task `bar` being run
* `--foo=bar` results in `grunt.option("foo") === "bar"`

Also, a patch to do this https://github.com/isaacs/nopt/issues/24#issuecomment-24264343 would be awesome.

**Comment by Coridyn** [comment]
I've made this module (https://github.com/widgetworks/nopt-grunt-fix) to work around this problem until Grunt 0.5.0 can address this issue.

**Comment by cspotcode** [comment]
@Coridyn: Thanks!  nopt-grunt-fix works like a charm.

**Comment by justinhelmer** [comment]
@Coridyn you are a gentleman and a scholar.

**Comment by shama** [comment]
Fixed on 9a8bb8573f26cffe007e25f9ab1160d8e3ed3c97 and changes will be documented in the upcoming release notes.

**Comment by justinhelmer** [comment]
@shama thanks
