### ISSUE TITLE
Promoting Grunt?

### ISSUE THREAD

**Issue by cowboy** [gruntjs/grunt#926]
## How can we better promote Grunt?

I, along with @sindresorhus and @kahlil, who emailed us recently, have a few ideas.

We should:

* Tweet more consistently.
* Publish regular blog posts highlighting favorite plugins, tutorials, releases, etc.
* Create our own tutorials, screencasts, guides.
* Adjust docs to address community questions or misunderstandings.
* Respond to StackOverflow questions tagged `gruntjs`.
* Respond to relevant community comments, in general.

What else?

**Comment by vladikoff** [comment]
We are just gonna try to release a new version for now
