### ISSUE TITLE
Add bin into local grunt

### ISSUE THREAD

**Issue by shama** [gruntjs/grunt#943]
Reference TryGhost/Ghost#1053

I think it would be nice if `npm install grunt` included a bin script. Then Grunt users could recommend `npm install && npm test` without explaining the additional step to install the grunt cli globally and have the package dependencies completely self contained.

@vladikoff had the good idea of just adding `grunt-cli` as a peer dependency to Grunt.

The current solution is to `npm install grunt-cli` locally and reference in the package.json with:
```json
{
  "scripts": {
    "test": "grunt test"
  }
}
```
in which npm will find the local `node_modules/.bin/grunt` binary installed by grunt-cli.

I think at the very least, this message https://github.com/gruntjs/grunt-cli#installing-grunt-cli-locally should be removed and a completely local install method should be officially supported.

**Comment by vladikoff** [comment]
@JKAussieSkater this is gonna be a change for the "docs" if https://github.com/gruntjs/grunt/issues/1438 lands, for your information.

**Comment by shama** [comment]
This is done on fb9dd08a78965fb0e9a141404d7a25c30c1f75c4. When `grunt-cli@1.0.0-rc1` is released, I'll ask @vladikoff to update his PR GH-1438 to point to that version.

**Comment by JKAussieSkater** [comment]
@vladikoff, noted!
