### ISSUE TITLE
current Gruntfile.js path

### ISSUE THREAD

**Issue by rweng** [gruntjs/grunt#965]
Hi,

I have a task in my tasks folder that is supposed to run a script in my project. Now I am thinking, is there a way to get the project root without defining it explicitly in the Gruntfile? Since in my projects the Gruntfile is always at the top level of the project, it would be enough to get the currently executing Gruntfile. Can I do this?

Basically I want to be able to do s.th. like this in my task (independent where the task is defined):

```
spawn(grunt.root + '/bin/file')
```

Thanks!

**Edit:**

`process.cwd()` seems to work, but it is kind of un-intuitive since I'd expect `process.cwd()` to return `path/to/root/subfolder` if grunt is called in the `subfolder`

**Comment by PeterHorvathIsento** [comment]
It is not fully true: if you load a task by grunt.loadTasks(), I get the cwd to the path of the actually included file, and not to the original Gruntfile. This is very annoying.
